### ISSUE TITLE
Temperatur Kangoo und Fluence

### ISSUE THREAD

**Issue by kaimaik** [fesch/CanZE#105]
Hallo,
kann man die Temperatur vom Kühlwasser (Ladegerät)
und die Temperatur der Heizung (Wasser) mit einbauen ?

**Comment by yoh-there** [comment]
@avataranedotas: maybe you can have a look at this? I have no idea where to look

**Comment by yoh-there** [comment]
Comment in email: 

Beim ICARsoft werden die Temperaturen angezeigt.

**Comment by yoh-there** [comment]
That would certainly help. Please state not only the value but also in which module (ECU) you find it and the id of the query. Thanks!

**Comment by kaimaik** [comment]
ok.werde ich machen.
Allerdings erst morgen :-)

**Comment by avataranedotas** [comment]
In english?

**Comment by yoh-there** [comment]
Sorry. "Can you get to the temperature of the cooling water of the charger and water temperature of the heater?" It should be in the i907, so I suspect ISO-TP commands. Have you figured those? We're talking Kangoo, it seems closer to a Fluence than a Zoe, not sure.

**Comment by kaimaik** [comment]
Am 16.10.2015 23:23, schrieb Alexandre Moleiro:

> In english?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/fesch/CanZE/issues/105#issuecomment-148840002.
> 
> ok.

Antworten kann ich nur in deutsch.

ok ?

**Comment by fesch** [comment]
Ja, ich kann ja übersetzen ;-)

**Comment by kaimaik** [comment]
ich hab hier mal die Werte vom i907 und dem Kangoo ermittelt.

Alles Werte vom EVC

109 = Temperatur der Antriebsbatteriewanne
116 = Temperatur vom Kühlmittel der Heizung
183 = Aussentemperatur HEX Code= 33B1
195 = Temperatur vom Kühler (Ladegerät) mit HEX Code= 33F2
196 = Temperatur vom Ladegerät mit Hex Code = 33F6 wobei
dieser Wert während der Fahrt sehr unterschiedlich ist.

**Comment by yoh-there** [comment]
109 = Battery compartment temp. (22 20 01) ?
116 = cooling fluid temp (22 33 7)?
183 = outside temp (22 33 B1)!
195 = cooler temperature from charger ( 22 33 F2)!
196 = ?? temp, rapidly changing (22 33 F6)
These are all ISO-TP queries directed to the EVC

**Comment by avataranedotas** [comment]
According to my data for the Fluence:
Request 0x 22 33 07 to the EVC should give you the heating water temperature +40C

In the Fluence the cooling water for the charger is the same as for the Inverter block, I don't have it confirmed but might be request 0x 22 33 F2 or 0x 22 33 F6

**Comment by kaimaik** [comment]
Der Kangoo und der Fluence haben den gleichen Motor.
Das Ladegerät und der Inverter sollten auch gleich sein .
Die Temperaturen  vom Inverter block schwanken je nach fahrweise.Wenn viel Gas gegeben wird gehen die Temperaturen sehr stark nach unten.
Bei einer längeren Fahrt mit wenig Gas verändert sich die Temperatur nur wenig.

Dann müsste 0x 22 33 F6 die Temperatur vom Inverter sein

**Comment by yoh-there** [comment]
@avataranedotas Are you interested in building this part in CanZE? ("No" is a valid answer!!) It could be based on the technical charging activity. And I think if build should be put in the (new) technical fragment anyway.

I have closed #87 which in my opinion should be on the same screen due to lack of interest. So far I have not seen much drive to implement any of this either.......

**Comment by avataranedotas** [comment]
So basically the idea is to get the temperatures for the various cooling circuits? Is that correct?

**Comment by yoh-there** [comment]
I think yes, preferably with the fan status added. Zoe is probably a tad different because it can cool the batteries through a separate evaporator on the CLIMA. On the other hand, you guys have the peltiers.

**Comment by kaimaik** [comment]
Ich benötige die Temperaturen dringend.
Für Heizung und das Ladegerät mit dem ganz großen Lüfter

**Comment by yoh-there** [comment]
@kaimaik Not to be rude, but I don't think a lot of people understand WHY this is needed . And we really have no resources at all, it is all a labour of love. Why is this useful information?

**Comment by kaimaik** [comment]
Tut mir leid wenn das unhöflich rübergekommen ist.
War keine absicht.Sorry
Ich habe bei mir eine Standheizung eingebaut.
Diese Temperauren möchte ich gern überwachen.
Wann die Boardheizung einschaltet und wieviel die Standheizung dazu heizt.

Die Temperaturen vom Ladegerät sind mir auch wichtig.
Ich habe gern ein kühles Ladegerät : -)

**Comment by yoh-there** [comment]
OK, makes more sense, Standheizung, interesting. I assume electrical, externally powered then.

 And I was not accusing you of being unhöflich, I was trying to avoid being rude myself!!! :-)

**Comment by kaimaik** [comment]
alles ok :-)

**Comment by kaimaik** [comment]
Typ2 für den Kangoo oder Fluence
![20141003_135000](https://cloud.githubusercontent.com/assets/15162489/11196198/6ef9e30c-8cb6-11e5-9171-e08b0944bad4.jpg)

**Comment by yoh-there** [comment]
Sie nützen die normale Type2 auch für Standheizung? Dass müssen sie noch mal am einem tag erklären bitte ;-)

**Comment by kaimaik** [comment]
Am 16.11.2015 23:09, schrieb yoh-there:

> Sie nützen die normale Type2 auch für Standheizung? Dass müssen sie 
> noch mal am einem tag erklären bitte ;-)
> 
> Nein.aber möglich !

Typ2 ist zum laden.

Standheizung ist mit Diesel (Webasto)

**Comment by kaimaik** [comment]
![20151017_140200](https://cloud.githubusercontent.com/assets/15162489/11196515/c02fda3c-8cb7-11e5-8a0c-b2b3261c12ba.jpg)

**Comment by fesch** [comment]
Dans einzig Diesel das ich in meinem Zoé hatte war für meinen Rasenmäher ... und dabei bin ich mir doch echt dämlich vorgekommen als ich mit dem Elektrowagen zur Tanke fuhr um den Kanister auf zu füllen ;-) ;-D

**Comment by kaimaik** [comment]
ja das kenne ich :-)

**Comment by kaimaik** [comment]
aber besser als frieren

**Comment by avataranedotas** [comment]
I now have confirmed data in the Fluence for the following:
-Evaporator temperature
-Water temperature used for heating
-External ambient temperature
-Internal ambient temperature
-Motor water pump speed
-Charger water pump speed
-Heating water pump speed
-DC-DC converter temperature
-Inverter temperature
-Battery temperature probes 1,2,3 and 4

I could not find any information on Radiator fan status

**Comment by avataranedotas** [comment]
I also have unconfirmed data about the battery cooling fans speed.

yoh-there, I don't have much time for the App, but I can provide you with the addresses of the data above.

**Comment by yoh-there** [comment]
Well I bet that covers all. If you added it to the CanZE spreadsheet model or can give it to me spreadsheet-style, in would not be crazy much work anymore I guess. The battery temp I won't take on as the heatmap covers that nicely.

**Comment by kaimaik** [comment]
Jetzt fehlt noch die Temperature Ladegerät (Wasserkühler) oder habe ich da was übersehen ?

**Comment by yoh-there** [comment]
The experimental temperatures just didn't make it into today's release but it is committed to the master branch. I will close this issue now, but feel free to reopen next week if things are wrong (which I am sure they are as it is totally untested ;-) )

**Comment by yoh-there** [comment]
Hello @kaimaik . Any feedback on this issue? If it all works, we could promote it from "experimental" to "technical"?

**Comment by kaimaik** [comment]
Hallo Alexandre,
bei mir funktioniert grad CanZE nicht.
Bob will einen Kangoo leihen und schaue wo das Problem mit den Daten liegt

**Comment by yoh-there** [comment]
Oh d'uh. I knew that. Sorry.

**Comment by kaimaik** [comment]
Das wird schon.
Bob ist da ganz zuversichtlich.
Ich auch :-)

**Comment by kaimaik** [comment]
Die neue Version liefert wieder Daten :-)
Top !

Bei der neuen Version werden die Temperaturen nich richtig angezeigt.
wie kann ich die ganzen Frames "sehen" ?
Beim Icar Soft 907 werden die Temperaturen angezeigt.
Es muss doch möglich sein diese Parameter auszulesen und in CanZE einzubauen.
