### ISSUE TITLE
Hardware Issue - Acer Iconia B1

### ISSUE THREAD

**Issue by andyfras** [fesch/CanZE#122]
I have tried build 2015-10-13 and 2015-10-18 - in each case it shows ' ELM is not responding'.

Konnwei KV902 Adapter

Acer Iconia Android version 4.1.2

It works OK on my Moto G phone.

**Comment by yoh-there** [comment]
If you use more than one device, please realize the KV902 will only remember ONE paired phone. Switching to another device you need to re-pair it all over again. Let us know please if this is the issue. It is the sort of issue that is completely out of our control.

For the time being I am assuming it is exactly this and I am marking this issue as Open (so you can easily respond) and WontFix.

**Comment by andyfras** [comment]
Both devices connect to the KV902 without re-pairing, so it seems that my KV902 can remember more than 1 paired device.

**Comment by fesch** [comment]
... which I can confirm for the MaxiScan too.

**Comment by yoh-there** [comment]
In that case, for the moment I can only advice to install Bluetooth Terminal https://play.google.com/store/apps/details?id=Qwerty.BluetoothTerminal on the Acer, connect to the device (you need to set Append Newline on in the settings screen) and send ATZ Please state the response here.

In the current source (and the build of upcoming Sunday) there will be a screen in the app showing the low level conversation, so as an alternative to Bluetooth Terminal and/or Android Studio, you could opt to wait for that one.

**Comment by andyfras** [comment]
Thanks. I'll wait for the next build.

**Comment by yoh-there** [comment]
Dear @andyfras . Can you please update us on this issue? Thanks

**Comment by andyfras** [comment]
I loaded the latest version (25-10-15), but it still fails with "ELM is not responding" and a "Timeout on [atws]" error.

**Comment by fesch** [comment]
Did you try the terminal thing yoh-there asked you for?

**Comment by yoh-there** [comment]
What it means is that Bluetooth communication is established, but the ELM it is not talking. I have no idea what to think of this. In any case it is out of the realm of our influence. As said above you can try to use Bluetooth terminal. I am regretfully closing this issue and will include the Acer Iconia B1 as a possibly problematic device on the web page.
