### ISSUE TITLE
Starting CanZE for the first time, crashes if no bluetooth device selected

### ISSUE THREAD

**Issue by avataranedotas** [fesch/CanZE#129]
When starting CanZE after a fresh installation the bluetooth device is not set, so getSharedPreferences will get null.
Attempting to start an activity will result in app crashing.

Prevent activities from opening until device selected?
OR
Force opening of the settings activity?
OR
????

**Comment by fesch** [comment]
Confirmation:
- open settings
- hit clean settings button
- close application (fully!)
- reopen application
- click on any button

**Comment by fesch** [comment]
solved
