### ISSUE TITLE
Formal and legal disclaimer first time App is open

### ISSUE THREAD

**Issue by avataranedotas** [fesch/CanZE#140]
I would suggest that on the first time the app is open (after installation) a disclaimer be presented to the user that would have to click on checkbox and accept button before the app starts connecting to the car.

**Comment by fesch** [comment]
I will do that ... but please, could anyone provide me the text to display? I must admit that this kind of texting is none of things I'm really good in ...

**Comment by yoh-there** [comment]
I'd simply copy the text from the Download page of the website :-)

**Comment by fesch** [comment]
It's in the code now. To test it:
- Open CanZE
- Goto settings
- Clear the cached data
- Quite CanZE while in the Settings-Screen
- Restart CanZE 
- Voilé!

**Comment by yoh-there** [comment]
Erm no? What do you mean with quitting CanZE while in the settings screen? I even tried clicking "center" button to get to Android, then clear last active apps, nothing gives me the disclaimer.

**Comment by fesch** [comment]
Quit CanZE using the "show apps" button (on mine it is a simple white square), then slide CanZE away to close it.

**Comment by yoh-there** [comment]
OK, yes, did that, a "pkill -9 CanZE" equivalent ;-) But....

I do get "You first need to adjust....", but no disclaimer.

**Comment by fesch** [comment]
I will try on some other device later ...
![screenshot_2015-10-25-20-29-04](https://cloud.githubusercontent.com/assets/1027354/10717400/2e51f9fe-7b57-11e5-83d0-ccef47cde6a4.png)

**Comment by yoh-there** [comment]
I like the "No" button ;-) But no, doesn't work here, sorry

**Comment by yoh-there** [comment]
Owwww, when I normally close an "unset" CanZE now, it crashes (as in, seems to close normally, then a "CanZE stopped" popup. So it has to do wit the failing disclaimer as everything is OK after settings have been saved.

**Comment by fesch** [comment]
Very strange ... any exception in the LogCat? Does the warning pop-up if you unset the "Safe Driving Mode"?

**Comment by yoh-there** [comment]
Works. Half-compiled crap on my end. Apologies :-/

**Comment by fesch** [comment]
Ufff ...

**Comment by yoh-there** [comment]
Well, maybe. Could be your last "code move" commit did the trick. Works after that one, thanks!

**Comment by avataranedotas** [comment]
I think the part "By using this software you are interfering with your car and doing that with hardware and software beyond your control, created by a loose team of interested amateurs in this field. Any car is a possibly lethal piece of machinery and you might hurt or kill yourself or others using it, or even paying attention to the displays instead of watching the road." should also be in, with bigger text than the formal part.

**Comment by fesch** [comment]
![screenshot_2015-10-26-07-37-58](https://cloud.githubusercontent.com/assets/1027354/10722817/ab82a2a4-7bb4-11e5-8eb7-5be1abba2c3d.png)

**Comment by avataranedotas** [comment]
Perfect!
