### ISSUE TITLE
Bug in payload bitcount handling for SINGLE ISO-TP frames

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#19]
Bug found (and fixed) in the ELM driver, that removed the first payload byte. Probably caused my miscounting startbit for single frame UDS messages, while non-UDS messages are very often FIRST/NEXT (where the bug AND the miscounting was not present.

While the issue is closed in the code, it needs to be double cecked in the spreadsheet and in the initialisation of the Fields class, so I am leaving this open.

**Comment by yoh-there** [comment]
AFAIK fixed throughout the code.

**Comment by fesch** [comment]
Did you make a push?

**Comment by yoh-there** [comment]
To yoh-there/CanZE (yesterday): yes. Pulling into fesch: no. I haven't dared doing that to be honest.

**Comment by yoh-there** [comment]
This has been fixed now. Issue closed.
