### ISSUE TITLE
Background task

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#191]
Allow CanZE to live in the background (through a setting) instead of stopping completely. This will be especially useful when logging is implemented.

@avataranedotas did this already in FluenceSpy, so the basics should be available

**Comment by fesch** [comment]
Having done the BT thing, I will do that ... will not be too difficult.
When this option is switched on, a notice will be displayed, informing the user to better connect his tablet to some power source if in longer use.

**Comment by yoh-there** [comment]
Turned out to be default ON (and then of course no warning). Is that what you intended?

**Comment by fesch** [comment]
No, should be default OFF ...
