### ISSUE TITLE
Copy over all info Alexandre extracted from the i907

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#20]
Need to reformat the graphical representation in Alexandre's sheet to the formal description in the main sheet. Beware of proper bit positions, these are not always correct in the table headers!

**Comment by fesch** [comment]
Having the X10 now, we only need to add his ISO-TP frames ...

**Comment by yoh-there** [comment]
The XML files we recently found maybe a HUGE help. Maybe CLIP has the same files, including the more modern ECU's? :-)

**Comment by yoh-there** [comment]
Closing this issue as we have more recent XML files which I was also able to dissect. This will find it's way into the new diagnostics screen.
