### ISSUE TITLE
Battery screen: High temperatures does not fit in the chart

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#203]
See screenshot.
When the compartment temperatures (must be battery modules temperatures I think) are above 30°C, it does not fit in the chart.
![screenshot_2015-11-07-02-25-05 battery temps does not fit in chart](https://cloud.githubusercontent.com/assets/10838083/11048051/ee8fc48c-8735-11e5-9294-4face04eaa19.png)

**Comment by fesch** [comment]
Hot thing!

**Comment by HarmOtten** [comment]
I've seen up to 47°C during my trip to Norway.
