### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by fesch** [fesch/CanZE#229]
Frames.init code depends on Fields.init code which depends on Frames.init code ... --> out of memory

**Comment by yoh-there** [comment]
Oops

**Comment by yoh-there** [comment]
It is of that bloody getCar() that doesn't belong in Fields anyway ;-)

What do you propose? Move to global in Main, or a Car Class? I will fix it either way

**Comment by fesch** [comment]
Just tried to overload the Frames.fillStatic and default to a Zoe, then added a car parameter to reloadTiming that call fillStatic with the same parameter. As the frame are anyway reloaded after the fields are being initialized, this does the trick.
But putting the CAR into the MainActivity would be the logical way to do, as all settings are there and this is the first class to be loaded anyway. So that would make sense ...

**Comment by yoh-there** [comment]
I agree. Will do

**Comment by yoh-there** [comment]
This should be better.
