### ISSUE TITLE
All log files emty

### ISSUE THREAD

**Issue by macfrank** [fesch/CanZE#234]
Samsung Galaxy S2, Android 4.1.2, recommended KM902 Dongle, writing to sd0.

Bluetooth connection works, and App shows data. The CanZe folder was created and log files are created too. But they do not contain data. Size 0 Byte. 
I now have several .log files in the CanZe folder but without content.

Did I miss some setting/action or is it a bug?

**Comment by yoh-there** [comment]
Well yes and no. In the settings screen there are two logging "ticks":
- Log to sdcard1: this is a prelude to a logging function for car parameters. It is not functional yet and leads indeed to empty log files. Best to keep it unticked at the moment
- Write debug log to SD card: this creates technical logs, mainly about the dialogs with the ELM device. It is basically for our debugging and optimization efforts.
