### ISSUE TITLE
Formal Disclaimer answers not fully visable on phone.

### ISSUE THREAD

**Issue by sordoneF** [fesch/CanZE#239]
![2015-11-29 11 44 12](https://cloud.githubusercontent.com/assets/16062794/11459279/62e7b220-96d3-11e5-9b64-df3f15466cd5.png)
When you do a fresh install, the disclaimer agreement button text for Yes is outside of the screen.
Expected result: "Do you agree" text with a "Yes" and "No" button only.

**Comment by fesch** [comment]
Did you try rotating your device?
