### ISSUE TITLE
Wrong power/100km

### ISSUE THREAD

**Issue by zmeglic** [fesch/CanZE#248]
Power consumption over 100km is wrong. It is always a large number... in thousands.

Version 1.06
Zoe
KONWNWEI OBDII http://www.ebay.co.uk/itm/151753972025

![screenshot_20151206-145140](https://cloud.githubusercontent.com/assets/16178106/11614261/83354eec-9c3d-11e5-84a9-233fbf06b8c9.png)

**Comment by yoh-there** [comment]
That was fixed earlier and released today. If you installed through Google Play you should have it updated by now. Please reopen if the issue is not solved after insuring you have a recent version (compile date in the settings screen stating today)
