### ISSUE TITLE
Charging screen

### ISSUE THREAD

**Issue by solmoller** [fesch/CanZE#260]
Available Charging power is listed as #ACP 

Mean battery temperature is extracted as -40

**Comment by jragg** [comment]
For me: It works ! right Power and temp data is shown.

Version CanZE: 1.08 
Car: Zoe
Dongle: MaxiScan 902
Smartphone: XIAOMI RedMi Note 4G
Android version: 4.4.4

**Comment by yoh-there** [comment]
jragg, I think your car is a Zoe right? solmoller is a FLuence ZE

**Comment by yoh-there** [comment]
@avataranedotas What frames do you use for AvailbleChargingPower (if you use that), meaning, what the external charger is willing to give (pilot signal on CP). I use 427.40 and that seems not to work for "FluKan". Same for men battery temp, I use 42e.44

If course I can make this Zoe/FluKan dependant, but I would need the proper frames.

**Comment by jragg** [comment]
yes right, a ZOE from 2013

**Comment by avataranedotas** [comment]
For the pilot signal charging power I get the Amperes from free frame 42E, bits 38 to 43.
427.40 is not available on my Fluence ZE.

Battery temperature is not available on free frames on my Fluence ZE.
I get it from the LBC requesting 0x022103, Byte 4 and Byte 5 (starting at Byte 0) of payload data with 0.1 C precision.

**Comment by yoh-there** [comment]
Fixed #269
