### ISSUE TITLE
Braking Power

### ISSUE THREAD

**Issue by solmoller** [fesch/CanZE#261]
I get "Timeout on [atma][]" in the Braking info, Firmware info and Driving info screens, all with various debug codes.

The screens appears to be working fine, so I gather it's a timing with my OBDII adapter. Graphical screens work a lot better, e.g. Consumption.

As a result I have updated the CanZE hardware page and listed the dongle as 'not recommended'

BR

Henrik

**Comment by yoh-there** [comment]
I just committed a somewhat more lax timeout model. Can you recheck please after pull & recompile? Thanks!
