### ISSUE TITLE
Formal Disclaimer answers not fully visable on phone for o.a. Safe Driving Mode setting.

### ISSUE THREAD

**Issue by sordoneF** [fesch/CanZE#262]
Expected result: "Yes" and "No" buttons.
Device is Motorola Moto-G, Android 5.1, Resolution = 720 x 1280 pixels.

![2015-12-13 19 39 41](https://cloud.githubusercontent.com/assets/16062794/11768877/89dbe70e-a1da-11e5-9b3d-eb3d6bfcba15.png)
![2015-12-13 19 39 21](https://cloud.githubusercontent.com/assets/16062794/11768875/89d9cbfe-a1da-11e5-863c-d5d0ed7efd72.png)
![2015-12-13 19 39 13](https://cloud.githubusercontent.com/assets/16062794/11768876/89dbae2e-a1da-11e5-9e8f-20bf7a577042.png)

![2015-12-13 19 50 34](https://cloud.githubusercontent.com/assets/16062794/11768904/4106ad42-a1db-11e5-84bc-e60dcfaa0c81.png)
![2015-12-13 19 50 22](https://cloud.githubusercontent.com/assets/16062794/11768905/410b077a-a1db-11e5-9182-14f3d25e7369.png)

**Comment by fesch** [comment]
Hui, if this is 720 x 1280 resolution, then my actual strategy is bad. Need to check to get the dpi settings. Actually my 7'' pad has the same resolution, me the entire display is much smaller ...

Found this: http://stackoverflow.com/questions/3166501/getting-the-screen-density-programmatically-in-android

**Comment by sordoneF** [comment]
https://play.google.com/store/apps/details?id=com.MTMDevelopers.ScreenSpecs, this app will say: 720 x 1184, DPI = 320 which is more or less correct.
http://www.whatismyscreenresolution.com/ will say 360 x 640 which is not correct. Strange so be carefull and select the right test.

**Comment by fesch** [comment]
I've tried to fix this by including the scaled density into my calculations. Hope it will work ...

**Comment by fesch** [comment]
If anyone would like to test, the intermediate version is here:

http://www.fisch.lu/junk/app-release.apk

**Comment by sordoneF** [comment]
Tested the 2015.12.22 version and the problem is not solved. Maybe a bit better but the text is not "full screen". Maybe change it to a "No" and "Yes" button ?

![2015-12-22 13 03 07](https://cloud.githubusercontent.com/assets/16062794/11964949/80cbc472-a8f1-11e5-8463-7b2df307ae0e.png)
![2015-12-22 13 02 36](https://cloud.githubusercontent.com/assets/16062794/11964950/80ed40f2-a8f1-11e5-8eb4-7c1694a7f904.png)

**Comment by yoh-there** [comment]
Sorry, but noticing a few spelling errors too.

Turn off your (of), but for clarity I would suggest "even if you power cycle your"
interfere (interfer)
applications (application)
also may (alsomay)
drain your battery (suck of your battery)

**Comment by fesch** [comment]
Actually I have a condition that put a simple "no" and "yes" on the buttons if the screen resolution is too not high enough to fit, but that does not seam to work.

I will implement some test-screen I will ask you to send me a screen capture so maybe that will help me get things ordered.

**Comment by yoh-there** [comment]
So, the emulation in Studio is crappy??? That is pretty bad!

**Comment by fesch** [comment]
I've uploaded a new version with a button "SCREEN TESTS" in the experimental section. Please post a screenshot of that one ... and hopefully I will get some good information to base my test on.

http://www.fisch.lu/junk/app-release.apk

@yoh-there : in the emulator everything works fine! @sordoneF's device has a resolution of 720 x 1280 (around the same as my Nexus 7) but everything seams to be scaled up :-/

**Comment by sordoneF** [comment]
Screentest done with as result:
![2015-12-22 21 59 41](https://cloud.githubusercontent.com/assets/16062794/11967021/e7e31468-a8ff-11e5-8e67-31fe63caab4e.png)

**Comment by yoh-there** [comment]
And for my S3

Opening screen
![screenshot_2015-12-22-23-03-48](https://cloud.githubusercontent.com/assets/4979670/11967104/9e9d1b54-a900-11e5-9d5b-26b04ef29e57.png)

test screen
![screenshot_2015-12-22-23-04-47](https://cloud.githubusercontent.com/assets/4979670/11967103/9494dc8c-a900-11e5-8947-4cb70fce16dd.png)

**Comment by fesch** [comment]
I notice you both have a density of 2. Mine has a density of 1, respectively of 1.33 on my 21' tablet.

I've modified my test:
http://www.fisch.lu/junk/app-release.apk

**Comment by sordoneF** [comment]
Display is now  correct. Text "Do you agree" should be added as last line, I think. Safe driving is stille off.

Greetz frank/sordonef.

Bob Fisch notifications@github.com schreef op 23 december 2015 10:58:17 CET:

> I notice you both have a density of 2. Mine has a density of 1,
> respectively of 1.33 on my 21' tablet.
> 
> I've modified my test:
> http://www.fisch.lu/junk/app-release.apk
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fesch/CanZE/issues/262#issuecomment-166851721

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yoh-there** [comment]
![screenshot_2015-12-23-11-37-35](https://cloud.githubusercontent.com/assets/4979670/11975036/01369ad8-a96a-11e5-806d-7ac8bf9dc275.png)
![screenshot_2015-12-23-11-37-56](https://cloud.githubusercontent.com/assets/4979670/11975037/01390e8a-a96a-11e5-853c-f84ec0931aa6.png)

**Comment by fesch** [comment]
OK, we need to shorten the text  of make it smaller ;-)

**Comment by yoh-there** [comment]
Why? I didn't try but it is scrollable isn't it? Nobody reads it anyway.

**Comment by fesch** [comment]
OK, so then this is fixed :-)
