### ISSUE TITLE
"Technical" and "Experimental" Screens interchanged ?

### ISSUE THREAD

**Issue by jragg** [fesch/CanZE#266]
Am i right that both screen are interchanged ?
Version CanZE: 1.08 
Car: Zoe
Dongle: MaxiScan 902
Smartphone: XIAOMI RedMi Note 4G
Android version: 4.4.4

**Comment by yoh-there** [comment]
ICK SIlly error. I will fix that.

**Comment by yoh-there** [comment]
Fixed and closed. #267
