### ISSUE TITLE
In battery screen no cell voltages are displayed

### ISSUE THREAD

**Issue by macfrank** [fesch/CanZE#271]
In battery screen no cell voltages are displayed. The chart in the left lower corner is empty. 
![screenshot_2015-12-17-09-07-19](https://cloud.githubusercontent.com/assets/756891/11873635/e8c590e0-a4db-11e5-8e0f-513143bf691f.png)

**Comment by fesch** [comment]
Hi,

what dongle do you use? What car do you drive?

**Comment by macfrank** [comment]
My dongle is a MaxiScan902 and the car is a Renault Zoe R210

**Comment by fesch** [comment]
Same as mine thus. Strange ...

@yoh-there : What do you think of this?

**Comment by yoh-there** [comment]
@fesch Actually, on mine too........ But the corresponding voltage heatmap works. So my guess, without looking at the code is: config error or some "overloading". Assuming it works on your tablet, could it have to do with the widget being "too small"?

**Comment by yoh-there** [comment]
Oh, I realize macfrank has a tablet. So it is NOT the size. Well, as I have the problem too and you @fesch do not (right??) I think I should investigate.

**Comment by fesch** [comment]
I will check this morning that screen. Haven't been in there for a while ...

**Comment by fesch** [comment]
I can confirm this: no data displayed! I will do a deeper analysis, as I did not touch that screen for some time.

**Comment by fesch** [comment]
Fixed
