### ISSUE TITLE
Error message in driving info

### ISSUE THREAD

**Issue by macfrank** [fesch/CanZE#272]
There is an error message shown in driving info screen.

![screenshot_2015-12-17-09-08-46](https://cloud.githubusercontent.com/assets/756891/11873688/3a9e0fc8-a4dc-11e5-86d4-07ec1dba9cb5.png)

**Comment by fesch** [comment]
That's a generic error that will be displayed in any screen when it occurs. This indicates a communication problem with the dongle.
