### ISSUE TITLE
OBDII BT Dongle test

### ISSUE THREAD

**Issue by solmoller** [fesch/CanZE#29]
We are going to have a lot of people testing this app with various dongles. Apart from a list of known good/bad dongles in the hardware section on the wordpress site, we could add a test to the setup menu. 

I suggest adding a button at the end of the BT setup: 'Test'. Pressing it makes the app issue
ATZ
- and display the result, in my case 'innocar'
  Then issue:
  ATSH 7E4
- and display both the result and an interpretation : 'OK 5 bytes read - that looks good'
  Then issue:
  ATFCSH 7E4
- again display the result and an interpretation : 'OK - two times OK, it appears you have a working adapter'

We might go as far as to do some speed testing, but that is outside what I can describe

Henrik

**Comment by fesch** [comment]
Good idea :-)

**Comment by yoh-there** [comment]
OK, I will take that challenge on.

**Comment by fesch** [comment]
The best place to do this is place a button in the Settings menu that is only visible/enabled if ELM327 is selected.

**Comment by yoh-there** [comment]
I agree

**Comment by yoh-there** [comment]
ELM test is now fully implemented in the Playground (Jeroen). Give it a spin, and I'll move it to the Setting screen later.

**Comment by yoh-there** [comment]
After some consideration I think we should leave ELM testing in experimental (or a third category, something like "technical" or "advanced", where also DTC should be moved once we're a bit more sure it works.

I am closing this issue.

Edit: most important reason for closing is that our straightforward advice is to buy a KW902. Not much need to test anyway, that one works.
