### ISSUE TITLE
Err atfcsh77b with ELM327 1.5

### ISSUE THREAD

**Issue by Nono1200** [fesch/CanZE#291]
Hello,
 I own a recently ELM327 1.5. It connects correctly Bluetooth, but it connects it displays this error err atfcsh77b.
 Do you have information for me?
 Thank you

Arnaud

**Comment by Nono1200** [comment]
Hello,
I own a recently ELM327 1.5. It connects correctly Bluetooth, but it connects it displays this error err atfcsh77b.
Do you have information for me?
Thank you

Arnaud

**Comment by yoh-there** [comment]
If that is incidental, please ignore (you can switch those messages off setting log level to none in the setting screen).

If it is NOT incidental but always, please state your device or include a picture. Thank you

**Comment by Nono1200** [comment]
It's always and this prevents the proper functioning of the case.
Here are photos:
![dsc_2131 1](https://cloud.githubusercontent.com/assets/16469195/12037654/472e7006-ae51-11e5-931a-151aef6ddef7.JPG)
![screenshot_2015-12-28-23-44-23 1](https://cloud.githubusercontent.com/assets/16469195/12037686/a3008112-ae51-11e5-9c9d-3dac3374b147.jpg)
Thank you

**Comment by yoh-there** [comment]
OK, well here is the problem. The fcsh command is absolutely needed for the operation in this EV, and obviously, the dongle does not support it. Other than the Konnwei KW902 and the Maxiscan we cannot help with other dongles. The one you have is totally no-brand in a generic case. In fact, I own EXACTLY one looking like this and it works fine. You just can't tell what is inside.

We have tried to explain this as clear as we could here http://canze.fisch.lu/elm327/ 

> The cheapest knock-offs do not work. Avoid the tiny ones in a transparent blue shell, as
> most contain stripped logic cramped in the spare room of their Bluetooth controller and
> these are too limited to work for CanZE.
> It is somewhat slow, though we’ve been able to get more out of it than we ever expected.
> If you experience problems with dongles other than the KW902, we are unable to help.
> The KW902 works, it is relatively cheap, and it is simply not worth, if not impossible, to
> cross check 50 unbranded, unversioned knock off dongles against 75 Android devices.

While I would really like to say differently, there is absolutely nothing we can do for you, other than advise you to buy a Konnwei or Maxiscan. They are available on eBay for under 15 euro's from China (it will take 2-3 weeks to arrive) and under 25 euro's from Europe (usually Germany)

**Comment by Nono1200** [comment]
OK thank you.
Can you give me a link to ebay dongle Konnwei KW902 I am sure not to be wrong please?
Thank you very much.
Arnaud

De : yoh-there [mailto:notifications@github.com] 
Envoyé : mardi 29 décembre 2015 18:11
À : fesch/CanZE CanZE@noreply.github.com
Cc : Nono1200 arnaud.caze@gmail.com
Objet : Re: [CanZE] Err atfcsh77b with ELM327 1.5 (#291)

OK, well here is the problem. The fcsh command is absolutely needed for the operation in this EV, and obviously, the dongle does not support it. Other than the Konnwei KW902 and the Maxiscan we cannot help with other dongles. The one you have is totally no-brand in a generic case. In fact, I own EXACTLY one looking like this and it works fine. You just can't tell what is inside.

We have tried to explain this as clear as we could here http://canze.fisch.lu/elm327/ 

The cheapest knock-offs do not work. Avoid the tiny ones in a transparent blue shell, as
most contain stripped logic cramped in the spare room of their Bluetooth controller and
these are too limited to work for CanZE.
It is somewhat slow, though we’ve been able to get more out of it than we ever expected.
If you experience problems with dongles other than the KW902, we are unable to help.
The KW902 works, it is relatively cheap, and it is simply not worth, if not impossible, to
cross check 50 unbranded, unversioned knock off dongles against 75 Android devices.

While I would really like to say differently, there is absolutely nothing we can do for you, other than advise you to buy a Konnwei or Maxiscan. They are available on eBay for under 15 euro's from China (it will take 2-3 weeks to arrive) and under 25 euro's from Europe (usually Germany)

**Comment by yoh-there** [comment]
You're welcome. There are three example links on the Hardware page of the CanZE website.

**Comment by Nono1200** [comment]
Thanks :-)
