### ISSUE TITLE
Compartment indication missing.

### ISSUE THREAD

**Issue by sordoneF** [fesch/CanZE#294]
Can you add the number of the compartment to this view ?
(which one is 15.0 ?)
![2015-12-29 22 45 53](https://cloud.githubusercontent.com/assets/16062794/12043601/e93f2d10-ae86-11e5-94c4-e8656e92da4d.png)

**Comment by yoh-there** [comment]
The numbering is left right, top to bottom, so the 15.0 cell is number 7. Same goes for the voltage heatmap.

Another question is: to what physical positions do these module and cell numbers correspond. The answer is: we don't know, and unless we find an insider who would be willing to tell us, we never will.
