### ISSUE TITLE
Communication stops

### ISSUE THREAD

**Issue by zmeglic** [fesch/CanZE#298]
Version 1.09 and previous
Zoe
KONWNWEI OBDII http://www.ebay.co.uk/itm/151753972025
Nexus 5, up to date.

After a random time (a few seconds up to a few minutes) any screen simply stops updating.
The green communication lights on OBD stops blinking.
After returning to main screen, and selecting another one, the communications start again.
There is no error or toast message displayed.

**Comment by tsknightstorm** [comment]
Same Problem here. ZOE and HTC One X+ with the Konwnei Dongle

**Comment by fesch** [comment]
Know problem of the dongle. Working to improve that since September 2015. 

Actually you have to live with that until a solution is found.  - Sorry -

**Comment by zmeglic** [comment]
Good to hear there is still hope :)
