### ISSUE TITLE
Widgets sometimes display a huge triangle

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#310]
No big issue. Graphs now and then display a filled area under a line going from left top to right bottom. It disappear after the next update, so it's usually a "flash". Hardware S3.

**Comment by fesch** [comment]
I can confirm this, but did not yet find the reason ...

**Comment by yoh-there** [comment]
Seems to happen when there is a "gap" in the recording. Not 100% sure

**Comment by fesch** [comment]
I did not get this since a long time anymore ...

**Comment by yoh-there** [comment]
Sorry my friend, I do.

**Comment by fesch** [comment]
Any improvements since my last commit?

**Comment by yoh-there** [comment]
Haven driven longer stretches with a running graph in a while. I will
update today and drive tomorrow.

On Wed, May 11, 2016 at 7:29 AM, Bob Fisch notifications@github.com wrote:

> Any improvements since my last commit?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fesch/CanZE/issues/310#issuecomment-218365502

## 

Please use Signal to reach me on secure IM and VoIP http://sgnl.link/1KpeYmF

**Comment by yoh-there** [comment]
I have seen one in my Thursday 40 km drive, but not down. Of course the flashes are very short and I didn't have my eyes on the phone all the time. Sorry. It's not a big deal (to me), but I think it's still there.

**Comment by yoh-there** [comment]
Today, for the first time, I saw the "triangle problem" in the lowest graph of the consumption screen, which has a slow update rate AND draws dots. I was too late to make a screen shot, but it was very obvious the erratic line was drawn from the one-but-last time stamp to the left-top point. I hope this helps a bit.

Seems like there is "simply" a (0,0) value inserted. If anything else fails, maybe such values in the array can simply be dismissed?

**Comment by fesch** [comment]
I did not get this since a long time. What about the other users?

**Comment by yoh-there** [comment]
I propose to close pre-emptively

**Comment by yoh-there** [comment]
It's still there. Not often and not a major issues. Just weird.

**Comment by yoh-there** [comment]
Update: the wrong line is one of (too fast to see) going from top-left to the most current value, or the one-but-most-current value is interpreted as top-left. Is a (crude) option to just ignore data points that end up left-top (I assume that is 0,0 in the canvas)?

Edit: ie insert on line 462 of Timeplot (for forward):
if (mx != 0.0 || my != 0.0) ({ ........ (closing } until after lasty = my

**Comment by yoh-there** [comment]
Sorry, didn't fix it. I might have read your update wrong. Seems like your only checking "last" and not the m values? Shouldn't the strategy be: "if the m values are wrong, don't do anything, not even updating the last values?"

**Comment by fesch** [comment]
Version 1.26 should now finally (and hopefully) fix this.
