### ISSUE TITLE
Battery screen improvements

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#333]
Based on suggestion on goingelectric and a long drive by myself yesterday......
- remove SOH graph;
- use real estate to display SOH numerically, and 12V voltage
- change RealSOC field to 7bb.6103.192 (this seems to better represent the bare battery SOC)
- replace battery temperatures with a (color only) heatmap? It's rather unreadable and unclear (to me at least) what the green lines mean.

What do you think?

**Comment by fesch** [comment]
Yes, let's see what it looks like ;-)

**Comment by fesch** [comment]
change RealSOC field to 7bb.6103.192: done

**Comment by yoh-there** [comment]
My suggestion is to close this item (even though I opened it). All values are available through the (tech) charging screen and the heatmap anyway.
