### ISSUE TITLE
Battery kilometers not correct

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#337]
CanZE v1.12
I checked the new value [Battery kilometers] on the Detailed Charging screen, and it showed 8565,0.
But my battery has never been replaced, so it should be 74101km. (I double checked with i907)

**Comment by fesch** [comment]
On my Zoé the value is the same than the one displayed on the car ....

**Comment by yoh-there** [comment]
Rollover on 16 bit number. Nothing we can do about that I am afraid. Maybe add in description

**Comment by HarmOtten** [comment]
We will find the most significant byte/word of this value somehow, because I know it is there.

**Comment by yoh-there** [comment]
Fixed in #339 I cannot test it as I haven't passed 65K kms yet. I will close this issue. Please test your personal pull/clone, or after the next release. Thanks!
