### ISSUE TITLE
Maybe # 329 should be reopened?

### ISSUE THREAD

**Issue by MAlfare** [fesch/CanZE#341]
Please read here for details:

https://www.goingelectric.de/forum/renault-zoe-zubehoer/obd2-diagnosegeraet-fuer-renault-zoe-erhaeltlich-t7818.html#p349939

The discussion between Jeroen and me, MAlfare, starting on Do 12. Mai 2016, 01:47 

Regards
Manfred

**Comment by yoh-there** [comment]
@fesch  : Version 12, voltage heatmap works. I thought scaling and all was fixed on 12? But I am running the development version of course, so maybe I have been too optimistic.

@MAlfare  please correct if I'm wrong).

**Comment by MAlfare** [comment]
Version 1.12 // Build: 2016.04.11 @ 07:56
Voltage heatmap works, scaling is fixed, but no data shown on Battery -> Cellvoltages (V)

**Comment by fesch** [comment]
Checking ....

**Comment by fesch** [comment]
I just tried multiple times, even with clearing all data, closing the app ... etc and I always get the cell voltages graph on the Battery page filled up nicely ...

**Comment by MAlfare** [comment]
Hi fesch!
Additinoal Information:
Android Version of my ZTE-phone: 4.2.2, on my Lenovo-tablet: 4.4.2
Not working on both, with downloaded from Playstore.
Could you pass me your (working) apk for testing?

Regards
Manfred

**Comment by fesch** [comment]
Voilà

[2016-05-22-canze.apk.zip](https://github.com/fesch/CanZE/files/276298/2016-05-22-canze.apk.zip)

**Comment by MAlfare** [comment]
Thank you!
Works on the tablet, and after some bluetooth problems, app- and system-crashes, on the phone too.
So there must be a difference between the playstore version, and the one. you sent me.

**Comment by fesch** [comment]
New version published ...
