### ISSUE TITLE
Cleanup of code

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#361]
- Improve setting of Bluetooth device when using http
- Allow leader definition for http (i.e. (http:\\192.168.1.21\wemos\")

As I personally see the ELM327Http option for developers only, the follwing I regard as optional
- Allow CanZE to start on an Android device without bluetooth adapter
- Display "connected" when DeviceInit over http returns "OK"

**Comment by fesch** [comment]
- [x] Improve setting of Bluetooth device when using http
- [x] Allow leader definition for http (i.e. (http:\192.168.1.21\wemos")
- [x] Allow CanZE to start on an Android device without bluetooth adapter
- [ ] Display "connected" when DeviceInit over http returns "OK"
- [x] Code clean of getString and getStringList (JM)
