### ISSUE TITLE
Request for multi-language

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#378]
Title says it all. User Twizyflu has offered to do the German translation, but of course we have not been very careful about separating out Strings as resources. This would be needed before any translation work makes sense.

Comments please if this is required / worth the effort.

**Comment by fesch** [comment]
- [x] Dutch
- [x] English
- [x] French
- [ ] German
- [ ] Luxembourgish ;-)

**Comment by yoh-there** [comment]
Working on it. Overall "delaminating" should be done today, and Dutch as ProofOfConcept. Please do NOT start, changes are massive overall and in progress

**Comment by fesch** [comment]
We will then need a new preference in the Settings too ...

**Comment by yoh-there** [comment]
Not really? Android resources follows system setting, any string taken from the language specific XML, if not found, fallback to default?

**Comment by fesch** [comment]
Hmmm ... but wouldn't it be nice to allow the user to switch to something else than the system default?

**Comment by yoh-there** [comment]
I will leave that to you ;-) In the mean time. Nearly all is "resourced out", including a Dutch language file. French and German versions I have send to volunteer native speakers.

**Comment by yoh-there** [comment]
Am I right when I say
- Luxembourgish was not really serous? ;-)
- That hard setting a locale is not really a requirement?
- That we can drop in languages as we get files and are not particularly waiting for language x?
If the answer to all the above is "Yes", I think we can close this issue.

I will add a post to the blog asking for volunteers to make language files.

**Comment by fesch** [comment]
3x Yes ---> closing ;)
