### ISSUE TITLE
test build 1.0.11.62

### ISSUE THREAD

**Issue by langloismichel** [fesch/CanZE#404]
Zoé R240 occasion de concession de mars 2016, achat en décembre 2016 avec 1500 km
test effectué à l'arrêt (après reset A et B), avec clé mais sans contact moteur

- l'app ne passe pas en "paysage" sur ipad mini
- taille de caractères des intitulés trop petite (au moins +2)
- quelle différence pour les tests avec/sans clé insérée et/ou moteur allumé.?
- ajouter un décompteur pour patienter sur l'écran de démarrage;
- pas trouvé de bouton pour envoyer sur sa propre messagerie personnelle une récapitulation des stats les plus importantes (ajouter l'email perso dans les config)
- mettre un repère quand la récup de données et l'analyse est faite (l'index du débug tourne en permanence (?), ou bien faut-il attendre pour revenir en arrière
- erreur pour la pression des pneus (capteur coché dans pref.)
- tension cellule :: on est un peu perdu, avoir peut-être des classes couleurs de tension plus tranchées; ou mieux faire un schéma-plan du positionnement des cellules avec leur id.
- faire un petit glossaire des variables affichées
- temp batterie :: ajouter les id des éléments
- charge donnees techn.: illisible, trop petit
- mettre la valeur d'autonomie avec une précision 1 (fenetre batterie, charge, donnes tech.), idem pour la puissance 
- test ELM : rien ne vient
- les versions de calculateurs ne s'affichent pas toutes (ou bien faut-il attendre plusieurs minutes.?)
- la pop fenêtre "fermeture de la socket wifi" reste ouverte sans nécessité (?)
- faut-il utiliser le bouton de déconnection.? l'icone reste grise
à+
Michel
4 copies écran
http://mlangloi.free.fr/CanZE/IMG_1206.PNG
http://mlangloi.free.fr/CanZE/IMG_1205.PNG
http://mlangloi.free.fr/CanZE/IMG_1204.PNG
http://mlangloi.free.fr/CanZE/IMG_1202.PNG

**Comment by yoh-there** [comment]
Thank you for your comments. Unfortunately, CanZE for iOS is build by a completely different team, not using GitHub at all. I will close your comment, but will forward your message as an email to the author of CanZE for iOS.

**Comment by FredLeudon** [comment]
Je m'en occupe. Merci pour le retour.

**Comment by FredLeudon** [comment]
>l'app ne passe pas en "paysage" sur ipad mini

_Cette fonctionnalité n'est pas encore développée. Priorité au fonctionnel pour l'instant_

>taille de caractères des intitulés trop petite (au moins +2)

_Idem question précédente, je travaillerai sur les écrans iPad une fois le fonctionnel terminé_

>quelle différence pour les tests avec/sans clé insérée et/ou moteur allumé.?

_Lors de l'arrêt du véhicule, après quelques minutes, les calculateurs passent en mode "sommeil".
CanZE envoie des commandes sur le bus CAN de la voiture afin de récupérer les informations de calculateurs.
Si la voiture est éteinte, il est impossible de communiquer avec les calculateurs car soit ils ne transmettent pas d'informations sur le bus CAN, soit ils ne répondent pas aux demandes d'interrogation.
Utiliser CanZE sur un véhicule éteint (sans clé insérée) ne donnera aucun résultat
Utiliser CanZE sur un véhicule avec clé insérée permettra d'interroger les calculateurs actifs.
Utiliser CanZE sur un véhicule avec moteur allumé devrait permettre d'interroger tous les calculateurs._

>ajouter un décompteur pour patienter sur l'écran de démarrage

_Lors du lancement de CanZE, certaines informations (le VIN, le kilométrage ainsi que le SOH de la batterie) sont transmises sur un serveur a des fins de statistiques uniquement. Si la connexion data du périphérique n'est pas disponible, la tentative de connexion peut prendre un peu de temps.
Je vais travailler à améliorer cet écran de démarrage._

>pas trouvé de bouton pour envoyer sur sa propre messagerie personnelle une récapitulation des stats les plus importantes (ajouter l'email perso dans les config)

_A l'heure actuelle, il n'est pas prévu d'envoyer les statistiques par mail.
Le bouton "Envoyer un commentaire" permet d'envoyer les logs au développeur.
Sur l'écran "Données techniques", dans l'activité "Lecture DTC", il est possible de récupérer les résultats de la lecture des DTC ainsi que le diagnostic des calculateurs par mail (icône en haut à droite de l'écran)_

>mettre un repère quand la récup de données et l'analyse est faite (l'index du débug tourne en permanence (?), ou bien faut-il attendre pour revenir en arrière

_Sur une "activité", les données sont lues en boucle à l'infini. Il est possible de revenir en arrière à tout moment._

>erreur pour la pression des pneus (capteur coché dans pref.)

_Si le capteur est coché dans les préférences et que la voiture n'est pas équipée de capteurs, il est normal que cela ne fonctionne pas.
Dans ce cas, il faut d"cocher le capteur dans les préférences. Une analyse en ligne droite, régulateur enclenché de la vitesse de rotation des roues est faite, mais le résultat n'est pas probant. Je dois affiner cette fonctionnalité._

>tension cellule :: on est un peu perdu, avoir peut-être des classes couleurs de tension plus tranchées; ou mieux faire un schéma-plan du positionnement des cellules avec leur id.

_Je me suis calé sur les affichages (tension.températures) tels qu'ils sont fait dans CanZE pour Androïd. Le but étant de faire une version iOS qui conserve la même philosophie._

>faire un petit glossaire des variables affichées

_Bonne remarque, quand j'aurai un peu de temps ;-)_

>temp batterie :: ajouter les id des éléments

_idem tensions_

>charge donnees techn.: illisible, trop petit

_Remarque prise en compte_

>mettre la valeur d'autonomie avec une précision 1 (fenetre batterie, charge, donnes tech.), idem pour la puissance

_Impossible, la donnée lue sur le bus CAN est un entier_

>test ELM : rien ne vient

_C'est à développer_

>les versions de calculateurs ne s'affichent pas toutes (ou bien faut-il attendre plusieurs minutes.?)

_Je vais refaire cette fonctionnalité dans le futur_

>la pop fenêtre "fermeture de la socket wifi" reste ouverte sans nécessité (?)

_C'est un bug qui sera corrigé dans les prochaines versions_

>faut-il utiliser le bouton de déconnection.? l'icone reste grise

_Il n'est pas grisé et il est préférable de l'utiliser_
