### ISSUE TITLE
V 1.20 crashes

### ISSUE THREAD

**Issue by MAlfare** [fesch/CanZE#407]
Hi!
Crashes after displaying "connected to..." and on KONNWEI KW902 BT is on, Host flashes, OBD off.
Lenovo A3500 F Tablet, Android 4.4.2 and Motorola Moto G4+, Android 6.0.1.
Both worked with previous version.

**Comment by fesch** [comment]
What locales do you have in your settings?

**Comment by yoh-there** [comment]
Damn, I thought there was always fallback to the default language? Is that just in the XML layouts??

**Comment by MAlfare** [comment]
@fesch: The language on my Android devices?
It is "Deutsch"

**Comment by fesch** [comment]
I've put my Android on "Deutsch" --> CanZE remains EN
If I chose "Français" --> CanZE becomes FR :-)

So no crash on my device!

**Comment by yoh-there** [comment]
Same here. Confused?

**Comment by fesch** [comment]
@MAlfare : What options do you have selected in the settings tab?
What happens if you switch you Android language to English?

I need to be able to reproduce the crash ...

**Comment by yoh-there** [comment]
Seems to fail only if SD card logging -> Fields is on, independant of Locale. That is my first analysis at least.

**Comment by fesch** [comment]
Indeed. That is reproducible. 

I've uploaded a fix. Can you confirm it works at your side too?

**Comment by yoh-there** [comment]
Pulling. Hold on........

**Comment by yoh-there** [comment]
Fix confirmed!

**Comment by MAlfare** [comment]
My settings, language set to English(UK)
![screenshot_2017-01-29-19-40-43](https://cloud.githubusercontent.com/assets/4406655/22406991/1f734140-e65e-11e6-8ee1-13a34984aca7.png)
![screenshot_2017-01-29-19-41-48](https://cloud.githubusercontent.com/assets/4406655/22406992/1f737052-e65e-11e6-9e1b-7e6099eb919c.png)

**Comment by fesch** [comment]
Version 1.21 with fix has been uploaded and is waiting for validation and dispatching in the store.
