### ISSUE TITLE
Back button missing in range and charging graphs screen.

### ISSUE THREAD

**Issue by sordoneF** [fesch/CanZE#408]
CANZE4iOS: 
![range_screen](https://cloud.githubusercontent.com/assets/16062794/22408148/01f62900-e674-11e6-873f-1db006acd2c7.PNG)
In the range screen the back button is a hamburger menu button.
When you click the hamburger button you go back so the function is there.
Same for Charging graphs screen. Please correct.

**Comment by FredLeudon** [comment]
Thanks for feed-back.
I will correct it for next release.
