### ISSUE TITLE
No cancel possible in "DTC readout" screen during retrieve.

### ISSUE THREAD

**Issue by sordoneF** [fesch/CanZE#409]
CANZE4iOS: When you click the Diag button with EVC selected, it will read 543 fields but there is no option to cancel this proces. And it takes a long time.

Expected result: the retrieve can be cancelled or otherwise a warning with a confirmation button that the proces wil take 5 minutes and can not be cancelled.

**Comment by FredLeudon** [comment]
Thanks for feed-back. 

I will add a "stop" button.

If You tap on the "return" button, reading ecu fields is stopped.
