### ISSUE TITLE
ELM performance on timeout

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#41]
I think the response timeout of sendAndWaitForAnswer should be made frame ID dependent, i.e. frame repeat time + 20ms for non ISO-TP frames, and 100ms for ISO-TP frames). It would improve performance further in the situation a timeout does occur.

In theory, it could also be used to control the query rate of different frames for the Due based devices, though there it competes with "skips".

IMHO a low priority, high impact enhancement, as it affects the spreadsheet, ELM, Field, Fields and possibly the Due devices.

**Comment by fesch** [comment]
Attribute "frequency" added to the spreadsheet and filled up with the information we got (using a VLOOKUP). Also added and filled that field to the X10 sheet.

Classes "Field", "Fields" and "ELM327" modified accordingly and tested in my car (no driving)
