### ISSUE TITLE
Use field "Range" in "Battery" screen for actual SoC %

### ISSUE THREAD

**Issue by GertjanVB** [fesch/CanZE#410]
Since "Range" is displayed quite  clearly  in the dash of ZOE, I suggest to use this space in the "Battery" screen for the exact SoC %. SoC is displayed in the graph on the "Battery" screen, but the exact figure at the moment is not easy to determine while driving. Displaying the exact SoC % in this data field will give a better understanding off the graphic and better impression on remaining range and duration of charging. I use CanZE for iOS.

**Comment by yoh-there** [comment]
I think you're referring to the iOS version right? As the Android version shows State of Health in numbers, State of Charge (Real and Usable) in a timed graph, Cell voltages as a line graph and  Battery temperatures ditto. Range is not stated. I am asking to ensure proper assignment and possibly ensuring what is shown is equal in both versions.

If possible, add a screen shot please. Thanks

**Comment by GertjanVB** [comment]
Yep iOS version:
![img_3158](https://cloud.githubusercontent.com/assets/18355712/22415274/20bd1270-e6c6-11e6-99a7-a09e1f4788a8.JPG)

**Comment by FredLeudon** [comment]
Do You prefer Soc or User Soc ?

**Comment by GertjanVB** [comment]
SoC, in connection to the SoC displayed in the dash, when charging is started. 
Hmm, what is user SoC exactly? SoH * SoC or % of the total real battery capacity, or something completely different?

**Comment by FredLeudon** [comment]
@CanZE Team, could You explain the difference between UserSoc and SoC please ?

**Comment by HarmOtten** [comment]
See [my comment about SoC versus User SoC](https://github.com/fesch/CanZE/issues/412#issuecomment-276454236)

**Comment by FredLeudon** [comment]
I will display User SOC in battery activity
