### ISSUE TITLE
Menu CHARGING (Android V1.21)

### ISSUE THREAD

**Issue by STEN-ZOE-FAN** [fesch/CanZE#414]
In subsection "Battery modules temperatures and balancing" are actually only the module Temperatures shown. Balancing info is allways "0".

**Comment by yoh-there** [comment]
Not for my car, at least not always :-) According to the documentation we have this is indeed balancing. It might be your battery is nicely balanced, or you have a different software version. Could you please go to the firmware menu, tap the LBC and attach a screen print here? I can try to figure that out with the 4 version information strings at the bottom of the screen. Also please indicate the model of the car (Q210, R240, Q90, R90).

**Comment by yoh-there** [comment]
Closing due to lack of feedback. Feel free to reopen.
