### ISSUE TITLE
Menu FIRMWARE (Android V1.21)

### ISSUE THREAD

**Issue by STEN-ZOE-FAN** [fesch/CanZE#415]
No version-infos are shown, only the items EVC / TCU ... are displayed.

**Comment by yoh-there** [comment]
Can you please add a screen print, indicate your car type? Thank you!

**Comment by Albino-Zoe** [comment]
I had the same problem ;-) The doing in V1.21 is now different. Select the item EVC / TCU, then the value appears.

----------------------------------------------------------------
Zoe R240 (08/2016) , CanZE (01/2017) , KW902 ELM327 (01/2017)

**Comment by yoh-there** [comment]
Thanks for confirming. I will test later. Some ECU's are a bit stubborn, and the BCB never gives up any data, but only the EVC or TCU, that is not right. Can you add please the type of car (Q210, R240, Q90, R90)?

**Comment by yoh-there** [comment]
I cannot reproduce this, sorry. Please ensure that the car is unlocked, card inserted (if not a keyless version) and "Started", as this awakens all ECU's.

When I do that I can query the firmware for nearly all ECU's.

I would appreciate if you can repeat the procedure with the above in mind, and report the results.

Please note that the BCB almost never answers, this is not bug.

Thanks.

**Comment by yoh-there** [comment]
Closing due to lack of feedback. Feel free to reopen.
