### ISSUE TITLE
Add Slovenian

### ISSUE THREAD

**Issue by zmeglic** [fesch/CanZE#418]
Here is my contribution. Translation to Slovenian language. (Slovenščina)
There might be a few typoos, but I will fix them if I find them. 
Also these three are not translated, because I have no idea what they mean.
<item>Blow req</item>
        <item>Cool cond req</item>
        <item>Heat cond req</item>
 
Hope you can include it soon.
Regards, Zdenko

[SL_strings.xml.zip](https://github.com/fesch/CanZE/files/742205/SL_strings.xml.zip)

**Comment by yoh-there** [comment]
That is very kind, thank you, we will surely include it in the next version!

- Blower requested
- Cooling requested
- Heating requested

But it's OK to leave it like that.

**Comment by yoh-there** [comment]
Added in the translation branch. Let's not forget to merge before the next release!

**Comment by zmeglic** [comment]
OK, than I will translate these together with any corrections/future translations at the next update.

**Comment by zmeglic** [comment]
How do I update the translations when new pages are added?

**Comment by yoh-there** [comment]
The easiest way is to pick up the file here 

https://github.com/fesch/CanZE/blob/master/app/src/main/res/values-sl/strings.xml

If I am not mistaken we have put in the new strings as English and if you could be so kind to simply change the few lines that are, we can easily merge that in. Thank you!

**Comment by zmeglic** [comment]
New file, merged with english variant:

[strings.zip](https://github.com/fesch/CanZE/files/803334/strings.zip)

**Comment by yoh-there** [comment]
Thank you! Will merge it in.
