### ISSUE TITLE
Range incorrect on Battery-screen

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#419]
(iOS / ZOE R90)
At low SOC (below 4%) the Range suddenly spikes to 1023km. At higher SOC it was displayed correctly.
![img_0330](https://cloud.githubusercontent.com/assets/10838083/22479804/6cd7aa24-e7ef-11e6-90b7-0228aa07d5e3.jpg)

**Comment by fesch** [comment]
As far as I remember, "1023" is a special value indicating that no calculation was possible. The car would indicate "---" and so should do CanZE as well.

**Comment by FredLeudon** [comment]
Thanks for feedback.

In next release, Range will be replaced by User SOC.

All Range calculation have been checked.
Will display --- in text or will be assigned to -1 in graphics when value >= 1023

**Comment by yoh-there** [comment]
Correct. Almost all values supplied by the ECUs are given as unsigned integers (sometimes offset such as with temperatures) and most often the highest possible value formally means "not available". Very few numbers are represented as signed integers. This is indicated by the SIGNED bit in the options attribute of a FIELD.
