### ISSUE TITLE
Build date

### ISSUE THREAD

**Issue by solmoller** [fesch/CanZE#42]
Well are having people opening bugs with outdated builds.

I suggest we follow http://stackoverflow.com/questions/7607165/how-to-write-build-time-stamp-into-apk

And add a build date to the GUI under settings - this will allow normal people to communicate the version they are having issues with. It should also lead them to update the app before logging issues

The code appears simple:
  try{
     ApplicationInfo ai = getPackageManager().getApplicationInfo(getPackageName(), 0);
     ZipFile zf = new ZipFile(ai.sourceDir);
     ZipEntry ze = zf.getEntry("classes.dex");
     long time = ze.getTime();
     String s = SimpleDateFormat.getInstance().format(new java.util.Date(time));
     zf.close();
  }catch(Exception e){
  }

**Comment by fesch** [comment]
Nice idea. 
I've added that ...
![screenshot_2015-09-27-20-24-49](https://cloud.githubusercontent.com/assets/1027354/10124464/f90fe650-6555-11e5-9465-25e20bfbcf1c.png)

**Comment by solmoller** [comment]
36 minutes from suggestion to closure. What is this? apart from brilliant :-)

**Comment by yoh-there** [comment]
Hee!!!!
