### ISSUE TITLE
Climate - Place where internal temperature sensor is installed ?

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#422]
Is really an internal temperature sensor installed at the Zoe? Where ?

**Comment by yoh-there** [comment]
There is, but I am not 100% sure where. Somebody told me it is the little "thing" on top of the dashboard, in the middle, almost between the vents for the windshield, but I am not sure, it seems a strange place. Please ask your dealer next time you're there. So will I :-)
