### ISSUE TITLE
Differences in screen "Battery Modules Temperatures" V1.21 vs. V1.16?

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#426]
Several lines were displayed in V1.16. In V1.21 only one ???
![screenshot_2017-01-29-09-17-54](https://cloud.githubusercontent.com/assets/25500628/22556793/ac750c06-e968-11e6-9a72-33a34797a673.png)
![screenshot_2017-02-02-08-12-22](https://cloud.githubusercontent.com/assets/25500628/22556887/eead8c74-e968-11e6-9063-30294a293dea.png)

Why is there no time axis?

------------------

Zoe R240 (08/2016), CanZE (01/2017), KW902 ELM327 (01/2017)

**Comment by yoh-there** [comment]
It was a bug.

And the two bottom graphs are not time based. It's actual values from the 96 cell pairs / 12 modules.

Closing
