### ISSUE TITLE
Test ELM327 Dongle - Error in test suite

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#427]
FYI

![screenshot_2017-02-02-19-36-37](https://cloud.githubusercontent.com/assets/25500628/22566199/49a62646-e98b-11e6-9d28-eac9dcbfd0a6.png)
---------------------
Zoe R240 (08/2016), CanZE (01/2017), KW902 ELM327 (01/2017)

**Comment by yoh-there** [comment]
Confirmed. Thank you! 

Removed field from the Fields class, probably already a while ago. Will add back.

**Comment by yoh-there** [comment]
Closing. Fixed in branch "development".

**Comment by Albino-Zoe** [comment]
Please open it again, the problem is in V1.29 with my R240 still or again!

**Comment by yoh-there** [comment]
This is a stupid regression and fixed in the development branch. It should be pushed to the master branch (which represents releases soon). Reopening is not needed.
