### ISSUE TITLE
Clima loop mode not working?

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#431]
Not sure if this is correct as I don't have an iOS device, but I saw a few screen prints of the CLIMA screen. There was no indication on the Clima loop mode line. If this is nonsense, please just close.

**Comment by FredLeudon** [comment]
I will have a look ....

**Comment by FredLeudon** [comment]
I had a look at the clima loop mode and it seems thad it is always "heather pump" mode. 

I switched from a/c on and off, de-icing, auto / manual with no change in clima loop mode. 

When I charged, clima loop mode was "idle"

What action make clima loop mode change for people who think it's working well?

Can somebody send a data logging file ?

**Comment by yoh-there** [comment]
De-icing is not a choice. What you meant is de-misting. I think it is still
simply too cold for the AC mode to kick in (but maybe it is warmer where
you are).

What the field SHOULD indicate is how the coolant circuit is switched:
de-ice the main radiator, cool, or heat. My advise would be to leave it
like this until summer.

**Comment by FredLeudon** [comment]
Ok,

There is perhaps a problem with my clima,

This winter, radiator etc were covered of ice....



Frédéric RICHARD

**Comment by yoh-there** [comment]
There have been serious software updates t the climate computer. Maybe a
good idea to have that checked.

**Comment by FredLeudon** [comment]
I tested ClimaTech activity and I assume Clim loop mode is working fine.

Closing this issue.

Feel free to reopen with screen shots if necessary.
