### ISSUE TITLE
CanZe exits after setting up

### ISSUE THREAD

**Issue by paprmakr78** [fesch/CanZE#441]
Once I've called the settings, the app exits and I need to reinstall it. Android Version 1.21 and newer.  Updates do not bring any improvement. Before the update to 1.21 it still works. As soon as I save the settings, CanZE quits. Sony XPERIA Z1C, Samsung Galaxy Tab 2 10.1 WiFi and others.

**Comment by fesch** [comment]
Maybe you could try to install, then goto settings and check the "debug log". All tough the application quits, it should write something to the log. You could then post it here.

**Comment by paprmakr78** [comment]
[debug-2017-02-21 05-50-23.957.log.txt](https://github.com/fesch/CanZE/files/789505/debug-2017-02-21.05-50-23.957.log.txt)

**Comment by fesch** [comment]
Thanks to the log file, I was able to find the code which seams to produce some exception, but there are a few lines that could have an impact. I thus recompiled a new version which gives - hopefully - more about in that section. You can find it here and then, probably, do the same operation and post that log too:

http://canze.fisch.lu/uploads/2017-02-21-canze.apk

**Comment by paprmakr78** [comment]
The app I have installed and tried. Now, the app stops, but I can not connect to the adapter. Also the setting of the vehicle (with me R240) is not saved, remains with Q210.
[debug-2017-02-21 13-59-29.460.log.txt](https://github.com/fesch/CanZE/files/790170/debug-2017-02-21.13-59-29.460.log.txt)

**Comment by fesch** [comment]
... but the log contains the needed details about the error :-)

Could you try this version?

http://canze.fisch.lu/uploads/2017-02-21-canze-2.apk

**Comment by paprmakr78** [comment]
Now I have tried the last version and it all works well. Only the response times are slow, but this is probably due to the logging. Thanks a lot for your quick help.
[debug-2017-02-21 14-27-02.907.log.txt](https://github.com/fesch/CanZE/files/790229/debug-2017-02-21.14-27-02.907.log.txt)
