### ISSUE TITLE
Diag class not found in recent builds

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#442]
Tech > DTCs

On some instances (not sure what the common factor is), dynamic classes refuse to load.

Please note that not all ECU's have DIag classes but the EVC certainly has.

**Comment by yoh-there** [comment]
> I follow the instruction (inset keycard, gear to D ...), but this is not very clear. Must I do anything else?

Car switched on is usually the best. The other instructions are ONLY needed when you want to clear DTCs, not to query them.

**Comment by yoh-there** [comment]
@fesch can you help me with this one?

**Comment by fesch** [comment]
I'll check this later on, yes

**Comment by yoh-there** [comment]
I will close this because of lack of action. TBH I have not seen this recently (But haven't used DTC's a lot either)
