### ISSUE TITLE
Issue in braking gauges (type Kangoo)

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#45]
See screenshot. I am not sure it is a bug really, as the entire braking system is not yet understood very well.

Issue reported by "kaimaik" through PM

![screenshot_2015-09-28-07-22-39](https://cloud.githubusercontent.com/assets/4979670/10144381/9e86fc82-661d-11e5-9361-cc31f3b68c62.png)

**Comment by fesch** [comment]
No, this is no issue. This field only exists in a file which is loaded from the SD card upon the start of CanZE. If you don't have that file, you wont have that field to. I've added this for personal testing purposes ...
