### ISSUE TITLE
x-axis of charts going back and forth during logging

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#451]
CanZE Android version.
Title of this issue says it all.

**Comment by fesch** [comment]
What do you mean by "during logging"?

**Comment by HarmOtten** [comment]
I mean at the time new data is coming into the charts

**Comment by fesch** [comment]
Got it. Checking the code ...

**Comment by fesch** [comment]
Fixed in the next release.

There was a major "ms" vs "s" time mismatch. Don't know where it came from, but it is fixed now.
