### ISSUE TITLE
Charts: Color of description the same as color of line

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#452]
CanZE Android version.
Is it possible to make the color of the description of a line in the chart, the same as the line color?
This would make it much easier to read the charts.
This applies to the Climate screen, and Charging graphs screen.

**Comment by fesch** [comment]
Should be. The problem is, that actually the text is being written within a single line of code. I'll check this ...

**Comment by fesch** [comment]
... and is configured as a single line in the views config :(

**Comment by yoh-there** [comment]
Comma separated, like the SIDs? Or is that too complex to position nicely, as they become separate entities?

**Comment by fesch** [comment]
Must use that ... because the slash is no option --> km/h  :(

**Comment by fesch** [comment]
Fixed in dev branche
