### ISSUE TITLE
Charging graphs: Add SOC%

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#454]
I would really like to see the SOC% in the Charging graphs screen.
To create some space I would suggest to combine the lines [Available charge power], [Max battery charge] and [DC charging power] in one chart. These are all in kW. And then you could show the SOC% in the top chart (together with the Pilot Amp).
Please let me know what you think.

**Comment by fesch** [comment]
Olà ... simple to do, bu the languages need to be updated all as well then :-/

**Comment by yoh-there** [comment]
Closing. Lack of activity.
