### ISSUE TITLE
Screen Driving info (Android) - "Distance to destination" & "Dist. Available at dest." are not displayed?

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#456]
Hello,
I used the first time the screen "Fahren" (Driving info) yesterday.
Is it normal that despite a given destination in the navigation device the values "Entfernung zum Ziel
" (Distance to destination) & "Reichweite am Ziel" (Dist. Available at dest.) are not displayed?
![canze_fahrinformationen](https://cloud.githubusercontent.com/assets/25500628/23707788/f0c4c0d4-0413-11e7-9706-5fabb7fbcccd.jpg)

-------------------------------------------------------------------------------------------------------------------
Zoe Intens R240 (25.08.2016) 25.000km/Jahr CanZE (Android) (V1.22) mit KW902 ELM327 (27.01.2017)

**Comment by yoh-there** [comment]
CanZE cannot read the NAV. Tap the Distance to Destination line, enter the distance you expect to drive, tap OK (or double for a round trip) and CanZE will show you the remaining range in the battery n arrival. Anything above zero is OK ;-) Closing.
