### ISSUE TITLE
fonctionnalité rendement

### ISSUE THREAD

**Issue by langloismichel** [fesch/CanZE#458]
bonjour,
je souhaiterais pouvoir lire sur l'app une estimation du rendement de charge effectuée par le chargeur caméléon de la Zoé, notamment quand il est branché à domicile sur le cable flexichargeur
merci

**Comment by fesch** [comment]
Comme la voiture n'a pas d'information relatives à la consommation réelle, cette information n'est pas intégrable dans CanZE. Dans ce cas il faudra s'orienter vers une station openEVSE.

**Comment by fesch** [comment]
@Jeroen: The question is about displaying the efficiency of the charger inside CanZE, but I think this is not possible as the car does not know what is really being consumed.

**Comment by yoh-there** [comment]
We can dig up DC power (Charging screen) and AC power (BCB screen, I hope it works on your end), so we could display DC on the BC screen too, and/or a ratio between the two

**Comment by fesch** [comment]
But will that give the efficiency of the charger?

**Comment by yoh-there** [comment]
Well, isn't that by definition the efficiency of the charger? 10kW AC goes in, 8kW goes to the battery (assuming no serious consumers during charging)? Or am I misunderstanding the question?

**Comment by fesch** [comment]
@langloismichel : Est-ce que ce va avec l'anglais ou devrais traduire?

**Comment by langloismichel** [comment]
je préfère le français, mais bon je crois comprendre

><https://github.com/langloismichel>@langloismichel 
>: Est-ce que ce va avec l'anglais ou devrais 
>traduire?
>

**Comment by yoh-there** [comment]
I am not sure if the addition I proposed is answering the OP's question. That might have been unclear when I said "or am I misunderstanding the question".

If there is lack of feedback I will close this issue soon.

**Comment by yoh-there** [comment]
Closed for lack of feedback from the OP
