### ISSUE TITLE
iOS Translations

### ISSUE THREAD

**Issue by FredLeudon** [fesch/CanZE#459]
Hi all

I worked hard to add Android translations to iOS CanZE.

Could somebody translate specific translation attached below ?

Thanks a lot.

[translations.txt](https://github.com/fesch/CanZE/files/892122/translations.txt)

**Comment by FredLeudon** [comment]
It is also necessary to translate this screen

![canze_settings](https://cloud.githubusercontent.com/assets/12695496/24642940/f780d7f8-190a-11e7-952a-830877897675.png)

**Comment by yoh-there** [comment]
Dutch:
Language -> Taal
WiFi settings -> WiFi instellingen
Automatic conexion (watch out, english spelling error: connection) ->
automatisch verbinden
Car -> Auto
Tyres pressure sensors -> Bandenspanning sensoren
other (capital O) -> Overige instellingen
Miles mode -> Mijlen modus
Field loggin (Field logging) -> Veld logs
Safe driving mode -> Veilig rijden modus

**Comment by FredLeudon** [comment]
Thanks

**Comment by wolfijenne** [comment]
I tried myself on the german translations, and where not done yet, on the english.
Whenever I am not shure, I put in a comment: (not sure on this one) 

[translations_de.txt](https://github.com/fesch/CanZE/files/938899/translations_de.txt)

**And the settings screen:**
German:
Language -> Sprache
WiFi settings -> WiFi Einstellungen
Automatic conexion  ->
Automatisch verbinden
Car -> Auto
Tyres pressure sensors -> Reifendrucksensoren
other (capital O) -> Andere
Miles mode -> Meilen Modus
Field loggin (Field logging) -> Feld-logging
Safe driving mode -> Sicheres Fahren

hope it helps

**Comment by manuelrocha88** [comment]
I've translated to Portuguese (Portugal Version) only the cDevice messages. It seems the messages are the same for the cELM327

If some have missed please ask and I translate it for you.

[translations_pt.txt](https://github.com/fesch/CanZE/files/955450/translations_pt.txt)

And the settings screen:
Portuguese:
Language -> Idioma
WiFi settings -> Definições WiFi
Automatic conexion -> Ligação automática
Car -> Carro
Tyres pressure sensors -> Sensor de pressão dos pneus
other (capital O) -> Outros
Miles mode -> Modo Milhas
Field loggin (Field logging) -> Histórico
Safe driving mode -> Modo condução segura

**Comment by FredLeudon** [comment]
Thanks

**Comment by mrubioroy** [comment]
Spanish and Catalan translations.

I've also made some corrections to the English translation. Please note that in English, ponctuation marks are not separated form the text: "The following:" and not "The following :" or "Hell!" but not "Hell !". However, this separation is common in French.
[translations.txt](https://github.com/fesch/CanZE/files/1744074/translations.txt)

**Comment by yoh-there** [comment]
Can I close this issue @FredLeudon ?

**Comment by yoh-there** [comment]
Closed due to lack of activity
