### ISSUE TITLE
CanZE 2.0.0 submitted today

### ISSUE THREAD

**Issue by FredLeudon** [fesch/CanZE#461]
Great news, 

CanZE for ios version 2.0.0 was submitted late this morning. 

In this version, translations are quite ok.

CanZE will work with Bluetooth LE dongle (LELink dongle only) 
I tested the Bluetooth stuff today and I noticed that there are some enhancements do to to make it working fine.

**Comment by FrancescZOE** [comment]
Hello, is there a CAnZE 2.0 for AndroiD?

**Comment by fesch** [comment]
iOS an Android version numbers are not related!!!
