### ISSUE TITLE
Km on "Charging extense" does not refresh soon

### ISSUE THREAD

**Issue by FrancescZOE** [fesch/CanZE#463]
Hello , i have some screen captures in a ZOE from 2013, where the km showed at are not refreshed with the real ones. Could i upload some images to take an idea?

https://www.dropbox.com/sh/2de3eg3e8x61n9s/AAA-5LjrECj7uuHn8UjsxMqQa?dl=0

**Comment by FrancescZOE** [comment]
I dont know when exactly changes and updates, now 2 hours later. After closing doors of car and putting it on charging. Has updated km to COrrect lecture. I have CanZE 1.24 lastest for Android.

**Comment by yoh-there** [comment]
This is as the car behaves. Car kilometers are only transferred to the battery computer once in a while. It has nothing to do with CanZE. Sorry for the late reply :-)
