### ISSUE TITLE
CanZe on iOS not working with R90/Q90 as selected model

### ISSUE THREAD

**Issue by BadgerinBlack** [fesch/CanZE#466]
I have a Z.E. 40 R90 but if I select this is the car in the iOS app I get the attached error message whenever I try and look at anything. If I set the type to R240 everything works fine.

http://www.dsg-renault.co.uk/uploads/images/canze.PNG

**Comment by FredLeudon** [comment]
Ok, i will have a look.

**Comment by yoh-there** [comment]
@FredLeudon can I close this issue?

**Comment by yoh-there** [comment]
Closing due to lack of follow up. I think this is being rolled up in issue #594 and the CanSee dongle ( https://gitlab.com/jeroenmeijer/cansee ) anyway
