### ISSUE TITLE
Wrong time on charts

### ISSUE THREAD

**Issue by stef44120** [fesch/CanZE#477]
Hello, I'm using CanZE for Android version 1.25 on Zoe R240 and I can see wrong time on charts.
Please see enclosed screenshot.
Thanks a lot for this app

Stef

![screenshot_2017-11-14-23-01-15](https://user-images.githubusercontent.com/33745992/32935841-2a04d43a-cb72-11e7-8b53-e434fe598fe6.png)

**Comment by yoh-there** [comment]
Confirmed.

**Comment by fesch** [comment]
Me too. I will fix that ...

**Comment by fesch** [comment]
fixed in dev branche
