### ISSUE TITLE
charge type not correct in charge history

### ISSUE THREAD

**Issue by nean-and-i** [fesch/CanZE#479]
In the charge history output can you please fix charge type accordingly, to be in line with to Renault specs?

Rapid/quick charge: 3 phases, 400V, 43kW, 80% in 30min
fast/accelerate charge: 3 phases, 400V, 22kW, 80% in 1h
everything below is a "standard charge" or "slow"

eg.:
Rapid 22kW - 50kW
fast  7kW - 22kW
Slow 0-7kW

In my case all charges stated as "slow" which is not correct.

this related to #478

**Comment by yoh-there** [comment]
No, as the car gives the same info in the history records. It's more an issue in the car firmware than it is in CanZE.
