### ISSUE TITLE
Number formats

### ISSUE THREAD

**Issue by solmoller** [fesch/CanZE#48]
The text based pages do not round displayed numbers - creating some screens that sometimes are just the speed and nothing else, as the speed may have 10 decimals

**Comment by yoh-there** [comment]
Agreed. Some numbers represent booleans (or trio-leans). Others, by virtue of their dividers (3 is a notorious one) can have a nasty number of decimals. Some are simply off (i.e. Torque) as the units are obviously incorrectly documented.

**Comment by yoh-there** [comment]
Partly fixed. In the braking screen, numericals are replaced with messages
