### ISSUE TITLE
Source Code iOS

### ISSUE THREAD

**Issue by beseder42** [fesch/CanZE#493]
Is the source code for iOS also available as open source? Or is that intended in the near future?

**Comment by FredLeudon** [comment]
CanZE for iOS is made with PCSoft’s WinDev Mobile app. 

I can share source code but it’s not easy as github’s repository.

Frédéric RICHARD

**Comment by beseder42** [comment]
If you can share I would appreciate.

**Comment by yoh-there** [comment]
Does Windev still uses it's own Source Code Manager?

But even without git integration, if the source is text files (like C-code, XML resources, etc etc) I would highly recommend creating a git repository.

Anyway, if there is not a shared location of the source maintained or planned, I respectfully propose to close this issue.

**Comment by yoh-there** [comment]
With some sadness, closed due to lack of activity.

**Comment by FredLeudon** [comment]
Windev uses it’s own editor. 

Source code is not text file, so creating git repository is not easy.

Frédéric RICHARD
