### ISSUE TITLE
String sorting in the battery health table

### ISSUE THREAD

**Issue by landswellsong** [fesch/CanZE#494]
Hi,
I'm not sure I have to report it here or elsewhere, but I noticed that the tables in battery health survey use string sorting. This makes sorting by the battery health unusable. I realize those fields also have text to them, but maybe there is a way to sort them numerically based on the first word / number sequence up to non-number etc.

**Comment by yoh-there** [comment]
Sorry for not responding. This seems to be an issue with the table handler in Wordpress (or we should enter all data with leading zeros).

I am closing this issue but not without suggesting to @fesch to ditch the surveys? Is anyone doing something with the data?

**Comment by fesch** [comment]
I will take a look at it, but the table contains strings, and this cannot be changed right out-of-the-box.
