### ISSUE TITLE
iOS App Crashes after 1 or 2 Minutes

### ISSUE THREAD

**Issue by wolfijenne** [fesch/CanZE#496]
Connection Via BT LE
App Crashes reliably after 1-2 Minutes
Log settings: info
When applying additional "Memory" in the log settings, App seams to be stable.

**Comment by FredLeudon** [comment]
Yes, this is a known issue. 

Using BTLE devices causes memory leaks and app crash due to huge memory usage. 

Verry hard to debug ;-)

**Comment by wolfijenne** [comment]
Sorry to bother here again... 
Since it seams to be stable when memory logging is on, why not simply have memory logging always be on when using BTLE?
