### ISSUE TITLE
When starting first time, selected BTLE Adapter is not shown

### ISSUE THREAD

**Issue by wolfijenne** [fesch/CanZE#497]
First time use:
Selecting BTLE
Testing of BTLE takes place
After testing Adapter is not shown in the screen (still none)
However, connection is possible.
After closing the app, Adapter is listed.

![image](https://user-images.githubusercontent.com/549286/39202711-05cdfab2-47f3-11e8-8ea6-a4e6d265ff56.png)
![image](https://user-images.githubusercontent.com/549286/39202722-109960a8-47f3-11e8-9117-6d67a829748a.png)
![image](https://user-images.githubusercontent.com/549286/39202729-1531d7d0-47f3-11e8-834d-d6396ad2c324.png)

**Comment by FredLeudon** [comment]
Thanks for feedback.

**Comment by yoh-there** [comment]
Is this issue closed?

**Comment by yoh-there** [comment]
Closed due to lack of activity
