### ISSUE TITLE
Typo  State of Hearth

### ISSUE THREAD

**Issue by wolfijenne** [fesch/CanZE#498]
Although I kind of like it, it probably should read "State of health" :)
![image](https://user-images.githubusercontent.com/549286/39202795-488fc344-47f3-11e8-95ac-56f3558e568f.png)

**Comment by FredLeudon** [comment]
Thanks for feedback.

There is a problem with DC power display too.

**Comment by yoh-there** [comment]
@FredLeudon I assume this is long fixed, so closing. Feel free to reopen if not.
