### ISSUE TITLE
2015.09.27 build: Not connecting and crash on opening settings

### ISSUE THREAD

**Issue by ahetlelid** [fesch/CanZE#50]
The latest build does not work on my LG Optimus 2X stock rom. There is no connection established and when I enter settings the app crashes.

Running the 2015.09.20 build, settings and connection works. The Leafspy page crashes in this version, but the charging page works just fine.

**Comment by yoh-there** [comment]
@ahetlelid   What Android please?

Team: maybe this is a duplicate of #38 (the part that @fuglemat reported) and it is unrelated to CM??

**Comment by ahetlelid** [comment]
Sorry. Forgot to check that information. It is Android 4.X, but I am unsure about the exact version as this phone has not been updated by LG for a loong time. (I am currently only using it for occational android necessities). It was updated last time when LG released the 4.X stock rom.

I will check when I have it available again.

**Comment by Fuglemat** [comment]
Sounds like the same problem, anyway, I did this

```
                // stop the BT device
                if(device!=null) {
                    device.setConnectedBluetoothThread(null);
                    BluetoothManager.getInstance().disconnect();
                }
```

and went out and tested it, and it works. LeafSpy also works.

**Comment by yoh-there** [comment]
@Fuglemat Did you make a fork? Are you pushing your changes to it and can Bob merge those? If needed I will paste here a simpe (and not very state of the the art) step by step on how to collaborate on github with Android Studio.

**Comment by fesch** [comment]
Added manually that if ;-)

**Comment by Fuglemat** [comment]
I just cloned it to take a quick look, and I had to disable all Git stuff to make Android Studio run on my old laptop. I would suggest you just fix it yourself for now :)
