### ISSUE TITLE
Battery Available Energy not working on Kangoo ZE (2013)

### ISSUE THREAD

**Issue by jvalik** [fesch/CanZE#500]
Hello,

first of all I would express many thanks that you developed CanZE tool. It helped me to check the battery health and cell voltages at the time I was purchasing my Kangoo.

My Kangoo ZE was produced 5/2013 and I'm having trouble reading Available energy of the battery and few more related parameters. It looks like some datastream isn't available or so.

I tried with ingition both on and off, having the car charging plugged and not, but it still doesn't work.

Sometimes I receive timeout on [atm] messages, sometimes not. I was receiving it also on cell voltages chart, but turning off the Safe Driving Mode solved that issue - not sure why.

Attached are the settings screenshot of CanZE and the extended Charging screen. I'm using Konnwei KW902 bluetooth dongle.

I'm aware that developers have Zoes only, so I can offer some help with Kangoo diagnosis, for example going through some raw data from OBD etc. But I'm new to OBD and not familiar with it, so some basic instructions may be needed.

Thank you

John
![screenshot_20180606-090336](https://user-images.githubusercontent.com/12666041/41022767-dc7a23ae-696a-11e8-9249-6dc9f10003da.jpeg)
![screenshot_20180606-091157](https://user-images.githubusercontent.com/12666041/41022776-e2c65b10-696a-11e8-863d-ee8a19187062.jpeg)

**Comment by jvalik** [comment]
Hello,

I also tried to run Fluence ZE Spy on my Kangoo and it was able to show much more data, see attached screenshot. Hope it helps.

John
![screenshot_20180607-182203](https://user-images.githubusercontent.com/12666041/41113557-47807398-6a82-11e8-81f0-f19de84ba9ee.jpeg)

**Comment by fesch** [comment]
I can conclude, that the Fluence PID's are closer to the Kangoo as the Zoe's are ;)

**Comment by yoh-there** [comment]
I am with @fesch on this one. AFAIK a Fluence ZE and a Kangoo ZE are technically the same.

**Comment by yoh-there** [comment]
@avataranedotas if you feel up to it, would you care to have a look at this? For the fields showing no or crazy data in the OP's second screen print, if you have the usual definition I (he) would be grateful. I can shove it in the definitions if I have it.

**Comment by avataranedotas** [comment]
I currently don't have time to look into it. I'm busy with the "new" 2017 LG battery PID's for the Fluence ZE.

**Comment by yoh-there** [comment]
Fair enough! Given lack of activity, I am closing this issue.
