### ISSUE TITLE
Miles instead of Kilometres?

### ISSUE THREAD

**Issue by g3wyw** [fesch/CanZE#505]
Is is possible to have a configuration parameter that changes all Kilometre readings ( Range, Distance to target, Speed etc) in Miles? 

My UK registered Zoe shows all in Miles and would like to have same units in the CanZE App if possible.

Paul

**Comment by yoh-there** [comment]
It's in the setting screen

**Comment by g3wyw** [comment]
Doh! RTFM if ever there was a time!
Missed that one
Many thanks

Paul

**Comment by g3wyw** [comment]
Many Thanks. RTFM!

 

Great product 

 

Paul
