### ISSUE TITLE
Cooperation with abetterrouteplanner to report data using CanZe

### ISSUE THREAD

**Issue by perkabolo** [fesch/CanZE#506]
Would it be possible to add logging to a website in order to provide data on charging and efficency to abetterrouteplanner in order to get better predictions for the Zoe?

**Comment by yoh-there** [comment]
See https://canze.fisch.lu/connected-services-thoughts/ please

**Comment by perkabolo** [comment]
Thanks! I forwarded that to the developers of abetterrouteplanner.
