### ISSUE TITLE
How about a charging graph with charge speed and SoC?

### ISSUE THREAD

**Issue by perkabolo** [fesch/CanZE#507]
How about a charging graph like this?

![image](https://user-images.githubusercontent.com/44729772/47954648-a4e9c780-df8c-11e8-86e0-6a1749eb7d88.png)

**Comment by perkabolo** [comment]
It can be used to better predict charging times for route planning.

**Comment by yoh-there** [comment]
Edit: we cross posted. See below. Basically I dispute it is good for planning. I think CanZE has better tools for that right now.

----- original answer --------

Thinking about what such a graph would bring. ZOE doesn't step-change it's power, but it's gradual. Then it seems a very indirect way of figuring out what is a good time to stop charging. The graphs we now have, though time based, and even more the charger predictor, are (in my opinion of course) far more insightful when trying to optimize your public charging planning.

Maybe I am overlooking another goal?

**Comment by Felger** [comment]
I'm one of the developers for [ABRP](https://abetterrouteplanner.com), which is what @perkabolo is looking for the data for (looking to add the Zoe to the planner).  We use the chart to analyze multiple routes, compare charging times and find a near-optimal route to minimize total trip time.  To add a model to the planner we need a set of data [(outlined in this blog post)](https://abetterrouteplanner.com/blog/index.php/2018/09/09/how-to-add-your-car-to-abrp/), one piece of which is the charge curve.  Many cars do have a smooth charge curve, and our planner is actually better equipped to handle smooth curves than stepwise functions.

We're also working on allowing you to follow a route we plan in real-time in the car.  Both of which need information from the car on its current stats.  Right now, we use Torque Pro for those cars that have known PIDs (Ampera-E/Bolt & Ioniq), LeafSpy (which is very limited at the moment), and Tesla's unofficial API. 

We're also investigating building our own app that requests the data from the car-specific apps via Intents or Events (Torque Pro supports this), so we don't have to store our users' data on our servers as a middle-man for real time data.  But the most common method that's supported right now is webserver logging so we're working with that right now.

**Comment by yoh-there** [comment]
Hi Felger,

I have a good mathematical model of the charging curve of the 22 kWh ZOEs. However, it is VERY dependent on battery (as opposed to ambient) temperature. I can give you the formula. Actually, it is embedded in the Java code on github, but I can extract it for you.

I also have a reasonable data set for the 41 kWh models, but have not have the time to turn them into a simple linear or quadratic function yet. However, also here (even more), the car is very sensitive to battery temperature.

If the curve is what you need, no data logging is required, done it all. But if you can't account for temperature, well, my stance is it's effort in vain (for the ZOE) if you take a "mean" temperature, but that's me.

**Comment by Felger** [comment]
We can and do account for external temperature in energy consumption on the road.  Not battery temperature currently, our assumption is that your car has a BTCS and keeps the battery at a reasonable temperature so as to not degrade charging, though that will likely have to change, as even Teslas see slow charging at low temperatures for the first charge of the day before the battery warms up. 

Does the Zoe have thermal management of the battery? 

Also, if you have a data-driven speed/power (or speed/range) curve, that would greatly simplify making the driving model.  I was going to build an analytical one based on the technical specifications available online, but my preference is to use a data-driven model based on real-world driving.

**Comment by yoh-there** [comment]
ZOE has active battery cooling using the car's A/C system. The 41 kWh also have a (tiny) battery heater that in my opinion is irrelevant for all but the most extreme situations. What can a few hundred watt do with 200 kg of stone cold mass, he asked rhetorically ;-)

"Problem" I see with your approach is that battery temperature after a stiff drive can easily be more than 10C higher than ambient, and then fast charging adds to that. ZOE actually likes all of that when ambient is moderate (say 12-15C for arguments sake) and the charge curve between 13C and 25C is massively different. Just saying, I don't have a solution, though I think if optimal route planning is the goal, battery warming should be included.

I do not have a speed-range curve, but that would be very easy to get at. Though things like weather (rain, wind) can throw a spanner in that too. Are you looking for averages?

**Comment by Felger** [comment]
How very strange! Given the typical climates that the Zoe is driving, I would have thought they'd give it a better heater.  Unfortunately, we may just have to include a disclaimer that we assume you've reached a steady state, and you may see reduced charging performance in cold weather.

Is it a different shaped charging curve, or just the same curve but lower?  If it's the second one, we could estimate.  Thing is, we don't want to introduce more special-case handling than we have to.  Eventually one of my goals is to devise custom functions for charge time and drive consumption adjustments based on external temperatures, but for the moment all the cars in the planner make similar assumptions about external conditions.

We account for weather with simple consumption adjustments, so we're looking for the median curve - the ideal-weather range vs speed.  The planner model actually uses a power-vs-speed curve (kW vs km/h), but if I know the usable battery size, then calculating power-vs-speed from range-vs-speed is easy.

On the previous subject, we just released our initial version of [live-OBD plan following](https://abetterrouteplanner.com/blog/index.php/2018/11/04/a-better-routeplanner-3-3/) using the webserver logging method I mentioned before.  If you're intersted in including the Zoe on that, I'd be happy to help figure out what's needed to connect the Zoe!

**Comment by yoh-there** [comment]
ZOE's battery (at least my 22 kWh) "auto heats" neatly when you step on it. Driving 120 km/h it's about 1C per 5 minutes. And anyway, a cold battery is no problem at all for driving. It is for (fast) charging, but then again, who charges BEFORE a long drive? Then fast charging after say an hour driving gives enough oomph to allow rather high power levels while charging, doing some more heating from within.  To be honest, I think they made a fair assessment, but that's me.

But I also think that using an average temperature is deceptively inaccurate. To get a feeling, have a peek at this sheet, representing the model:

https://docs.google.com/spreadsheets/d/1zDhdxQWK0W7SLOC40KOZc_lyTW6vkk5KnUB6xARV55I/edit?usp=sharing

Knowing the difference between ambient and battery will probably illustrate what I am trying to say.

Other than 1st gen Leaf, 22 kWh ZOE actually likes heat (but dislikes cold more than the Leaf). 40C for the battery is no problem. Sweet spot for the 41 kWh seems to be on 25C. Slightly different chemistry.

The Renault WEB API provides SOC and what we affectionately call the GOM (Guess-O-Meter), the range estimate. If that is enough for you, I would strongly suggest to go that route. Unfortunately, your users need to present their App credentials........ 

See this short post of mine with a link to the guy who did the hard reverse engineering work

https://plus.google.com/u/0/103762327575413926840/posts/Lr2LqWFZE7C

**Comment by Felger** [comment]
That's some really solid data! I definitely understand what you mean by internal compartment temperature.  I can't think of a way to reliably pre-plan a route guessing what the battery temperature will reach at a steady state.  Obviously the first leg of the trip the battery will be at equilibrium with the external temperature.  After that leg, however, it'll have equalized to a new (higher) temperature based on the power being pulled from the battery.

I also think it's not highly impactful if we don't account for this, since the error will occur in the same direction for all chargers we might select since it's dependent on the car's temperature, not on the station's capabilities.  So when it comes to optimizing the route, we will still select the optimal route for you to take, and it will still be driveable, but we would just tell you that you will charge for more or less time than you'll actually charge.

Realistically, we could adjust these numbers using live data from the car when executing a route, though we currently don't have a method for doing this in place so it would require special-case coding for the Zoe.

On the API, that's similar to how we get Tesla data, thanks for the link! I'll have to take a look at that. Only problem is, it's hard to implement for me, since I don't have a Zoe myself to provide the expected response.

**Comment by yoh-there** [comment]
If you have a method of me sending you a non public message, I can give you temp access to mine if that helps. I have no additional services, so it's all read only anyway.

**Comment by Felger** [comment]
Sure, if you send me an email at jason@abetterrouteplanner.com we can set up some other means of communication.  Perhaps WhatsApp, as it's purportedly encrpyted?

**Comment by yoh-there** [comment]
@Felger @perkabolo If I am not mistaken I have provided one of you with sample data for the 41 kWh battery models. Have you eve come around in converting that to a mathematical model?

**Comment by Felger** [comment]
I'm not sure I ever received it, could you send it my way again?

**Comment by yoh-there** [comment]
There you go

https://docs.google.com/spreadsheets/d/1YZeojRXoo7ui-hIWYc5Ov6IvCIlv7CpvJtR8pLDvIoI/edit?usp=sharing

(sorry, I must have missed the email coming from your reply, so a bit late)

**Comment by yoh-there** [comment]
We have now a somewhat better, first order (linear) formula for the ZE40 battery.

https://github.com/fesch/CanZE/blob/Development/app/src/main/java/lu/fisch/canze/actors/Battery.java

which will make it to the master probably today.

Closing
