### ISSUE TITLE
Reprogramming TPMS

### ISSUE THREAD

**Issue by bjaolsen** [fesch/CanZE#508]
I saw this in the closed #175 and would like to inform that:

This is possible to do using ddt4all and ELM327, it does however require you to have the ids for both sets of tires. The ids can also be read out from the unit using the same software, so once you have had the workshop do this once you can basically do it yourself afterwards.

In ddt4all the TPMS information is found in the UBIC/BFR section.
I used the screen TPMS_learning_ID_Pressure which allowed me to read and write all 4 ids at once

**Comment by yoh-there** [comment]
Thank you for that info. Slightly more answered in #175 Closing this one and reopening 175.
