### ISSUE TITLE
Support for ZoeR110

### ISSUE THREAD

**Issue by minibiti** [fesch/CanZE#509]
Hi,
Since I upgraded my Zoé R240 to a R110, I noticed that CanZE is not fully compatible with it.
Since there are no R110 choice in the settings, I am using R90 but it does not seem to be enough.

Are you aware of the problem?
If not, I can report the things that are not working properly. Not everything is broken :)

**Comment by yoh-there** [comment]
We don't have an R110 to our disposal, but we believe it is "just" a slightly modified R90. The problem with the 90 (and 110) models seems to be dongle overload. There is almost nothing we can do about that, other than making out own dongles. See the blog https://canze.fisch.lu

**Comment by yoh-there** [comment]
Please continue at #473

**Comment by minibiti** [comment]
I found out after having created this issue that the correct values do indeed come up in the app but it takes a while.
At the beginning, you get crazy values for battery pack temperatures and other things, but it settles after a while indeed.
Sorry :)

**Comment by StephanHi** [comment]
Just did my first charging session with my R110 and noted all the issues already described here. I watched crazy values in the heatmaps for more than an hour without them turning to something useful.
Max Battery recharge is shown as 0.0. Real SOC is shown as 0.0.

**Comment by yoh-there** [comment]
This issue is closed. Please continue at #473
