### ISSUE TITLE
Add "Safe Driving Mode"

### ISSUE THREAD

**Issue by fesch** [fesch/CanZE#51]
Suggestion from Alexander: My suggestion would be to have a Setting in the App called "Safe Driving Mode" that would be enabled by default and prevents button operation when moving.The user can disable "Safe Driving Mode", after getting a big disclaimer.

**Comment by fesch** [comment]
Done

**Comment by yoh-there** [comment]
Settings not possible while unconnected (states I am driving)

**Comment by fesch** [comment]
Initial state was wrong :(
