### ISSUE TITLE
Distance per kWh readout in driving and consumption screens

### ISSUE THREAD

**Issue by LakesGeek** [fesch/CanZE#512]
It'd be nice to have the option to show mpkwh (or kmpkwh, presumably, for Europeans) on the driving and consumption screens, rather than kwk per 100.

**Comment by yoh-there** [comment]
Thinking out loud. For the simple number screens it should not be a big deal to implement. but it would be quite "interesting" for the graphs.

1) We'd need two separate layouts for ie the consumption screen (most elements can be changed programmatically, but I am not so sure about the widgets. @fesch ?)

2) The more fundamental problem is one of showing regeneration. Right now it's quite natural, low value slides to 0 to a little bit of regeneration. In the m/kwh you'd get more and more and more and then yank over to a large negative value.

This would affect the bars pretty hopelessly. It would be a bit silly I think to keep the appearance of the consumption bar exactly as it is now, so "worse" is the bar filling up to the right and turning red, but put decreasing numbers in the bar (which IMHO would be the only "mathematically AND optically correct" solution)

I am not too sure if/how to approach this in a friendly matter. Thoughts?

**Comment by fesch** [comment]
Sorry ... I must be too tired (still now in the morning) to get all this. What is "mpkwh" or "kmpkwh"??

**Comment by LakesGeek** [comment]
Miles per kilowatt-hour or kilometres per kilowatt-hour, as the car shows on the "averages" display

At least, in the UK it displays mpkwh - I'm not certain exactly what's used in regions where km are used

**Comment by yoh-there** [comment]
It's like Left Hand Driving basically. It's just how they do things in the UK, you know, island and stuff ;-) In continental Europe, things have gravitated towards kWh / 100 km (l/100 km for ICE). But it is a genuine issue for UK drivers I realize.

I have thought about this a bit more. I think the graphs should be unchanged, the numbers converted, and the bars unchanged but with converted numbers inside.

**Comment by yoh-there** [comment]
Feedback on that @LakesGeek ?

**Comment by LakesGeek** [comment]
Sounds reasonable enough to me!  It was only really the number I was following right now in any case

**Comment by yoh-there** [comment]
Changed in commit #8c8c851
