### ISSUE TITLE
Weird issue with consumption in miles mode

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#520]
Calculation is correct (31 kWh/100mi), scale (alt) is set 0-64, but the lines plots around 49. It's pretty weird. As the number is right, I am assigning it to you for the moment.

![image](https://user-images.githubusercontent.com/4979670/51851548-6615a480-2324-11e9-8603-b6a870429eb0.png)

**Comment by fesch** [comment]
I switched yesterday to mils and the consumption graph did not change at all. Maybe because of the dashboard version not tracking it ... units changed, values not. I have to dig deeper ...

**Comment by fesch** [comment]
I can confirm there is a problem, but I did not yet find where ...

**Comment by yoh-there** [comment]
Fixed #faed446
