### ISSUE TITLE
"Battery kilometers" and subtle rounding difference?

### ISSUE THREAD

**Issue by Matthew1471** [fesch/CanZE#523]
In the strings there is

`<string name="label_HKM">Battery kilometers</string>`

This is confusing if you have CanZE set to show miles. Can I please suggest "Battery Odometer"? or that the label alters to say "Battery Mileage" if "Miles" is set.

Also I think there might be a rounding error sometimes? My car sometimes (not always) reports 1 mile less than CanZE is reporting (surely the battery can't have done an extra mile than the car thinks?).. so I suspect there to be an extremely subtle rounding issue.

**Comment by Matthew1471** [comment]
Or maybe just "Battery Mileage" is appropriate for both units? https://www.quora.com/The-distance-on-a-cars-odometer-is-called-mileage-Is-there-an-equivalent-word-if-its-a-car-with-metric-units-km

**Comment by Matthew1471** [comment]
![screenshot_20190202-175539](https://user-images.githubusercontent.com/5273302/52170972-40d1cd80-274c-11e9-812c-6939c707cf93.png)


Car dash shows 10784 miles.

**Comment by fesch** [comment]
... or the car's rounding is wrong!

Remember that there is another proven case where the car's rounding is terribly wrong, name the case of the recovered energy, where the counter only increments if an entire kW/h is being measured. So if someone like me, driving only short distances, an recovering a max of 0.9kW/h per run, the total counter of recovered energy say's at 0!!!

**Comment by yoh-there** [comment]
1) we won't care about rounding
2) the battery odometer is transferred from the EVC to the LBC in intervals (I forgot what the trigger is). It's basically a useless number. Some people think it will identify a "new" battery, but AFAIK it isn't.
3) fully agree about the nomenclature. Will change.

**Comment by yoh-there** [comment]
Fixed commit 76fd909

**Comment by Matthew1471** [comment]
Fine by me about rounding, just wanted to make sure we knew about it and had a reason as to why it was deemed correct if it was correct. Thanks for changing the label :).
