### ISSUE TITLE
Screen Rotation Kills Bluetooth Connection

### ISSUE THREAD

**Issue by Matthew1471** [fesch/CanZE#524]
I've observed that when you rotate the screen CanZE will drop the bluetooth connection (bluetooth light goes off on dongle) and CanZE reports connection drop.

I believe this is due to the way that Android "activites" are resumed/redrawn and CanZE incorrectly thinking the application has been suspended and resumed.

This is on Android 9 and by tapping the manual rotate button.

Sounds like you already know about this although not been called out as a bug? : https://github.com/fesch/CanZE/issues/99#issuecomment-147230540

**Comment by yoh-there** [comment]
Indeed, including explanationon the why ;-) I will keep this open for a bit, see what @fesch  thinks. If it's more than 10 minutes work I say: tough! ;-)

**Comment by yoh-there** [comment]
I was wrong about the 10 minutes. A valid point but after discussing, we won't fix this as it is / should not hampering the app except a bit of delay when rotating. Marking as such and closing.

**Comment by Matthew1471** [comment]
It seemed to cause quite a long delay on my phone and more than anything else it was how unexpected it was "oh the dongle has lost connection again... why? This connection is super un-reliable.. Oh hang on I wonder if it's something to do with I just turned my phone on its side?" gives an incorrect impression about the quality of my dongle/reliability of the app that is incorrect. Takes about a minute for my phone to recover.

Now I'm used to it, it's less of a problem but it's one of those "something that will catch out newbie CanZE users". If we don't plan to fix it a toast on-rotation "Bluetooth connection restarted due to screen rotation"?
