### ISSUE TITLE
"Max battery charge/regen kW" and "DC Power kW" Values Wrong Way Around?

### ISSUE THREAD

**Issue by Matthew1471** [fesch/CanZE#525]
Possible I've mis-understood the values but are they the wrong way around?

During this cold weather I'm doing a lot of battery PTC conditioning and I'm observing the Max battery charge/regen kW is often higher than the DC Power kW

![screenshot_20190202-212508](https://user-images.githubusercontent.com/5273302/52170926-54c8ff80-274b-11e9-8af5-9798f1139010.png)

If DC Power kW is the total in then surely the amount going to the battery specifically for charging should be less?

**Comment by Matthew1471** [comment]
Even happens when pressing the pre-condition button and the charge post is flashing to say that there's no charge instruction yet (car had gone into deep sleep and pressing the pre-condition button woke the car's AC up before the charger had finished negotiating with the EVSE)... you see -1.2kW coming from the DC power (should be the battery, no?) when it should be coming from the battery but 0.6 showing as "Max battery charge/regen kW" which should be the DC power (the EVSE gives a small residual current I am led to believe until the negotiation is performed).

![screenshot_20190202-185051](https://user-images.githubusercontent.com/5273302/52170934-9e194f00-274b-11e9-8eb5-43b37ec3d092.png)

Then once the charger had started supplying more energy the max power increased as I would expect the DC to have done. The DC had a smaller value to charge back up the charge I had just lost from pre-conditioning from battery while the car was still waking up and negotiating with the charger.

**Comment by mmangelsdorf** [comment]
Hi Matthew,

only an end user here, too.

But I think your values are completely valid.
**Max battery charge/regen kW** should be the maximum power, your battery _could_ currently be charged at (according to its current condition, i.e. SoC and temperature) - meaning that _actual_ charge power must be below this value.

Now **DC Power kW** should give you the _actual_ (DC-side) power that is put into or consumed from the battery. It must thus be lower than the maximum mentioned above.

Hope this helps :)
Marcus

**Comment by yoh-there** [comment]
Marcus explanation is spot on. I will add that Available is what the chargepoint, on combination with the cable indicator will be able to provide. Closing this issues as answered.

**Comment by Matthew1471** [comment]
I stand corrected and defer to your greater experience then :)
