### ISSUE TITLE
"error in the test suite, please report" (R90 Z.E.40)

### ISSUE THREAD

**Issue by Matthew1471** [fesch/CanZE#526]
As per title:

![screenshot_20190129-010321](https://user-images.githubusercontent.com/5273302/52171006-b2aa1700-274c-11e9-84c0-49157e51845b.png)

**Comment by yoh-there** [comment]
Thank you!

**Comment by yoh-there** [comment]
fixed in commit 093f0a1

**Comment by Matthew1471** [comment]
Sorry,

"Processing prepped free frame PARK BRAKE
Query send, but unexpected result received:
[8814000000000020]"

**Comment by yoh-there** [comment]
Hmpf! Thanks :-)

**Comment by Matthew1471** [comment]
Also, if I am allowed to be typo-petty again :-)

"query sen**t**" not "query sen**d**"?

**Comment by yoh-there** [comment]
#b0442f3
