### ISSUE TITLE
ELM Dump stops at Frame: 5d1

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#528]
I have never tried this "ELM Dump" before in previous versions, in the current V1.29 it stays with "Frame: 5d1"
![screenshot_20190207-154853_canze_v_1_29_elm_dump](https://user-images.githubusercontent.com/25500628/52421784-1047b600-2af5-11e9-90f9-4618e94b20ac.jpg)
"

**Comment by yoh-there** [comment]
The program would continue, but only after 60 seconds, which surely is the equivalent of a hang.

Fixed, but won't make today's release. Rollover to next release.

Closing
