### ISSUE TITLE
Enhancement : charge-to-percent

### ISSUE THREAD

**Issue by ldti** [fesch/CanZE#533]
Idea : create an option (maybe a different app?) to monitor SOC, and send a stop charge command over obd when reaching desired percent.

**Comment by yoh-there** [comment]
Unfortuately, there is no such commands we can send to the car. To implement this, a batter route would be to use the data from the dongle as input for a house automation system and control the chargepoint. Sorry, good idea, but can't do it.

**Comment by ldti** [comment]
Ah, I didn't know that there is no such command. bummer.
