### ISSUE TITLE
Twizy not selectable in settings dialog

### ISSUE THREAD

**Issue by gblueml** [fesch/CanZE#535]
Renault Twizy appears in the list of available cars.
Selecting it and accepting the settings and opening the setting dialog again results in ZoeQ210 being selected.
Selecting X10 accepting the settings and opening the dialog again results in Twizy being selected.

The bug is in SettingsActivity.java line 163:
Index is not set to the right value for Twizy and X10 selection.

**Comment by fesch** [comment]
Thanks for the push. I've just merged it. Will be in the upcoming release ... probably in the next few days ;)
