### ISSUE TITLE
Version 2015.09.20 works fine, newer versions don't

### ISSUE THREAD

**Issue by fivari** [fesch/CanZE#54]
I installed the version 2015.09.27 and 2015.10.01 on both my HTC One android 5.1.0 and a tablet android 4.4.2 . 
For both CanZe versions, the device displays "not connected"  although the the bluetooth connects. 
When pushing the key for settings, version 2015.09.27 crashes whereas the version 2015.10.01 displays: not allowed while driving. Not possible to enter the settings menu.
No way to make those versions work.
Version 2015.09.20 however, is working fine, except for the leafspy, then CanZe also crashes.
Any ideas how to solve the problem?

**Comment by fesch** [comment]
Problem already reported and solved. Please wait for the next published release ...
