### ISSUE TITLE
elm connection error

### ISSUE THREAD

**Issue by Rraets** [fesch/CanZE#574]
When I connect ELM327 ODB scanner I alway get following message :
ELM ready, version 2.x, will problably not work, please report it if does.
(in CANZE android on Samsung galaxy s10)

**Comment by yoh-there** [comment]
Great (as I assume it DOES work). What type of dongle is it? "elm327" is insanely generic and can mean anything. Link, or pic?

**Comment by Rraets** [comment]
Hello,

I is this one:
https://www.bol.com/nl/p/obd2-scanner-bluetooth-elm327-obdii-auto-computer-uitlezen-car-reader-diagnose-foutmeldingen/9200000088401970/?s2a=


There is not a lot of information on it..

greetings

René

Op ma 14 okt. 2019 om 23:42 schreef yoh-there <notifications@github.com>:

**Comment by yoh-there** [comment]
Thanks. I assume that despite the warning, it does work normally?

**Comment by Rraets** [comment]
No it doesnt work at all. After I give the pincode 1234 for the BT connection it gives that message. Then it looses the BT connection

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by yoh-there** [comment]
Ah, my bad. Well, sorry to say the only dongles we pledge to do our stinking best to run are the KONNWEI902 and CanSee. See https://canze.fisch.lu/elm327/ and https://gitlab.com/jeroenmeijer/cansee

**Comment by Rraets** [comment]
Is this a good one ?
https://www.amazon.de/Diagnoseger%C3%A4t-KONNWEI-Autoscanner-Unterst%C3%BCtzung-OBD2-Protokolle/dp/B077XGSV83/ref=sr_1_8?__mk_nl_NL=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=MaxiScan+Konnwei+902&qid=1571157970&sr=8-8



Op di 15 okt. 2019 om 18:26 schreef yoh-there <notifications@github.com>:

**Comment by fesch** [comment]
It might ...

**Comment by Rraets** [comment]
Do you sell them of do you have a link to a good one ??



Op di 15 okt. 2019 om 18:49 schreef Bob Fisch <notifications@github.com>:

**Comment by fesch** [comment]
We don't sell ELM's ... 
I've build some CanSee dongles, but the prize is of course not competitive as it is a custom build ...

**Comment by yoh-there** [comment]
....... but your link looks like a genuine 902, so it's about the best shot you have.
