### ISSUE TITLE
Clima RPM

### ISSUE THREAD

**Issue by gpezzarini** [fesch/CanZE#578]
I dont'understand the value, I can read only "5,0", it don't change when the Engine Fan Speed work
ZOE R240 2015

![Screenshot_20191030-090831](https://user-images.githubusercontent.com/57046041/68366323-53da5980-0133-11ea-93dc-1a7ae5df2a40.png)
Best regards

**Comment by yoh-there** [comment]
Engine fan speed should indicate the speed of the beefy radiator blower at the front, cooling (or heating) the big climate system radiator. I think in this picture you are charging and the heat pump is not working. Are you sure said fan was running? (it is pretty loud and easily detectable)

Edit: I misread your question. I think the unit is actually %. Let me double check that.

**Comment by yoh-there** [comment]
Yes, that was an error. The value is given as %. There is a release out just a few hours ago, so the fix is made, but it will have to wait until the next release in a couple of weeks. Thanks for reporting.
