### ISSUE TITLE
Wrong pilot Amp readout with ISOTP over Konnwei 802

### ISSUE THREAD

**Issue by mgerZOE** [fesch/CanZE#584]
On a 11kW 3-phase type-2 socket, I get a 1-phase 32A displayed on the detailes page. With ISOTP off, it's 15A, 3-phase, which is correct.
![with ISOTP](https://user-images.githubusercontent.com/57867429/69009119-beb93b00-0952-11ea-83f9-5c11f75cbf12.jpg)
![without ISOTP](https://user-images.githubusercontent.com/57867429/69009120-c082fe80-0952-11ea-959d-90e4cb4d119e.jpg)

**Comment by yoh-there** [comment]
Good catch, thanks. Fixed and closed.
