### ISSUE TITLE
Zoé R110

### ISSUE THREAD

**Issue by neuesfernsehen** [fesch/CanZE#595]
Which car should I select in the settings when I have a Zoé R110 and want to use CanZe iOS version?

**Comment by FredLeudon** [comment]
It is preferable to use the beta version of CanZE.

You can install beta version through Apple’s TestFlight app by following this link : https://testflight.apple.com/join/nhMX6f5n

Be sure to allow CanZE to use cellular network; so CanZE will be able to scan ECUs and download correct definitions form server.

**Comment by yoh-there** [comment]
If the question is answered sufficiently, please close the issue, thanks!

**Comment by FredLeudon** [comment]
I close this issue. 

Reopen if you can’t install beta version.

**Comment by neuesfernsehen** [comment]
Hello,
Thank you very much for the swift reply to my question.
I’ve already installed the beta version but didn’t test it until now.
Closing the issue is fine. I was off over the weekend so I didn’t react in the time you would have preferred.
Best regards
Mark

Von: FredLeudon <notifications@github.com>
Gesendet: Sonntag, 22. Dezember 2019 17:53
An: fesch/CanZE <CanZE@noreply.github.com>
Cc: Mark Polderman <mp@neuesfernsehen.de>; Author <author@noreply.github.com>
Betreff: Re: [fesch/CanZE] Zoé R110 (#595)


I close this issue.

Reopen if you can’t install beta version.
