### ISSUE TITLE
BobDue wrong device type: 'ELM327'

### ISSUE THREAD

**Issue by SMCinc** [fesch/CanZE#597]
Hello, I have a BobDue running (beside CANsee and Konwei). I use beta versions of CanZE.
Since a few weeks the devicetype seems to be hard coded. 
BobDue is reported as ELM 327 and can not be changed.

**Comment by yoh-there** [comment]
The solution is very simple.
1) name your device (using Androids Bluetooth settings) CANSee
2) Select the device in CanZE. It will automatically select CanSee as Device Type, which is the same as previously BobDue.

Please close the issue if this is the solution, thanks.

**Comment by SMCinc** [comment]
OK, thanks for the fast response.
