### ISSUE TITLE
TMPS change axle button possible?

### ISSUE THREAD

**Issue by SMCinc** [fesch/CanZE#598]
TMPS IDs reading and writing with CanZE is fine (I used ddt4all before).
The feature of storing zwo sets is great.
 - It would be perfect if  the TMPS IDs cold be changed axlewise: I and I think many users change the tires front to rear axle time to time (latest when they change from one season tire to an other) due to use the profile equal om all tires. LF -> LR and RF ->RR

**Comment by yoh-there** [comment]
Commit 20c3bf70

**Comment by SMCinc** [comment]
Tested on Zoe R210 using Android CanZE 1.51beta2 (2019-15-24 15:04:18) and CANsee HW:
Axle swapping button works fine.
Thanks a lot for the Christmas present.
