### ISSUE TITLE
Meaning of charge ending strings?

### ISSUE THREAD

**Issue by ldti** [fesch/CanZE#603]
Hi. Small question:

What is the meaning of each of the reasons of the charge ending, such as fault 22, fail and so on?

**Comment by yoh-there** [comment]
Fair question, but we only get a few numbers from the car and what we show is unfortunately all that we have from the documentation we got.

**Comment by ldti** [comment]
So the strings are mapped to numbers, but you don’t really know their meaning?

Sent from my iPad

On 31 Jan 2020, at 1:20, yoh-there <notifications@github.com> wrote:

﻿

Fair question, but we only get a few numbers from the car and what we show is unfortunately all that we have from the documentation we got.

**Comment by yoh-there** [comment]
Correct. Some numbers we have better descriptions and then we show. If it's just a number, we have not gotten better documentation.

**Comment by ldti** [comment]
Ok, I understand. Kind of a shame, though..

Sent from my iPad

On 31 Jan 2020, at 1:23, yoh-there <notifications@github.com> wrote:

﻿

Correct. Some numbers we have better descriptions and then we show. If it's just a number, we have not gotten better documentation.

**Comment by KarelSvo** [comment]
Take a screenshot, maybe I have an idea ;-)

**Comment by ldti** [comment]
You can find all of the strings here:

https://github.com/fesch/CanZE/blob/master/app/src/main/res/values/strings.xml

**Comment by KarelSvo** [comment]
There is no screenshot of your error 22 on this page ;-)

**Comment by ldti** [comment]
I know, because there's nothing to really show. All the strings are there in the link I attached.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
