### ISSUE TITLE
iOS Renault Zoe R110 compatibility

### ISSUE THREAD

**Issue by ladaca2** [fesch/CanZE#604]
Hi,
Apologies if this has been answered elsewhere...

Will the CanZE iOS app work to give me a battery health state reading for a Renault Zoe R110? I can see R90, Q90, R240 and Q210 in the model list, but not R110.

Can I use this app to get an R110 battery health state reading, and if so, which model do I need to select?

Many thanks

**Comment by yoh-there** [comment]
I am not sure for iOS but please try R90

**Comment by ladaca2** [comment]
Thanks – I will try that when I see the car.

Does anyone know whether it will make a difference, though, between choosing R90 and R110?

**Comment by yoh-there** [comment]
No. It's only a motor power rating difference.
