### ISSUE TITLE
Settings keep clearing.

### ISSUE THREAD

**Issue by KotekBesar** [fesch/CanZE#606]
Morning!

Seems like every morning I come to my car to find that CanZE doesn’t work and, when I open Settings, I find that it’s because they have cleared (back to safe driving mode).

Not sure why? If no one else is reporting this issue, perhaps it’s my phone? Using Samsung A80 (not rooted). 
![3D52E151-2369-4554-AD1C-8CA3AC0C7740](https://user-images.githubusercontent.com/42305037/74513946-93b79680-4f03-11ea-8184-d587a89d3e39.jpeg)
![69520E52-1DD2-4592-A6B9-9ED57E85D7B4](https://user-images.githubusercontent.com/42305037/74513950-95815a00-4f03-11ea-8b5c-b3617987d52e.jpeg)

**Comment by yoh-there** [comment]
I have no idea and never seen this. @fesch an idea? Is maybe the app transferred to SD (Inever tested this)

**Comment by yoh-there** [comment]
I hope issue went away. If not, feel free to reopen
