### ISSUE TITLE
Never see any DTCs on Ze40

### ISSUE THREAD

**Issue by fgmccrea** [fesch/CanZE#609]
Select a computer, click on query

Sending initialisation sequence

Sending start DTCs sequence:[59020f]
Get DTCs field does not exist

No active DTCs

Maybe someone could confirm it works ok?

Thanks

**Comment by yoh-there** [comment]
I am closing this issue, as it is the same as #617 617 (yes I know, you were earlier, sorry). Please follow that issue, I will try to solve it shortly.

**Comment by fgmccrea** [comment]
And I see you have been working on it thank you!
Gordon

Sent from Yahoo Mail on Android 
 
  On Thu, 27 Aug 2020 at 20:12, yoh-there<notifications@github.com> wrote:   


I am closing this issue, as it is the same as #617 617 (yes I know, you were earlier, sorry). Please follow that issue, I will try to solve it shortly.
