### ISSUE TITLE
CAN bus messages in DBC form?

### ISSUE THREAD

**Issue by MatinF** [fesch/CanZE#613]
Hi all,

I'm trying to do some data logging of a Renault Zoe. Are any of the converted messages for the Zoe here based on raw CAN bus messages? And if so, has anyone managed to add any of the CAN decoding rules to e.g. a DBC file?

Thanks, Martin

**Comment by KarelSvo** [comment]
The ddt4all Can sniffer works with a file that decodes the free frames. The file is called can_v10_02_20110126T152836.xml.

**Comment by MatinF** [comment]
Thanks @KarelSvo - I was not able to find this file in the repo, could you let me know where it is?
