### ISSUE TITLE
Can CanZE change configuration values?

### ISSUE THREAD

**Issue by brunoais** [fesch/CanZE#614]
The ZOE has many configurations which can be toggled and adjusted. Even renault (as I think many other manufacturers too) ICE cars have many configurations.
Can CanZE change those configurations too?
In my case:

1. Turn off creep (AKA set speed to 0)
2. Turn off regenerative breaking for accelerator pedal (keep it for the brake pedal).
3. Temporarely tune down AVAS volume for a fixed time (NOTE: the car has a button to turn it off). In my case, it does an awful lot of noise in the shared garage but I don't want it off so people know well I'm there.

BTW, I do know, at least, creep can be turned off easily because I've spotted got a mechanic turning it off on purpose to diagnose a behavior. He forgot it off for a while; unfortunately, it was turned back on when I took the car for the next mechanical review and they refused to turn if back off because corporate doesn't allow.

I don't mind if the settings change or adjustments are temporary and only active while the dongle is connected to the CANBus and go away as soon as it is disconnected.

**Comment by KarelSvo** [comment]
The search terms are: ecutweaker, ddt4all, pyren, pyclip, renolink

**Comment by yoh-there** [comment]
Except TPMS, we do not write any value, nor do we intent to.
