### ISSUE TITLE
Can ZE work with my BT adaptor?

### ISSUE THREAD

**Issue by AndyIreland** [fesch/CanZE#618]
Hello - here is a readout for my ELM327 OBD2 BT adaptor I have does the specs for it look OK? , will CAN ZE work with it  please? -  its a normal 22kw 2013 Zoe. 

Scan date=2020-08-13 17:18:50
Device name=OBDII
Device mac=86:DC:52:DD:F6:F1
Device Version (Declared)=ELM327 v2.1

Command	Version	Result
AT@1	1.0	OK
ATSPA6	1.0	OK
ATTPA6	1.0	OK
ATTP6	1.0	OK
ATSP00	1.3	OK
ATSP6	1.0	OK
ATAL	1.0	OK
ATNL	1.0	OK
ATAMC	2.0	KO
ATAMT20	2.0	KO
ATRA70	1.3	OK
ATSR70	1.2	OK
ATAR	1.2	OK
ATAT0	1.2	OK
ATAT2	1.2	OK
ATAT1	1.2	OK
ATBD	1.0	OK
ATBRT0F	1.2	OK
ATCAF0	1.0	OK
ATCAF1	1.0	OK
ATCEA04	1.4	OK
ATCERF1	2.2	KO
ATCEA	1.4	OK
ATCF00000111	1.0	OK
ATCF111	1.0	OK
ATCFC0	1.0	OK
ATCFC1	1.0	OK
ATCM00000111	1.0	OK
ATCM111	1.0	OK
ATCP18	1.0	OK
ATCRA7C0	1.3	OK
ATCRA000007C0	1.3	OK
ATCRA	1.4b	KO
ATCS	1.0	OK
ATCSM0	1.4b	KO
ATCSM1	1.4b	KO
ATCTM5	2.1	KO
ATCTM1	2.1	KO
ATCV0000	1.4	OK
ATD1	1.3	OK
ATD0	1.3	OK
ATDP	1.0	OK
ATDPN	1.0	OK
ATE0	1.0	OK
ATE1	1.0	OK
ATFCSD0430FF00	1.1	OK
ATFCSH000007B0	1.1	OK
ATFCSH7B0	1.1	OK
ATFCSM0	1.1	OK
ATFE	1.3a	OK
ATH0	1.0	OK
ATH1	1.0	OK
ATI	1.0	OK
ATIB10	1.0	OK
ATIB12	2.2	KO
ATIB15	2.2	KO
ATIB48	1.4	OK
ATIB96	1.0	OK
ATIFRS	1.2	OK
ATIFRH	1.2	OK
ATIFR0	1.2	OK
ATIFR2	1.2	OK
ATIFR1	1.2	OK
ATIFR6	2.2	KO
ATIFR5	2.2	KO
ATIFR4	2.2	KO
ATIGN	1.4	OK
ATIIA7A	1.2	OK
ATJS	1.3	KO
ATJE	1.3	KO
ATJHF0	1.4b	KO
ATJHF1	1.4b	KO
ATJTM5	1.4b	KO
ATJTM1	1.4b	KO
ATKW	1.3	OK
ATKW0	1.2	OK
ATKW1	1.2	OK
ATL0	1.0	OK
ATL1	1.0	OK
ATM1	1.0	OK
ATM0	1.0	OK
ATPPFFON	1.1	OK
ATPPFFOFF	1.1	OK
ATR0	1.0	OK
ATR1	1.0	OK
ATRV	1.0	OK
ATS0	1.3	OK
ATS1	1.3	OK
ATSDFF	1.4	OK
ATRD	1.4	OK
ATSH000007E0	2.0	KO
ATSHA848F1	1.0	OK
ATSH7B0	1.0	OK
ATST32	1.0	OK
ATSWFF	1.0	OK
ATTAF9	1.4	OK
ATV1	1.3	OK
ATV0	1.3	OK
ATWMC133F13E	1.0	OK
ATPC	1.0	OK
ATWS	1.0	OK
ATD	1.0	OK
ATZ	1.0	OK

and another ELM327 test .....

v1.0 ATZ [OK]
v1.0 ATWS [OK]
v1.0 ATE1 [OK]
v1.0 ATL1 [OK]
v1.0 ATL0 [OK]
v1.0 ATI [OK]
v1.0 AT@1 [OK]
v1.0 ATRV [OK]
v1.3 ATS1 [OK]
v1.3 ATS0 [OK]
v1.0 ATCAF0 [OK]
v1.0 ATCFC0 [OK]
v1.0 ATH0 [OK]
v1.0 ATR1 [OK]
v1.2 ATKW0 [OK]
v1.3 ATD1 [OK]
v1.3 ATD0 [OK]
v1.0 ATAL [OK]
V1.0 ATSP 3 [OK]
V1.0 ATSP 4 [OK]
v1.2 ATIIA 01 [OK]
v1.4 ATSI [OK]
V1.0 ATSP 5 [OK]
v1.4 ATFI [OK]
V1.0 ATSP 6 [OK]
V1.0 ATSP 7 [OK]
V1.0 ATSP 8 [OK]
v1.0 ATPC [OK]
v1.0 ATSH 012 [OK]
v1.0 ATSW 96 [OK]
v1.0 ATSW 34 [OK]
v1.0 ATWM 817AF13E [OK]
v1.0 ATIB 10 [OK]
v1.0 ATST FF [OK]
v1.3 ATCRA 012 [OK]
v1.3 ATCRA 01234567 [OK]
v1.1 ATFC SH 012 [OK]
v1.1 ATFC SH 00112233 [OK]
v1.1 ATFC SD 300000 [OK]
v1.1 ATFC SM 1 [OK]
v1.2 ATAT0 [OK]
v1.2 ATAT1 [OK]
v1.0 ATCM 123 [OK]
v1.0 ATCM 12345678 [OK]
v1.0 ATCF 123 [OK]
v1.0 ATCF 12345678 [OK]
v1.4 ATMA [OK/TIMEOUT]
STN11xx TEST 1 STI [FAIL]
STN11xx TEST 2 STDI [FAIL]
STN11xx TEST 3 STPR [FAIL]
STN11xx TEST 4 STPBRR [FAIL]
STN11xx TEST 5 STPRS [FAIL]
Result: 47 succeeded from 52

![bt elm327-3](https://user-images.githubusercontent.com/49172217/91505147-d0a71180-e8c6-11ea-8f41-ec88899e1d03.jpg)
![bt elm327-2](https://user-images.githubusercontent.com/49172217/91505151-d1d83e80-e8c6-11ea-961b-e3ec52247d0a.jpg)
![bt elm327 ](https://user-images.githubusercontent.com/49172217/91505152-d1d83e80-e8c6-11ea-9746-34d566b550fd.jpg)

@fesch

**Comment by yoh-there** [comment]
These are very generic dongles. They almost never work. The 2.1 is a giveaway. It MIGHT work if you set "use ISOTP frames". If not get a KV902; IMHO it doesn't break the bank. Since "Use a KV902 or build a CanSee dongle" is really the only advice we do and can reasonably give (see the website), I am closing this issue.
