### ISSUE TITLE
File google-services.json is missing.

### ISSUE THREAD

**Issue by Gosa7777** [fesch/CanZE#619]
Dear CAN-ZE team, 
first of all thanks and congrats to pulling off this App, great work!

I'm trying to build the App from the Github repository, but I'm getting the error message 
"File google-services.json is missing."
in Android Studio. 

Any suggestions on how to solve this?

Thanks
Claude

**Comment by Gosa7777** [comment]
I had never used Firebase before, now logged in with my google account linked the project to Crashlytics and it did create the json file. 
hope this is ok

**Comment by yoh-there** [comment]
If everything is OK, your crashes on your clone will now go to your Crashlytics, which is exactly as it should be. If not, oh well ;-)
