### ISSUE TITLE
Zoé VIN decoding : Help Wanted

### ISSUE THREAD

**Issue by FredLeudon** [fesch/CanZE#621]
Hi all

I need infos on Renault's VIN

Please, reply with first 10 digits of Your VIN (VF1AGVYA06) and full identification of Your Zoe

In this example, this is :  Zoé Q210 2013 Intens

Thanks for feedback, help is needed to correctly identify ZE40 and ZE50

**Comment by Notice-Jeroen-Meijer** [comment]
Q210 Life 2013 VF1AGVYA04

**Comment by FredLeudon** [comment]
Thanks, I really need vin for ZE40 & ZE 50

My new ZE 50 R 135 is VF1AG0004

Frédéric RICHARD

**Comment by fgmccrea** [comment]
R110 40 VF1AGVYF05

**Comment by fgmccrea** [comment]
Version from that is AGVYF0

**Comment by FredLeudon** [comment]
Thanks. 

Frédéric RICHARD

**Comment by fgmccrea** [comment]
Another one 40 VF1AG00006

**Comment by FredLeudon** [comment]
Please can you say if it’s a Q90, R90 or R110 plz

Frédéric RICHARD

**Comment by fgmccrea** [comment]
ah sorry its also r110 younger

**Comment by KarelSvo** [comment]
> Please can you say if it’s a Q90, R90 or R110 plz Frédéric RICHARD


All Zoe manufactured after February 20, 2018 have a consecutive VIN, independent of engine and battery. Identification via VIN code not possible.

**Comment by fgmccrea** [comment]
I thought it was R110Its probably manufactured in 2018Just so I don't give you bad information, can you tell me how to be certain its R110?

Sent from Yahoo Mail on Android 
 
  On Fri, 11 Sep 2020 at 19:55, KarelSvo<notifications@github.com> wrote:   



Please can you say if it’s a Q90, R90 or R110 plz Frédéric RICHARD


All Zoe manufactured after February 20, 2018 have a consecutive VIN, independent of engine and battery.

**Comment by madamic** [comment]
Zoe Q210 (2015) Intens, 22 kWh.
VF1AGVYA15

**Comment by FredLeudon** [comment]
Thanks. 

Frédéric RICHARD

**Comment by KarelSvo** [comment]
> Hi all
> 
> I need infos on Renault's VIN
> 
> Please, reply with first 10 digits of Your VIN (VF1AGVYA06) and full identification of Your Zoe
> 
> In this example, this is : Zoé Q210 2013 Intens


VF1AGVYA0**6**  just checked, this version does not exist in the Renault vehicle database.
there are
VF1AGVYA0E  year 2013 Brazil
VF1AGVYA0F year 2015 Brazil
VF1AGVYA0G year 2015 Brazil
VF1AGVYA0H year 2016 Brazil
VF1AGVYA04 year 2012 and 2013 Europe
VF1AGVYA05 year 2013 to 2016 Europe

**Comment by FredLeudon** [comment]
Yes sorry a gave 10 digits.

Only first 9 digits are useful to decode the VIN but some VINs doesn’t match the general rule. 

VF1 means Renault 
AGVYA0 means Q210
AGVYB0 means R240

I saw AGVYA1 and AGVYB1 ....

Next digits are the car’s serial number.

Frédéric RICHARD

**Comment by KarelSvo** [comment]
> I need infos on Renault's VIN

What is the background of your question? would you like canze to determine the vehicle type using the VIN?
A automatic detection of whether you are connected to phase 1 or phase 2 is easier to implement.

 For VIN decoding, I recommend the CAN CLIP DVD 200. The Renault offline vehicle database is stored there until May 2020.
https://gitlab.com/py_ren/pyren/-/blob/master/README.md
This software can extract all VINs of a vehicle type including date of manufacture, technical equipment, ECU reference data into a spreadsheet  document.
This software can also extract fault diagnosis documentation for your VIN from the CLIP DVD. In any language supported by CLIP.

**Comment by FredLeudon** [comment]
Yes, this is what I want to do. 

Frédéric RICHARD

**Comment by KarelSvo** [comment]
> Yes, this is what I want to do. Frédéric RICHARD

Selecting phase 1 vehicle types is unnecessary.
There are no different control units installed.
There are only differences between phase 1 and phase 2.
And that can be selected with a request to the EVC.
11 bit negative response = phase 2
29 bit negative response = phase 1
11 and 29 bit negative response = Fake Elm

or ask the UPC 74D about the DIAG VERSION
```
<IdFrame request="2180" response="6180"/>
<IdByte rank="6"  value="36"/> #phase 1
<IdByte rank="6"  value="3A"/> #phase 1
<IdByte rank="6"  value="40"/> #phase 2
```

**Comment by FredLeudon** [comment]
Ok and how do you deal with :

- twizy 
- kangoo 
- fluence
- smart / twingo

Frédéric RICHARD

**Comment by KarelSvo** [comment]
> Ok and how do you deal with : - twizy - kangoo - fluence - smart / twingo Frédéric RICHARD

You forgot the City-K ZE ;-)

**Comment by MarkRotNF** [comment]
ZE 50 R110 Exp.
VF1AG000X

**Comment by SMCinc** [comment]
VF1AGVYA05
Zoé Q210 2014 Intens

**Comment by Thecurrentcollector** [comment]
Zoe 2020 ZE 50 R135 Intens
VF1AG00006

**Comment by yoh-there** [comment]
@FredLeudon do you have enough data?

**Comment by FredLeudon** [comment]
Yes, can be closed. 

Frédéric RICHARD
