### ISSUE TITLE
Any explanation for Flt4 and Flt5 error codes

### ISSUE THREAD

**Issue by Shrolk** [fesch/CanZE#625]
It seems there is no explanation for end of charge caused by Flt4 ou Flt5 codes.
I guess it's an error code but what are the meanings of thoses ?

**Comment by yoh-there** [comment]
This mnemonic is the only thing that was listed in the documentation files we got our hands on. I have no idea what they actually mean. Silly I know, but I included them as some others do make sense and keep it complete.

**Comment by danielb7390** [comment]
A few months passed, i guess still nobody knows what they mean?
My zoe keeps stopping charge after a ~2h, i just unlock the car and open the door and it starts charging again...

![imagem](https://user-images.githubusercontent.com/5844389/126370670-7d040f3f-cb0a-4f24-9991-df270e96ef4c.png)
