### ISSUE TITLE
Frederick: can I help with iOS and ZE50 ?

### ISSUE THREAD

**Issue by ik2wxx** [fesch/CanZE#628]
@FredLeudon can I help you with iOS ZE50 support ?
I'm already working with other people on Android version.
Cheers
Roberto

**Comment by FredLeudon** [comment]
Hi, thanks.

Unfortunately, I’m very busy with my job and I don’t know when I will work on CanZE again. I hope before February :-)

My dongle won’t work anymore...

Sad time :-(

Frédéric RICHARD

**Comment by ik2wxx** [comment]
That's why I asked you if you need help :-)

**Comment by FredLeudon** [comment]
Ok,

Give me your email address and I’ll send you all datas I already get.

So, You will be able to search request and fields needed by CanZE.

Cordialement,


Frédéric RICHARD

**Comment by ik2wxx** [comment]
info@pw2.it
Thank you
