### ISSUE TITLE
Developing CANSEE on iOS version

### ISSUE THREAD

**Issue by FredLeudon** [fesch/CanZE#643]
Hi all,

I would like to develop CanSee communication.

I use only isoTP frames on CanZE for iOS.

Could somebody send a example of what is sending to cansee dongle and what the result look like ?

Example : i76D,2181,6181 is it ok ? 

Thanks

**Comment by yoh-there** [comment]
The documentation is here

https://gitlab.com/jeroenmeijer/cansee/-/wikis/Firmware

Your example is correct.

Cansee has a table doing the source/destination translation.

FYI, the third field ("6181") is ignored, so there is no real need to pass it to Cansee. Checks for receiving the expected response should be done in CanZE.

Edit: my previous answer was wrong, apologies.

**Comment by FredLeudon** [comment]
Thanks a lot, will try tomorrow while driving at work....

**Comment by yoh-there** [comment]
Closing (question answered)
