### ISSUE TITLE
Hard reset failed

### ISSUE THREAD

**Issue by solmoller** [fesch/CanZE#66]
When the app runs in the background it keeps trying to communicate with the OBD - fine, but it should stop complaining about the missing connection on top of other apps.

**Comment by fesch** [comment]
Heu?
On my device, the BT is stopped as soon as the app is no longer in background. The communication will be shut down cleanly to make sure the ELM is no in an inconsistent state.

**Comment by solmoller** [comment]
I have the app still running in the background, every five seconds I get the message

**Comment by fesch** [comment]
What message do you get exactly?

**Comment by solmoller** [comment]
I get this: "Hard reset failed :-("

**Comment by yoh-there** [comment]
Which is what I programmed in ELM after it detects a problem, tries a soft
reset, fails, tries a hard reset, fails again.

**Comment by solmoller** [comment]
.. And continues to warn about it despite the app being in the background. Apps in background should not pester their users.

**Comment by yoh-there** [comment]
Yes they should if things go wrong. However, it is debatable if it makes
any sense to run a "display" app when it is not in the foreground. IMHO.

**Comment by fesch** [comment]
When riding to school this morning:
- opened CanZE
- checked the Battery screen
- opened Driving screen

After 2 or 3 km, the message "had reset failed" popped up. 
After restarting CanZE (I did not touch the dongle), it worked again nicely until the end of my trip.

**Comment by yoh-there** [comment]
So, we need to do even harder resetting. Hmmmm.

**Comment by yoh-there** [comment]
There have been numerous changes to the ELM driver and when to run and not run the query thread. that I am closing this issue, but feel free to re-issue-or reopen.
