### ISSUE TITLE
ISOTP 7-byte single frame

### ISSUE THREAD

**Issue by landswellsong** [fesch/CanZE#665]
Hey-hey,
My friend is making a custom CanZE build with a few extra command on his non-OEM ZOE BMS and we found out that apparently (?) there's no support for sending 7 byte single frame ISO TP. 

Code in question: https://github.com/fesch/CanZE/blob/master/app/src/main/java/lu/fisch/canze/devices/ELM327.java#L596

I told him to try changing the clause to 14. Having worked with ELM low-level a bit, I know it might be related to the inability of sending a 8 byte CAN frame without `ATAL` command, but he tried and it worked so apparently it's executed somewhere down the line (I tried lazily grepping but didn't find).

So my question is, what's the logic behind that? Is it a compatibility thing to support dongles that can not into `ATAL` or is this something worth sending a pull request for?

**Comment by yoh-there** [comment]
TBH, I think it is simply a long standing bug. I'll have a peek again re ATAL, but sending 7 bytes in a FIRST/NEXT sequence is pretty much against the specs. Man, this has been in there for AGES, probably since we added outgoing long messages (so that must have been TPMS support).

PR is welcome of course!

**Comment by landswellsong** [comment]
Hmm what's the spec in question?

**Comment by yoh-there** [comment]
Well it's wiki https://en.wikipedia.org/wiki/ISO_15765-2 But it says

> SINGLE: The single frame transferred contains the complete payload of up to 7 bytes (normal addressing) or 6 bytes (extended addressing)
> First frame: The first frame of a **longer** multi-frame message packet, used when more than 6/7 bytes of data segmented must be communicated. The first frame contains the length of the full packet, along with the initial data. 

Bolding mine. We have never used extended addressing (used for gateway stuff; we might need to in the future), so read 7 above.

Edit: we do issue ATAL at initialization, see line 202

**Comment by landswellsong** [comment]
Ah, I never worked with extended ids that's why I was confused. How about I implement this:
1. If the packet is extended addressed we keep as it is.
2. If the packet is standard addressed we allow 7 bytes too

Given `ATAL` is there, no other changes should be necessary. I'll build tomorrow and check if anything else falls of on a real car.

**Comment by yoh-there** [comment]
Extended is a completely different beast than 29 bits addressing if I read correctly, so IMHO only the if at line 596 should be changed (12 -> 14)?

**Comment by landswellsong** [comment]
Oh, that's another *extended*, yeah then the simple clause change with a comment would do.

**Comment by yoh-there** [comment]
Thank you sir! No PR needed. Will put it in.

**Comment by yoh-there** [comment]
Closed through 7214774c
