### ISSUE TITLE
Reset DTC

### ISSUE THREAD

**Issue by Dimonlipko** [fesch/CanZE#667]
Hello.

I found bug, that frame to clear DTC is not correct. Frame that send ELM327 01 14 00 00 00 00 00 00, must be 04 14 FF FF FF 00 00 00

![photo_2020-12-25_00-58-14](https://user-images.githubusercontent.com/59143371/103142690-35a53380-4710-11eb-9508-b995728fcc99.jpg)

**Comment by Dimonlipko** [comment]
Sorry, I use not last version CanZE. I will check, all work good))

![Снимок экрана (410)](https://user-images.githubusercontent.com/59143371/103142943-6c317d00-4715-11eb-941e-2323871c69fa.png)

**Comment by yoh-there** [comment]
Don't be sorry. Thank you for reporting and welcome! We sure can use your knowledge!
