### ISSUE TITLE
AllDataActivity - An error inserts additional redundant new line into log file

### ISSUE THREAD

**Issue by Matthew1471** [fesch/CanZE#673]
In AllDataActivity.java additional new lines get written to the file if an error occurs.

> 18daf1db.629282.264,PCB traceability.01,48,
> 18daf1db.6292a0:-E-Message.isotp.startswith7f
> 
> 18daf1db.6292c0:-E-Message.isotp.startswith7f`
> 

I believe this is caused by the \n on line 255 in AllDataActivity.java: 
`appendResult(frame.getFromIdHex() + "." + frame.getResponseId() + ":" + message.getError() + "\n");`

Also linked but the combined frames are missing a new line (as none are inserted into the string buffer that is blindly appended) :

> 18daf1db.62903c.24,Cell 28 Voltage(Wtx_cell_v[27]),4.085,V
> 18daf1db.629000.24,DIDs supported in range [$9001 - $9020],3F1EF7EE,18daf1db.629001.24,Battery SOC(Zxx_bsoc_avg),90.54,%18daf1db.629002.24,Battery USOC(Wxx_usoc_avg),90.46,%18daf1db.629003.24,Battery SOH(Zxx_sohe_avg),95.74,%18daf1db.629005.24,Pack Voltage (CAN value)(Wxx_pack_v_out),392.4,V18daf1db.629006.24,Sum of all Cell Voltage(Wxx_pack_v),393.313,V18daf1db.629007.24,Maximum Cell Voltage(Wxx_cell_v_max),4.092,V18daf1db.629008.24,Number of Maximum Cell Voltage(Wxx_cell_v_max_nr),39,18daf1db.629009.24,Minimum Cell Voltage(Wxx_cell_v_min),4.083,V18daf1db.62900a.24,Number of Minimum Cell Voltage(Wxx_cell_v_min_nr),0,18daf1db.62900c.24,Current Sensor Offset value(Wxx_bat_i_ofs),0.00,A18daf1db.62900d.24,Instant Current of Battery (CAN value)(Wxx_bat_i_10ms_out),15.28,A18daf1db.62900e.24,Maximum Generated Power (After Restriction)(Wxx_rgn_pw_lngtrm),13.00,kW18daf1db.62900f.24,Maximum Available Power (After Restriction)(Wxx_dchg_pw_lngtrm),118.38,kW18daf1db.629011.24,Low Voltage Supply(Wxx_raw_14v_mes),14.021,V18daf1db.629012.24,Average Temperature(Wxx_temp_avg),3.31,°C18daf1db.629013.24,Minimum Temperature(Wxx_temp_min),3.00,°C18daf1db.629014.24,Maximum Temperature(Wxx_temp_max),4.00,°C18daf1db.629018.24,Maximum Charge Power (after restriction)(Wxx_chg_pw),7.90,kW18daf1db.629019.31,End Of Charge flag(Wbx_chg_end),0:Charging OK,18daf1db.62901a.30,HVBatt Interlock flag(Wsx_HVcn_ilck_out),2:Closed,18daf1db.62901b.24,Battery Identification Number (BIN).25,2,18daf1db.62901b.32,Battery Identification Number (BIN).24,9,18daf1db.62901b.40,Battery Identification Number (BIN).23,5,18daf1db.62901b.48,Battery Identification Number (BIN).22,1,18daf1db.62901b.56,Battery Identification Number (BIN).21,0,18daf1db.62901b.64,Battery Identification Number (BIN).20,5,18daf1db.62901b.72,Battery Identification Number (BIN).19,9,18daf1db.62901b.80,Battery Identification Number (BIN).18,2,18daf1db.62901b.88,Battery Identification Number (BIN).17,8,18daf1db.62901b.96,Battery Identification Number (BIN).16,R,18daf1db.62901b.104,Battery Identification Number (BIN).15,T,18daf1db.62901b.112,Battery Identification Number (BIN).14,F,18daf1db.62901b.120,Battery Identification Number (BIN).13,0,18daf1db.62901b.128,Battery Identification Number (BIN).12,4,18daf1db.62901b.136,Battery Identification Number (BIN).11,1,18daf1db.62901b.144,Battery Identification Number (BIN).10,7,18daf1db.62901b.152,Battery Identification Number (BIN).09,0,18daf1db.62901b.160,Battery Identification Number (BIN).08,7,18daf1db.62901b.168,Battery Identification Number (BIN).07,F,18daf1db.62901b.176,Battery Identification Number (BIN).06,F,18daf1db.62901b.184,Battery Identification Number (BIN).05,F,18daf1db.62901b.192,Battery Identification Number (BIN).04,F,18daf1db.62901b.200,Battery Identification Number (BIN).03,F,18daf1db.62901b.208,Battery Identification Number (BIN).02,F,18daf1db.62901b.216,Battery Identification Number (BIN).01,F,18daf1db.62901c.24,Traceability Identification Number (TIN).19,R,18daf1db.62901c.32,Traceability Identification Number (TIN).18,L,18daf1db.62901c.40,Traceability Identification Number (TIN).17,0,18daf1db.62901c.48,Traceability Identification Number (TIN).16,F,18daf1db.62901c.56,Traceability Identification Number (TIN).15,2,18daf1db.62901c.64,Traceability Identification Number (TIN).14,L,18daf1db.62901c.72,Traceability Identification Number (TIN).13,2,18daf1db.62901c.80,Traceability Identification Number (TIN).12,4,18daf1db.62901c.88,Traceability Identification Number (TIN).11,1,18daf1db.62901c.96,Traceability Identification Number (TIN).10,7,18daf1db.62901c.104,Traceability Identification Number (TIN).09,0,18daf1db.62901c.112,Traceability Identification Number (TIN).08,7,18daf1db.62901c.120,Traceability Identification Number (TIN).07,L,18daf1db.62901c.128,Traceability Identification Number (TIN).06,2,18daf1db.62901c.136,Traceability Identification Number (TIN).05,9,18daf1db.62901c.144,Traceability Identification Number (TIN).04,A,18daf1db.62901c.152,Traceability Identification Number (TIN).03,R,18daf1db.62901c.160,Traceability Identification Number (TIN).02,0,18daf1db.62901c.168,Traceability Identification Number (TIN).01,0,18daf1db.62901d.24,Functional Identification Number (FIN).01,2,18daf1db.62901d.32,Functional Identification Number (FIN).02,,18daf1db.62901d.40,Functional Identification Number (FIN).03,ô,18daf1db.62901d.48,Functional Identification Number (FIN).04,F,18daf1db.62901d.56,Functional Identification Number (FIN).05,2,18daf1db.62901d.64,Functional Identification Number (FIN).06,L,18daf1db.62901d.72,Functional Identification Number (FIN).07,2,18daf1db.62901d.80,Functional Identification Number (FIN).08,4,18daf1db.629020.24,DIDs supported in range [$9021 - $9040],FFFFFFFE,18daf1db.629021.24,Cell 1 Voltage(Wtx_cell_v[0]),4.088,V18daf1db.629022.24,Cell 2 Voltage(Wtx_cell_v[1]),4.102,V18daf1db.629023.24,Cell 3 Voltage(Wtx_cell_v[2]),4.099,V18daf1db.629024.24,Cell 4 Voltage(Wtx_cell_v[3]),4.099,V18daf1db.629025.24,Cell 5 Voltage(Wtx_cell_v[4]),4.094,V18daf1db.629026.24,Cell 6 Voltage(Wtx_cell_v[5]),4.100,V18daf1db.629027.24,Cell 7 Voltage(Wtx_cell_v[6]),4.100,V18daf1db.629028.24,Cell 8 Voltage(Wtx_cell_v[7]),4.089,V18daf1db.629029.24,Cell 9 Voltage(Wtx_cell_v[8]),4.088,V18daf1db.62902a.24,Cell 10 Voltage(Wtx_cell_v[9]),4.102,V18daf1db.62902b.24,Cell 11 Voltage(Wtx_cell_v[10]),4.088,V18daf1db.62902c.24,Cell 12 Voltage(Wtx_cell_v[11]),4.090,V18daf1db.62902d.24,Cell 13 Voltage(Wtx_cell_v[12]),4.089,V18daf1db.62902e.24,Cell 14 Voltage(Wtx_cell_v[13]),4.099,V18daf1db.62902f.24,Cell 15 Voltage(Wtx_cell_v[14]),4.102,V18daf1db.629030.24,Cell 16 Voltage(Wtx_cell_v[15]),4.098,V18daf1db.629031.24,Cell 17 Voltage(Wtx_cell_v[16]),4.097,V18daf1db.629032.24,Cell 18 Voltage(Wtx_cell_v[17]),4.085,V18daf1db.629033.24,Cell 19 Voltage(Wtx_cell_v[18]),4.102,V18daf1db.629034.24,Cell 20 Voltage(Wtx_cell_v[19]),4.099,V18daf1db.629035.24,Cell 21 Voltage(Wtx_cell_v[20]),4.090,V18daf1db.629036.24,Cell 22 Voltage(Wtx_cell_v[21]),4.089,V18daf1db.629037.24,Cell 23 Voltage(Wtx_cell_v[22]),4.100,V18daf1db.629038.24,Cell 24 Voltage(Wtx_cell_v[23]),4.084,V18daf1db.629039.24,Cell 25 Voltage(Wtx_cell_v[24]),4.088,V18daf1db.62903a.24,Cell 26 Voltage(Wtx_cell_v[25]),4.095,V18daf1db.62903b.24,Cell 27 Voltage(Wtx_cell_v[26]),4.102,V
> 18daf1db.62903d.24,Cell 29 Voltage(Wtx_cell_v[28]),4.088,V

I think the best way to do the new lines might be for the bufferedwriter to add them as it does now via log( ) and the textView to also add its own but the messages passed to both functions should not contain a trailing line feed (unless a line feed is inbetween multiple fields). Each appender is then responsible for its own line feed format and the params passed around do not have to expect multiple lines. To save effort a List of strings (assuming thread safe) might help keep track of how many records are inserted in your buffer, a stringbuffer will require too much editing of the strings where multiple messages exist (i.e. is this the last message in the buffer to add a newline to or are more coming).

**Comment by yoh-there** [comment]
Thank you Matthew. Fixed 55d8d636 0eeb7a65
