### ISSUE TITLE
Zoe 50 Charge history Type column inconsistent [seems EVC firmware version issue]

### ISSUE THREAD

**Issue by codavu** [fesch/CanZE#675]
Hi guys, 

I received my new Zoe 50, showroom car, bought with 750 KM on dash. 

Still I did one 22KW charge from 39% to 81% ( at 881 KM ), then tried the flexycharger at home and charged at 1.8 KW for 1.5 Hours up to 83 %  ( at 887 km / 85% on dash ). 

Still the problem I spoted is the column of Type, which seems somehow blocked to the values. 

Attached are the screenshots of the Charge History where the column can be seen to be stuck at the same values. 
I am using a Konnwei dongle, on Android 10

Thanks for the work done on CanZE !! Appreciated !

.

![Screenshot_20210123-185739](https://user-images.githubusercontent.com/45878332/105743057-8f319580-5f3c-11eb-8006-60cf74763a53.jpg)
![Screenshot_20210123-171719](https://user-images.githubusercontent.com/45878332/105743076-935db300-5f3c-11eb-92bf-7931296db5c2.jpg)
![Screenshot_20210122-201905](https://user-images.githubusercontent.com/45878332/105743087-95c00d00-5f3c-11eb-8394-7ec7ad13e688.jpg)

**Comment by yoh-there** [comment]
Thanks for reporting!

CanZE tries to refresh these fields (60 in total) every 6 seconds. This might be too fast and the poller might fail to schedule in sequence. I will move the requests to the queue that handles them in sequence. I will close this issue, but please reopen if the issue persists after the current (1.59) release. 09ef6157

**Comment by codavu** [comment]
Thanks for the quick fix on this one. I will keep an eye on this. 
Also I am new Zoe user, and if I can help on the quality part, I will do it.

**Comment by supiiik** [comment]
@codavu can you please check, what FW version of EVC ECU you have? Because in my ZE50, the charging table isn't working at all

**Comment by R240Pe** [comment]
I have been using CanZE every day for years for a complete battery documentation of all trips and charging processes for my Q90 and it is excellent that CanZE has also been adapted for ZE50 in recent months. Very good work! Congratulations!
Unfortunately, the charging history does not work on the ZE50. After completion of a loading process, the values ​​of the loading process are displayed. If you immediately carry out another loading process - without interrupting CanZE - this data is also displayed correctly and additionally after completion - i.e. 2 lines with loading data.
If CanZE is then terminated and restarted, there is no longer any access to the previously displayed data, all values are 0.
When the charging process is complete, the available range is also displayed. This range is not displayed on the charging info pages (NaN). The total battery range driven is also not displayed.
Is there a particular problem with showing these existing two data values ​​on both sides?
If you need further information or screenshots, I will be happy to provide it.
I have BETA and every release now 1.60 installed immediately.

**Comment by yoh-there** [comment]
OK, so not fixed. Thanks for the additional info. Needs some discussion in the team. What we seem to know right now is:
- We have NOT been able to get the "GOM" at all from any ECU, which hampers the third graph in Consumption. So, I am quite curious you got it. Can you please give every detail you have? EVC firmware, what screen/field you got it?
- The history seems to be an EVC firmware problem. One ZE50 team member with fairly recent EVC firmware seems to have good values, another with somewhat older has not. I'll ask for their firmware numbers.

**Comment by R240Pe** [comment]
EVC Data: 
diagVersion: 07
supplier: CONTINENTAL_ENGINE_SYSTEM
Soft: 0A10
Version: 6A00
I am attaching the screenshot with the loading progress of the two consecutive loading processes. The odometer reading 3096 displayed in the charging history was correct during the charging process. This number is not displayed on the "Technology load parameters" page, but the information "-".

Unfortunately, I didn't take an instant screenshot with the range at the time. So far, I only had a value displayed on the technology-charging-info-page this once, immediately after completing a charging process. If this information is not (so far) available for CanZE, the page may not have been completely updated and the line still showed a different or old value. Then I may have been wrong. But I will keep an eye on it during the next charging processes.
![Screenshot_20210121-033533](https://user-images.githubusercontent.com/34570383/107171749-d0f21f80-69c3-11eb-88cd-d6a938fcfe6f.png)

**Comment by yoh-there** [comment]
Thank you 0A10 seems to indeed have this problem. Waiting for the results of the car that seems to be fine.

**Comment by codavu** [comment]
Hey guys, 

I will give it a try today/tomorrow , once my wife gets home. It's her car.. so no direct access to it.

**Comment by codavu** [comment]
Hi guys,

Managed to get my hands on the Zoe, and I have this:
![image](https://user-images.githubusercontent.com/45878332/107265277-5cab9080-6a44-11eb-8819-9ac381e9fcd4.png)

As for the charge history I can still see the same "Inc / 3x Lente"  repeating, as below:

![image](https://user-images.githubusercontent.com/45878332/107265458-941a3d00-6a44-11eb-8454-5ed075e75376.png)

Thanks

**Comment by Notice-Jeroen-Meijer** [comment]
Update, Remember, this applies only for the ZE50.

All drivers with EVC firmware version: 6A00, diagVersion: 07 seem to have this problem. Drivers with firmware version: 69B0, diagVersion: 08 have no problem with history. Note that the firmware version is LOWER, but the diagVersion is HIGHER.

I don't think there is anything we can do in CanZE to fix this. Unless someone sees another way out, or sees this problem on said firmware, this issues is earmarked for closing. I will change the title.

**Comment by yoh-there** [comment]
Update, Remember, this applies only for the ZE50.

All drivers with EVC firmware version: 6A00, diagVersion: 07 seem to have this problem. Drivers with firmware version: 69B0, diagVersion: 08 have no problem with history. Note that the firmware version is LOWER, but the diagVersion is HIGHER.

I don't think there is anything we can do in CanZE to fix this. Unless someone sees another way out, or sees this problem on said firmware, this issues is earmarked for closing. I will change the title.

**Comment by codavu** [comment]
Hi @yoh-there 

This issue was opened for the inconsistent Type column values. 
With each recharge I am doing I do get the same pattern of: Unknown / Slow / Slow / Slow  and repeating no matter the kilometers.

Is this inconsistency coming from the EVC ? I have 69B0 as firmware version. Or this is because of the dongle being used ?

Regards,

**Comment by yoh-there** [comment]
@codavu I honestly can't answer that question. I need to relay it to ZE50 owners as I cannot check it at all.

To the team: sorry guys ;-)

**Comment by codavu** [comment]
@yoh-there No problem 

Thanks for the great work you are doing on CanZE !!

**Comment by R240Pe** [comment]
As I wrote some days ago: "The total battery range driven is also not displayed." on the CanZE Screen "Ladeparameter - HV-Akkudaten - gefahrene Akkureichweite -"
I knew, I saw it somewhere - and now I found this information: **EVC-HCM-VCM 18daf1da.622006.24, Total vehicle distance,3253,km**

![Screenshot_20210208-043935](https://user-images.githubusercontent.com/34570383/108449278-809c7c80-7263-11eb-9ef5-3481ea2aeda9.png)

**Comment by yoh-there** [comment]
This issue has gone stale. I am closing it but feel free to reopen. Personally, there is not a lot I can do with my Q210.
