### ISSUE TITLE
Significato di Total battery usage

### ISSUE THREAD

**Issue by casalelli** [fesch/CanZE#676]
Il total battery usage è sono i kWh caricati nella batteria compresi dell'energia rigenerata o no?
Per il consumo totale dell'auto devo considerare 
Total battery usage
oppure
Total battery usage - total energy from regenerative breacking
?
Nota: breacking dovrebbe essere braking
grazie e grazie del vostro lavoro

**Comment by yoh-there** [comment]
We cannot be 100% sure, but since this number is reported by the battery computer, I don't think it has knowledge that it's coming from regeneration or not. Hope this helps.

**Comment by casalelli** [comment]
Sono riuscito a fare 2 prove, con l'utilizzo aumenta la sola energia da rigenerazione di frenata per cui la Total Battery usage è la sola energia dovuta alle ricariche esterne
