### ISSUE TITLE
Can CanZe be adapted to Captur plugin adding a specific profile?

### ISSUE THREAD

**Issue by Roberto-1967** [fesch/CanZE#677]
Hi I know that this is not an issue but CanZe works at 99% on my captur plugin using ZOE50 profile but there are issues in some parameters so the overall experience is not good. It's really a pity since most of the features are perfectly running.
Do you think it's possible to add a "Captur plugin" profile?
I can help you somehow providing logs from my car if needed.
Some screenshots below.
![Screenshot_20210110-171809](https://user-images.githubusercontent.com/78104691/106038077-c4261f80-60d7-11eb-9028-f6bdacfd3288.jpg)

 Have a look to the Nm
![Screenshot_20210116-195845](https://user-images.githubusercontent.com/78104691/106038197-ec158300-60d7-11eb-96f2-88b61c1b7825.jpg)

![Screenshot_20210103-122129](https://user-images.githubusercontent.com/78104691/106038426-3c8ce080-60d8-11eb-96b1-0a2b9b3d6f62.jpg)

This is working as most of the other features
![Screenshot_20210103-125633](https://user-images.githubusercontent.com/78104691/106038204-f20b6400-60d7-11eb-9c2c-a3d3d51c7978.jpg)

**Comment by fesch** [comment]
Is there a Captur EV version?

**Comment by Roberto-1967** [comment]
it's a plugin 9.8 kw battery

**Comment by fmarsico70** [comment]
I add myself to Roberto's request for this improvement.

**Comment by yoh-there** [comment]
While I honestly understand and appreciate the interest, I don't think any of the current developers are able to pick this up, manly by simply not having access to the car. We learned the hard way that it is close to impossible to get things right without that. I propose to close the issue, as it's basically stale.

**Comment by Roberto-1967** [comment]
Ok I understand the difficulties related to not having the car to run test. 
Let me say that if any existing or new developer will have an E-tech car available it could be very interesting to extend the coverage in a dedicated branch. 
You'll notice that there will be a lot of e-tech cars on the roads in the next months.
Thanks
