### ISSUE TITLE
Zoe 2015 model, battery change

### ISSUE THREAD

**Issue by Erspange** [fesch/CanZE#682]
Hello

I want to buy and change the high voltage battery on my zoe, but I want to know if I can reprogramme it for the new and bigger batterypack my self?

Best regards
Erik

**Comment by yoh-there** [comment]
The Ph2 (ZE50) battery cannot be installed in a Ph1 car. There are people buying an old Ph1 battery and replacing the cells with modern ones.............

**Comment by Erspange** [comment]
Hello yoh-there

My plan is to buy a 41Kwh phase 1 battery used from a condemned Zoe. The main reason is that my battery is down to 67% health.
