### ISSUE TITLE
ZE50 error while reading LBC DTCs

### ISSUE THREAD

**Issue by ZMan88** [fesch/CanZE#683]
Hello,

I have an issue with CanZe when trying to read the DTCs codes for the LBC
![LBC_DTC_Error](https://user-images.githubusercontent.com/23256232/108397889-2084e680-7221-11eb-9a17-2274badb7dfe.jpg)
Not sure if it is a problem with the zoe, or the dongle used.
The dongle used is KONNWEI KW902.

I also have errors when trying to get all the firmware versions 
![Firmware_Error](https://user-images.githubusercontent.com/23256232/108398285-85d8d780-7221-11eb-8149-887f5f6837a3.jpg)

Also getting errors when opening the BRAKING activity but did not get a screenshot of that.
If there is any more info that I could provide, tell me and I will.

Love the app btw, adds a lot of functionality that Renault missed when developing the system.

**Comment by ZMan88** [comment]
I forgot to say, I m using version 1.60

**Comment by yoh-there** [comment]
What dongle are you using please? Something is very wrong if it doesn't accept atsp6.

**Comment by ZMan88** [comment]
The dongle i am using is
![IMG_20210220_085554](https://user-images.githubusercontent.com/23256232/108586979-fe42b400-7359-11eb-93e5-02ad50789b51.jpg)

**Comment by ZMan88** [comment]
![Screenshot_20210303-184416](https://user-images.githubusercontent.com/23256232/109866617-25f51e80-7c6e-11eb-8c3d-50fd2a443a43.jpg)
I get this when I test the dongle, if it helps

**Comment by Leobaillard** [comment]
Thanks for the details. I have some tests planned in my Zoe with the Konwei. I'll check your issue and report back as soon as possible.

**Comment by yoh-there** [comment]
There has been no follow up on this issue. I will close it because it is stale. Feel free to reopen.
