### ISSUE TITLE
ZE50 errors with canze v 1.60

### ISSUE THREAD

**Issue by AsparagusRex** [fesch/CanZE#684]
Hello,

I am not a technical person but I try my best.
I connected an ELM adapter (KONNWEI KW902 OBDII) with my ZOE Phase 2, Life R110 Z.E. 50.
I eanbled bluetooth on the adapter and my smartphone and got agood connection.
Selected the Konnwei adapter and the ZE40/ZE50 in the canze app.
So far so good.
Bit on most screens i get error messages and no data :(

I ataach two screenshots.

Any idea, what is wrong here?

Thanks

As.
![2021-02-18 18 46 42](https://user-images.githubusercontent.com/23653919/108412744-74e09400-722a-11eb-8d20-a1fcbb9b0c6c.jpg)

![2021-02-18 18 46 12](https://user-images.githubusercontent.com/23653919/108412741-73af6700-722a-11eb-9dc9-d4445625f03e.jpg)

**Comment by yoh-there** [comment]
Not all fields we know from the Ph1 cars are mapped or even available in the Ph2. But the does not exist should not happen. Can you add a screen of your setting, especially so that it shows your device and the car settings?

**Comment by AsparagusRex** [comment]
is that what you are looking for?

![2021-02-20 10 52 01](https://user-images.githubusercontent.com/23653919/108591709-5aadcf80-736a-11eb-85e2-aad2c57da04e.jpg)

**Comment by AsparagusRex** [comment]
Hello? Any ideas out there?

**Comment by ZMan88** [comment]
I have the same errors on my zoe ze50 with konnwei adaptor

**Comment by AsparagusRex** [comment]
Is it a problem of the adapter (Kinnwei), or the software, or the Zoe model?

**Comment by Leobaillard** [comment]
Hi, I'm currently doing tests on my Zoe and a Konwei adapter to try and reproduce. I'll keep you updated.

**Comment by AsparagusRex** [comment]
Let me know if I canbe of help for testing etc.

**Comment by AsparagusRex** [comment]
Any progress on this issue?

**Comment by Leobaillard** [comment]
Hi!

Sorry for not answering sooner, I had to take a break for family reasons and I'm now back.

I just did some more tests in my car with two different phones and the stable version of the app, everything is working as expected with the Konnwei.

Some follow up questions though:
- do you get any data while driving for the consumption screen for example?
- did you check the option in settings to allow data while driving?
- some of the data is only "moving" when the car is moving too, can that explain the data showing "0" on your end? (sorry if this seems trivial, but just making sure)
- could you show us the results of the "ELM test" page of the app while the car is ON and the Konnwei is connected?

Some more questions about the Konnwei:
- when did you buy the dongle?
- if you bought it online, do you still have the listing page with the product details and could you link it here?

I'm sure we can figure this out if there is indeed a problem related to the app. It could also be a newer version of the dongle that changed stuff in the way it communicates with the app (hence my questions about your dongle).

**Comment by AsparagusRex** [comment]
Hello,

glad you are back.

Let me start with the Konnwei question :)

I bought it online at the Konnwei Store at Amazon:
https://www.amazon.de/gp/product/B077XGSV83

Now for the other questions:
>do you get any data while driving for the consumption screen for example?
Yes, screenshot attached
 
>did you check the option in settings to allow data while driving?
Yes

>could you show us the results of the "ELM test" page of the app while the car is ON and the Konnwei is connected?
attached

Hope this helps :)
![2021-04-12 17 11 08](https://user-images.githubusercontent.com/23653919/114421325-7ccb0d80-9bb5-11eb-8b8c-47bda46b27a7.jpg)
![2021-04-12 17 11 51](https://user-images.githubusercontent.com/23653919/114421328-7dfc3a80-9bb5-11eb-9d4d-9385d9864ced.jpg)
![2021-04-12 17 14 45](https://user-images.githubusercontent.com/23653919/114421333-7f2d6780-9bb5-11eb-894f-558ba6666eda.jpg)

**Comment by Leobaillard** [comment]
Ok, good, thanks!

Just to be sure, what is not working? It seems from your screenshot that the data is loading, right? Do you only get the error message when opening the page first and not after or does it come back repeatedly while using a particular screen? For the former, it could just be that the data takes time to load initially for some reason but it ok afterwards.

**Comment by AsparagusRex** [comment]
Let me test that and get back to you

**Comment by AsparagusRex** [comment]
Hi, sorry it took me so long but now I am happy to report that everything seems to be working on the Z50.
Thanks a lot
As.

**Comment by yoh-there** [comment]
Thank you for reporting back to us. Closing.
