### ISSUE TITLE
CAN ZE FOR KANGOO? 

### ISSUE THREAD

**Issue by Elektroreini** [fesch/CanZE#685]
I have Kangoo ZE but no acess to reset faults.
Any ideas?

**Comment by yoh-there** [comment]
We stopped supporting the Kangoo a while ago, sorry.

**Comment by Elektroreini** [comment]
I disassembled and fixed faulty motor.
My mechanical Scills are better than my programming. But Im willing to support
I have Kangoo ZE.   IXAT CAN bus converter.. Some electronic skills.
