### ISSUE TITLE
CanZE for VW ID.3?

### ISSUE THREAD

**Issue by c64emulator** [fesch/CanZE#686]
The CanZE is a great App for ZOE. The functionality and usabilty is unexcelled.
I would appreciate any efforts to make this app working for the VW ID.3.

**Comment by yoh-there** [comment]
We honestly appreciate the compliment, but there is no way any of the current team members can make this work. All Renault ZOE drivers and half of the time we are sitting on our cars with laptops on our lap trying to figure out what the hell is happening. Of course anyone who is really into this can take CanZE as a base and add (nice!) or make his own VW version (that's OK, it's open source).

Closing this issue.
