### ISSUE TITLE
bêta de l’app CanZE

### ISSUE THREAD

**Issue by olloollol** [fesch/CanZE#688]
Bonjour 
Je souhaite tester la version bêta de l’app CanZE.
Il est indiqué :
Pour rejoindre la version bêta de l’app CanZE, commencez par installer TestFlight, puis touchez le lien sur votre iPhone ou iPad.
Ou trouve t on le lien une fois que l'on a intallé TestFlight ?
Merci pour votre réponse

**Comment by ik2wxx** [comment]
From the CanZE site https://canze.fisch.lu :
CanZE is available as a beta test in Testflight using this link https://testflight.apple.com/join/gypjWAtk
