### ISSUE TITLE
iOS TestFlight wifi dongle connection settings

### ISSUE THREAD

**Issue by JulesBuh** [fesch/CanZE#692]
I have the iOS CanZE app build 3.0.1.0 which works with v-link WiFi dongle. I was trying to connect the TestFlight iOS app 1.0(5) but couldn’t match the settings to connect.

I’ve tried http option and match the IP and port that the working app shows in the settings but that didn’t work on TestFlight iOS app.

the TestFlight one looks better since I’m trying to get the log which isn’t accessible on the 3.0.1 iOS build

any suggestions?

**Comment by ik2wxx** [comment]
Hi
I can't talk about previous iOS version, I don't know how it works.

About TestFlight version, if the dongle is wifi, you should select "wifi" connection type in the app settings, not http.
But first you should connect to the dongle wifi network.

So, first power up the dongle, wait for his wifi network, connect the phone to it.
Get the ip address of the dongle.
Configure the app to connect to a ELM327 dongle via wifi, insert dongle ip address and port, and test connection with the button in the settings screen.
Please let me know.

**Comment by JulesBuh** [comment]
Thanks I’ll give that a go and report back

**Comment by StevenMeel** [comment]
Bonjour 
j'essaye de me connecter mais sur les paramètres wifi  j'ai bien l'adresse ip mais je n'ai pas de port. 
![FB64EE72-524F-41ED-8FF2-9FC00A1EEE05](https://user-images.githubusercontent.com/83688852/117278942-80268180-ae61-11eb-9b2b-c2f3b7b813be.png)

**Comment by ik2wxx** [comment]
Hello
Try 35000, that's the default tcp port for most wifi obd adapters.
Otherwise, check on the adapter documentation.

**Comment by StevenMeel** [comment]
Je viens de vérifier la notice du dongle et le port est bien 35000. 
Je dois faire quelques chose de mal, impossible de ce connecter. 
![2B207D16-F824-4DA4-AD91-CD1E608FC0BB](https://user-images.githubusercontent.com/83688852/117305556-2cc32c00-ae7f-11eb-84f7-4023f8112757.png)
![5187E53A-F37B-4963-8A38-52571D5C39C1](https://user-images.githubusercontent.com/83688852/117305574-30ef4980-ae7f-11eb-99dc-c60c83552c2b.png)
![DDFF0280-B66F-4C08-9B96-FB8F31C06E60](https://user-images.githubusercontent.com/83688852/117305594-364c9400-ae7f-11eb-964f-39a55354ef08.png)
![8DB033BF-1023-4E30-9B1F-CB4F3B309A16](https://user-images.githubusercontent.com/83688852/117305615-3a78b180-ae7f-11eb-9703-6db4c4d9cf80.png)
![8A169D31-1F91-48F2-ABF0-F8F8370EC497](https://user-images.githubusercontent.com/83688852/117305626-3c427500-ae7f-11eb-8050-d43636f3dba7.png)

**Comment by ik2wxx** [comment]
Hello
The adapter ip is 192.168.0.10, not 192.168.0.11 (this is your phone address)

**Comment by StevenMeel** [comment]
J'ai corrigé mais je me connecte toujours pas. 
![B766A7F1-7EE5-420A-B4AE-E9B48EAAAB62](https://user-images.githubusercontent.com/83688852/117320885-eecd0480-ae8c-11eb-9b1e-d5cb163696a9.png)

Voila ce que j'obtiens quand j'appuie sur connect puis test. 
Faut il que j'appuie sur d'autres boutons pour me connecter ?
![AB054B3F-5F58-43F7-9A54-1379C65BB355](https://user-images.githubusercontent.com/83688852/117321175-3358a000-ae8d-11eb-94df-d0989b1f1966.png)
![2028DFA4-C341-42A4-A6C6-DDB0B0092D09](https://user-images.githubusercontent.com/83688852/117321183-35226380-ae8d-11eb-82ed-e40755d079b6.png)
![83958385-F0CD-4E4F-87E6-85CDF94BEF78](https://user-images.githubusercontent.com/83688852/117321207-394e8100-ae8d-11eb-874f-e059a4342652.png)

**Comment by ik2wxx** [comment]
Hello
The adapter is connected, and CanZE is correctly connected to it, but the adapter is not replying correctly.
Look at the "NO DATA" replies...
Is the car powered ?
Is it a Q210 model Zoe ?
Can you post a photo of the adapter ?
Thank you

**Comment by StevenMeel** [comment]
J'ai compris mon erreur j'ai pas appuyer sur la prise. 
maintenant tout fonctionne merci
![D2A022C9-8626-4E70-900F-85AEFC86CC11](https://user-images.githubusercontent.com/83688852/117333501-48d3c700-ae99-11eb-82f6-c5858331b2af.jpeg)
![51C76E9C-6FE6-49BC-A5E9-034E02E38557](https://user-images.githubusercontent.com/83688852/117333511-4b362100-ae99-11eb-84e5-0d89f8cb6de3.jpeg)

**Comment by ik2wxx** [comment]
Hello
Please ask if you need more help
Bye
