### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by frh** [fesch/CanZE#695]
Would you mind if CanZE were included in the free and open source app store F-Droid (https://f-droid.org/)? This would be very helpful for those not running Google services.

For this a build flavor not using Firebase would have to be created, as F-Droid does not allow proprietary dependencies.

**Comment by yoh-there** [comment]
I had a quick look at the process. It seems elaborate, adding the project to their git repository and F-Droid compiling from source. Quite another workflow than the Play store.

Firebase is a tool for us to do quality monitoring that we really like ;-)

Given the limited gains this doesn't seems to be a diligent use of our limited resources.

I have no problem to either
- restart our habit of publishing binary (.apk) releases on GitHub. (To be honest at some moment in time we simply forgot doing that and nobody seems to have noticed)
- informing you when a new release is out in case you want to take on this task yourself, and publishing a link to the F-Droid page.

**Comment by frh** [comment]
I understand not wanting to spend resources to support it. I have very limited experience with Gradle and Android packaging in general, but I could take this on if you don't mind. From what I see what I'd have to do is to create a build flavor for F-Droid that doesn't include Firebase, and then open an issue on the F-Droid issue tracker and fix any other issues that might come up.

F-Droid uses Git releases/tags to automatically build new versions, so if you guys could start tagging releases again that would make that process more automated.

**Comment by yoh-there** [comment]
No problem at all. Lovely if you would take that on thanks. If we need to incorporate something for a flavor, feel free to do a pull request.

Don't hesitate to remind us if we seem to have skipped a release tag. We're on a fairly slow release schedule now, so it might fall through the cracks but from my end I'll try to put/keep it in the workflow.

**Comment by frh** [comment]
Thanks for the merge! Regarding the release, it looks like the latest version is 1.60, but the latest tagged release is 1.48?

**Comment by yoh-there** [comment]
Correct. As I said, we kind of forgot to do that. Does it help if I add a a 1.60 tag?

Edit: and if so, is it mandatory for F-droid that I include the source code in the release as a binary? Sorry for the questions, I want to do this once and right!

**Comment by frh** [comment]
Adding a 1.60 tag would help a lot, thank you! Especially helpful if that tag includes the Gradle build flavor commit!

From what I understand F-Droid packaging only cares about the Git tag, so I don't think it matters whether or not the source code is included as a binary.

**Comment by yoh-there** [comment]
Done :-)

**Comment by frh** [comment]
Thanks! I just opened a Request For Packaging at https://gitlab.com/fdroid/rfp/-/issues/1724. I'll let you know if any issues arise.

**Comment by yoh-there** [comment]
Done :-)

**Comment by frh** [comment]
Thanks for the review! I will get started on a PR to F-Droid to package CanZE. Would you mind doing a new release tag to include these changes, or maybe removing and re-adding the 1.60 tag if that's possible? Sorry for that, my bad!

**Comment by yoh-there** [comment]
No problem. Just let me know when I should do that, Just making sure I shouldn't before everything is set.

**Comment by frh** [comment]
From the reply I got in the RFP ticket, I'm pretty sure that you can do it now.

**Comment by yoh-there** [comment]
Done :-)

**Comment by Notice-Jeroen-Meijer** [comment]
I don't think it's included yet. Anything I need to do?

**Comment by frh** [comment]
> I don't think it's included yet. Anything I need to do?

Thanks, but it looks like all we're waiting for now is for the F-Droid people to review my PR at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8935.

**Comment by yoh-there** [comment]
Looks like there is stagnation on the Fdroid end after your hard work. Indeed there seems nothing on our ends that they seem to be waiting for.

**Comment by frh** [comment]
I asked about it on IRC. The reviewers are just busy, so we'll just have to wait a bit longer.

**Comment by frh** [comment]
The PR is being reviewed now. They want to include info on what the app's permissions are used for. Based on my own digging these are what each permission is used for, is this correct?

**location (`ACCESS_COARSE_LOCATION`, `ACCESS_FINE_LOCATION`):** Include location in optional local logging
**Bluetooth (`BLUETOOTH`, `BLUETOOTH_ADMIN`):** Car communication
**storage (`WRITE_EXTERNAL_STORAGE` and thus implicitly also `READ_EXTERNAL_STORAGE`):** Optional writing of logs
**network (`INTERNET`):** Get app news from GitHub repo

**Comment by yoh-there** [comment]
That is all correct. I would probably say "Canbus dongle communication", but that's nitpicking. Have they indicated anything about where to put that information? Let me know if I need to pull something please.

**Comment by yoh-there** [comment]
Merged. Do they need a version bump?

**Comment by frh** [comment]
Thanks! Unfortunately they do need a bump. I'll ask if there's anything else they need so we can avoid any more unnecessary ones.

**Comment by frh** [comment]
No more changes here should be necessary, so if you could do a version bump to include the latest PR that would be great.

**Comment by yoh-there** [comment]
Done :-)

**Comment by frh** [comment]
Thanks! Could you tag the new release as well?

**Comment by yoh-there** [comment]
Sorry. Done.

**Comment by yoh-there** [comment]
I think F droid use is stale. On our end we forgot tagging releases, on the other hand, no one raised an issue. I am closing this one for it going stale.

**Comment by frh** [comment]
> I think F droid use is stale. On our end we forgot tagging releases, on the other hand, no one raised an issue. I am closing this one for it going stale.

The F-Droid build is still working very well. I've been using it for a few years now, but I never went to GitHub to check for new releases so I didn't notice that the version was stale. It's set to auto release new versions when tagged on GH with the version number as the tag name, so if you tag a new release it should get picked up!
