### ISSUE TITLE
Battery change, ph1 to ph1 battery

### ISSUE THREAD

**Issue by Erspange** [fesch/CanZE#698]
I have a Zoe with very poor battery health, and I have gotten hold of a newer battery. My current battery is 23KWh and has about 67% health, in the ZE app. When I change the battery, I need to set in the firmware the new capasity of the battery, is this possible in CANze? In case no, how do I go forward to change battery in the cars SW?

**Comment by fesch** [comment]
The only thing that CanZE can modify / set in the car, are the TMPS sensors.
I don't think that it is possible to simply change the capacity of the battery somewhere. I rather think this is somewhere inside the BMS of the battery, so the new battery should already know about it.

**Comment by Erspange** [comment]
Thanks for a quick answer!

This means I can just change battery and everything is ok...

**Comment by fesch** [comment]
You mean "you by yourself" or "your dealer"?

**Comment by Erspange** [comment]
I am a trained engineer, so more than capable of changing a battery ;)

**Comment by fesch** [comment]
Ah, then I'm reassured :-)
