### ISSUE TITLE
Bug Canze avec Zoé Q210

### ISSUE THREAD

**Issue by StevenMeel** [fesch/CanZE#699]
Bonjour 
J'utilise depuis peu Canze
Je me connecte bien en wifi avec le konnwei
J'ai eu le soh
J'ai bien la température des modules 
Mais je n'arrive pas a avoir la tension des cellules, y a t il une astuce ?

![60507FD6-E82F-4701-9286-3F8BECC3BF7C](https://user-images.githubusercontent.com/83688852/117214261-da412b80-adfc-11eb-872e-df6800589a61.png)

![1E12E114-8D2B-49B1-92B4-288F289A045E](https://user-images.githubusercontent.com/83688852/117214302-ec22ce80-adfc-11eb-9af9-11e79cdf2f03.png)

**Comment by ik2wxx** [comment]
Hello Steven.
Are you using the iOS version from https://testflight.apple.com/join/gypjWAtk ?
I guess you are using the iOS CanZE that's not mantained by the official CanZE Team (our screens are different).
I suggest you to try our app :-)

**Comment by StevenMeel** [comment]
Oui, j'avais essayé celle qui était dans apple's app. 
Je vais essayer la vôtre au plus vite. 
merci

**Comment by StevenMeel** [comment]
Effectivement avec votre application ça fonctionne. 
Merci

Pourquoi nous ne voyons que 96 cellules, nous en avons 192, non ?
![A506F77F-281A-4A3F-9356-CFAD165AC5B4](https://user-images.githubusercontent.com/83688852/117333997-cb5c8680-ae99-11eb-9fd2-88dbe6da8cbf.png)

**Comment by ik2wxx** [comment]
Hello
Cells are coupled in pairs.
So there is no available tension control for every cell but only for coupled (1+1) cells.
Bye

**Comment by StevenMeel** [comment]
Encore une question, j'accède au ECU LBC et pas au ECU LBC2. 
Est-ce normal ?
![FE5143B7-9FDE-4750-BE6E-A9153ACA8F46](https://user-images.githubusercontent.com/83688852/117334875-cf3cd880-ae9a-11eb-967b-2e5722fb211f.png)
![37A0B0B3-45D9-4C32-A84B-C5DE880253B5](https://user-images.githubusercontent.com/83688852/117334881-d1069c00-ae9a-11eb-95d4-4b6979574a6d.png)
