### ISSUE TITLE
ECU LCB2 qui ne s'affiche pas

### ISSUE THREAD

**Issue by StevenMeel** [fesch/CanZE#701]
Bonjour 
Juste une question, j'accède au ECU LBC et pas au ECU LBC2. 
Est-ce normal ?
![FE5143B7-9FDE-4750-BE6E-A9153ACA8F46](https://user-images.githubusercontent.com/83688852/117334875-cf3cd880-ae9a-11eb-967b-2e5722fb211f.png)
![37A0B0B3-45D9-4C32-A84B-C5DE880253B5](https://user-images.githubusercontent.com/83688852/117334881-d1069c00-ae9a-11eb-95d4-4b6979574a6d.png)

**Comment by fesch** [comment]
Oui, cela peut être normale et dépend de la voiture.

**Comment by StevenMeel** [comment]
Dommage car dans ces ECU LBC je vois la tension des 96 cellules , et j'aurais aimé avoir la tension des cellules des 96 autre dans LCB2.

**Comment by yoh-there** [comment]
LBC2 is not "the other half". It is a backup computer system for the battery. LBC shows all voltages. The cells are paired, so a string of 96 pairs. Roberto already explained this in your issue #699. Closing.
