### ISSUE TITLE
Help for CANZE beginner

### ISSUE THREAD

**Issue by Mike2304** [fesch/CanZE#702]
I want to connect to my Zoe. I bought a Konnwei android dongle but it didn't work with my old Samsung tablet, so I bought a Konnwei Wifi dongle. The dongle seems to connect to my iphone, but I can't access the car. I get a message in French which says ELM Test "The wifi dongle was detected but it could not connect to it.
please disconnect the dongle, wait a few moments, reconnect it and try the operation again. make sure the vehicle is turned on".
I can't find any help on your website for new owners, so am requesting it here.
Regards Mike
2015 Zoe

**Comment by yoh-there** [comment]
For Android, the Q&A https://canze.fisch.lu/qa/ might help, esp issue 9.

Calling @ik2wxx for iOS

**Comment by ik2wxx** [comment]
Hello
Talking about iOS, that message is not from our official iOS app, maybe you're using another CanZE app that is not supported by us.
Please try the official iOS CanZE app currently available in Testflight at https://testflight.apple.com/join/gypjWAtk

**Comment by Mike2304** [comment]
Hi,
Thanks, will do. Got app from Apple app store.
Mike

**Comment by Mike2304** [comment]
Hello,
Thanks for reply,
I installed app to iphone from Test Flight. Successfully connected to
Konnwei and tested connection. Plug symbol shows on, but no data showing.
Car out of range of home wifi and mobile data off. Iphone shows wifi
connected to Konnwei.
Not sure if car is Q210, but is 2015 June. How can I tell? Feel I must be
doing something wrong.
Regards Mike

**Comment by Notice-Jeroen-Meijer** [comment]
If it's a 2015 car, it's either a Q210 or an R240. From the CanZE point of view, they are not very different.

The difference is very easy to see under the hood: The Q has a big metal box on top in the middle. The R has a black plastic pipe on top in the middle (air cooling duct). See also this post by Mo1 https://www.speakev.com/threads/zoe-model-info.88161/page-2#post-1604105

**Comment by ik2wxx** [comment]
Hello Mike
In the iOS app, settings screen, please enable "log to sdcard" and then, in the same screen, "test dongle".
Wait for the test result, then open the File app, you will find the log of all communication between app and adapter.
You can post the log here, if the log content does not help you to understand the problem.
Roberto

**Comment by Mike2304** [comment]
Hello Roberto,
Thanks for reply. On the CANZe app I get log to sd1. Iphone doesn't have an
sd card, but I enabled 'Log to SD1".
"Test Obd" says OK.
Where do I open "File App" ? Is this within the CANZE app or somewhere else?
Have left iphone in car for a while as it seems to be going through many
"debug activities" to see if anything happens. Have tried with and without
car on charge.
Mike

**Comment by ik2wxx** [comment]
Hello Mike
Message related to "sd1" is coming from translations we are waiting to update (the app is in test).
The File app is an Apple app available on every iOS device
More info here https://support.apple.com/en-us/HT206481

**Comment by Mike2304** [comment]
Hi Robert,
I tried again without success. Nothing showing in "files".
To clarify:
Iphone is connecting to Konnwei and CanZe is showing connection to "Test
dongle" ok. All readings on CanZe are blank or zero, but it shows debugging
scrolling
CanZE settings are:
Device type ELM327
Connection _WiFi
Device address 192.168.0.10
device port 35000
Log to sdcard1 Yes
Write for emulator Yes
Regards Mike

**Comment by ik2wxx** [comment]
Hello
Please try again with newer build 1.0 (6)
Thank you

**Comment by Mike2304** [comment]
Hello,
Thanks for reply, we are now away from uk, so will try when we are back.
Regards Mike

**Comment by Mike2304** [comment]
Hello,
Have tried this again today, still no results. I have 1(6)
[CanZE 1628436137.log](https://github.com/fesch/CanZE/files/6951123/CanZE.1628436137.log)
I am afraid I am completely unfamiliar with this and hope you can help. I just want to know my battery SOH because range is only 57 miles.
Regards Mike

**Comment by ik2wxx** [comment]
> [CanZE 1628436137.log](https://github.com/fesch/CanZE/files/6951123/CanZE.1628436137.log)

Hi Mike
Reading from the log, I can see that connection between app and dongle is ok, connection between dongle and can bus is KO.
Most request have reply "CAN ERROR"
Also, request "atcra7ec" have reply "?", I suspect the dongle is not compatibile with Zoe.
Please try other obd dongle (or loan a working one from a friend)
Supported obd dongles are listed here https://canze.fisch.lu/hardware/
BTW, I have a Konnwei 902 wifi (green one) and works great.

**Comment by Mike2304** [comment]
Hi Roberto,
Thanks for your advice.
The first one I bought was Konnwei 902 BT (black), but it wouldnt work with
my old Samsung tablet and all my other devices are Apple.
So I then bought Konnwei 903 wifi (orange) which is this one for IOS.
I queried it with Konnwei and they sent the attached, which doesn't explain
what the difference is with the 902wifi.
Frustrating!
Mike

**Comment by KarelSvo** [comment]
> Hi Roberto, Thanks for your advice. The first one I bought was Konnwei 902 BT (black), but it wouldnt work with my old Samsung tablet and all my other devices are Apple. So I then bought Konnwei 903 wifi (orange) which is this one for IOS. I queried it with Konnwei and they sent the attached, which doesn't explain what the difference is with the 902wifi. Frustrating! 

to understand how counterfeiting is done   https://cvtz50.info/en/elm327/
an example for 4mhz elm 
aliexpress.com/item/4000159235000.html
ebay.com/itm/123997779408
kingbolentool.com/collections/basic-obd2-code-reader/products/kingbolen-obd2-scanner-bluetooth-check-engine-light?variant=31540043481145

**Comment by ik2wxx** [comment]
> I queried it with Konnwei and they sent the attached, which doesn't explain what the difference is with the 902wifi. 

Maybe you forgot to attach a file or an image ?

**Comment by mkozachok** [comment]
I have the same issue. Is it compatible with Konnwei 901 WIFI?
