### ISSUE TITLE
Gone from TestFlight 

### ISSUE THREAD

**Issue by sramskill** [fesch/CanZE#705]
Hi

firstly brilliant job all . Been using for a few months now and love it .. however now can’t get at it in test flight - getting beta expired message . 

S

**Comment by AMV093** [comment]
Hello! 

I am also getting the same error in Test Flight. :( 

Anyway, the app is very usefull and full of hidden info about the car.

I hope that it’ll get fixed soon! 

Thank you!

**Comment by ik2wxx** [comment]
Hello
Should be ok now.
Sorry for that

**Comment by AMV093** [comment]
It works now, thank you so much!
