### ISSUE TITLE
Latest version misreading values

### ISSUE THREAD

**Issue by sirdir1972** [fesch/CanZE#706]
Hi

The latest beta seems to read values more quickly from the ODB adapter. Problem is it misreads most values.

**Comment by yoh-there** [comment]
Thanks for reporting. Version 1.60, the latest,  was released on februari 4th. Are you sure there is this causality? If so, can you please provide us with as much information as possible?
- car type (esp if it's a Ph1 or Ph2 car; if it's a Ph1, please try the "ISOTP" setting)
- dongle used
- settings

EDIT: I am sorry, I misread. I think you are talking about the iOS beta, Please confirm, Thanks

**Comment by sirdir1972** [comment]
Yes, I'm talking about the iOS beta 1.0 (6)

The Dongle is a LELink BLE btw, the car a Zoe Q210

**Comment by yoh-there** [comment]
Got it, re-assigned. BTW, I am not sure if the ISOTP setting is in the iOS version, trying that might help.

**Comment by sirdir1972** [comment]
ISOTP is active

**Comment by ik2wxx** [comment]
Thank you for reporting, can you please post some screenshots of uncorrect data ?

**Comment by sirdir1972** [comment]
Sure, here are some screenshots. It's coincidence what data is correct and what not and it may change with every 'loop' of querying the ODB, I'd say:
https://www.icloud.com/sharedalbum/#B0v5M7GFPxybc1

**Comment by ik2wxx** [comment]
Thank you.
As I'm reading from screenshots, data from car is not recognized.
Data is NAN (not a number) or EMPTY when no reply received.
Is the car model correct ?
Most Zoe models need specific command to read data and setting wrong car model will prevent you to receive correct data.
I can't say this is the problem solution, just trying to help.
Also, can you please enable logs and retry to fetch some data, than share logs with us ?
Logs can be enabled in settings screen, and are written on your iphone, you can find them with Apple File app under "CanZE" folder.
Apple File app can be downloaded from Apple App Store if you don't have it already
https://apps.apple.com/app/file/id1232058109

**Comment by sirdir1972** [comment]
Hi!
Car Model is correct (Q210) and it has all worked until I updated to the latest beta. It seems to read the data quicker than before but not always correctly.

I’ll attach the logs


Sent from my iPad

Regards
Patrick

**Comment by ik2wxx** [comment]
Thank you for reporting, we will investigate.
Build 5 is expired so you can't install it anymore, sorry.

Any other Q210 or Lelink user, please tell us if you have problems.

**Comment by wolfijenne** [comment]
Just tried it out (same configuration with R90). I made a video of it, maybe it helps.

https://www.spider.li/RPReplay_Final1624102662.MP4

**Comment by ik2wxx** [comment]
Thank you, can you please also post Settings screen ?


> Just tried it out (same configuration with R90). I made a video of it, maybe it helps.
> 
> https://www.spider.li/RPReplay_Final1624102662.MP4

**Comment by Giankymis** [comment]
Hello, i have a wifi dongle. Is there anyone that have configured It over http? I have try to add dongle ip address but not works. Thanks

**Comment by wolfijenne** [comment]
sorry, did not see this earlier. 
![image](https://user-images.githubusercontent.com/549286/130207388-bcb41906-1f95-4161-b8d9-323fd568a1d3.png)

**Comment by sirdir1972** [comment]
any news on this? Still can't use CanZe…

**Comment by ik2wxx** [comment]
> any news on this? Still can't use CanZe…

We're waiting for report of other Q210 users...but looks like other Q210 have no issues.
BTW, I did not receive your logs, can you please resend them ?

**Comment by wolfijenne** [comment]
I also have this problem. I would love to send you logs, however, I have no idea where to find them on my iphone as the iphone.

thx, Wolfgang

**Comment by ik2wxx** [comment]
> I also have this problem. I would love to send you logs, however, I have no idea where to find them on my iphone as the iphone. thx, Wolfgang

Your car model is R90, not Q210, let's separate issues.

Logs can be enabled in settings screen, and are written on your iphone, you can find them with Apple File app under "CanZE" folder.
Apple File app can be downloaded from Apple App Store if you don't have it already
https://apps.apple.com/app/file/id1232058109

**Comment by wolfijenne** [comment]
Thx... I finally found them. As I tried it just recently, here is a log. The log should consist of the charging screen and the cell Voltages screen. If you want me to try something specifically, pls let me know.

[Emulator 1630791445.log](https://github.com/fesch/CanZE/files/7116475/Emulator.1630791445.log)
[CanZE 1630791439.log](https://github.com/fesch/CanZE/files/7116477/CanZE.1630791439.log)

**Comment by ik2wxx** [comment]
> Thx... I finally found them. As I tried it just recently, here is a log. The log should consist of the charging screen and the cell Voltages screen. If you want me to try something specifically, pls let me know.
> 
> [Emulator 1630791445.log](https://github.com/fesch/CanZE/files/7116475/Emulator.1630791445.log)
> [CanZE 1630791439.log](https://github.com/fesch/CanZE/files/7116477/CanZE.1630791439.log)

Thank you for reporting log files, let me check.

**Comment by sirdir1972** [comment]
> > any news on this? Still can't use CanZe…
> 
> We're waiting for report of other Q210 users...but looks like other Q210 have no issues.
> BTW, I did not receive your logs, can you please resend them ?

Sure, I'll send you the logs I currently have. 
I'm not sure he Q90 and Q210 issues are different, they look very similar. I don't have access to another compatible blutooth dongle, but this one worked fine before the update. 
[CanZE 1630934434.log](https://github.com/fesch/CanZE/files/7117549/CanZE.1630934434.log)

**Comment by sirdir1972** [comment]
Bought another BLE dongle. Works fine with ABRP but same problem with CanZE. I have the impression CanZE communicates faster with the car/dongle than it did before. Maybe it would help to add some delay or a lower baudrate or something?

**Comment by jakub-a** [comment]
Here is Q90 ZE40 (2019). Using the Vgate iCar Pro BT4.0 and CanZE 1.0 (9). Values are not available  or not read correctly:
![IMG_3756](https://user-images.githubusercontent.com/67999691/159874965-0594d517-45b7-4a3c-b7bb-882db3c3c472.PNG)

![IMG_3755](https://user-images.githubusercontent.com/67999691/159874992-6be4f8a3-3d58-4b37-8a31-3694d5ce5560.PNG)

https://user-images.githubusercontent.com/67999691/159875019-b15be840-45e0-4348-8449-cc2b598775ec.MP4

**Comment by ik2wxx** [comment]
> Here is Q90 ZE40 (2019). Using the Vgate iCar Pro BT4.0 and CanZE 1.0 (9). Values are not available or not read correctly: 

Hi, did you try other car models in setting screen?
Try both "ZOE ZE40/ZE50" and "ZOE R90/110" and "ZOE Q90" to find your correct setting.

**Comment by jakub-a** [comment]
I tried all models but I am not getting the correct readings or no readings at all.

**Comment by ik2wxx** [comment]
> I tried all models but I am not getting the correct readings or no readings at all.

Then the problem seems to be the dongle...can you try a different one?

**Comment by jakub-a** [comment]
Good to know. Thank you - I will return it then. Unfortunately I don't have a second iCar Pro. I do have a BLE dongle that works on my old android device but the iOS App only allows 2 devices: Vgate iCar Pro and LELink.
Is there a way to pair with a different device?

Here is the iCar Pro that doesn't seem to work.
![IMG_3813](https://user-images.githubusercontent.com/67999691/160357779-554534e0-8f1e-4409-a473-bfa975c7fc82.jpg)
.

**Comment by sirdir1972** [comment]
Why would it be the dongle if an older build (I mention which one in another thread) works? I compiled that version myself and it works.

**Comment by ik2wxx** [comment]
> Good to know. Thank you - I will return it then. Unfortunately I don't have a second iCar Pro. I do have a BLE dongle that works on my old android device but the iOS App only allows 2 devices: Vgate iCar Pro and LELink. Is there a way to pair with a different device?

Go to the last page scrolling the home view to the left, you will see a "TEST OBD" button.
Click "connect" and select the OBD BLE name, then try with "Auto Init" and "TEST" button to see if it works.
If it works, send me then OBD BLE name and I will add it as compatible.

**Comment by ik2wxx** [comment]
> Why would it be the dongle if an older build (I mention which one in another thread) works? I compiled that version myself and it works.

I have same dongle and same app and it works. I don't have same car so I can't tell.
I'm just trying to help.
Will change the source in next release so no PH2 cars will use a slower queue delay as before.

**Comment by jakub-a** [comment]
I connected to the dongle both the iCar Pro as well as the other BLE Dongle but the App Crashes every time i try to run a rest. 

Happy to help by sending logs and whatnot. 

https://user-images.githubusercontent.com/67999691/160434486-b54dec87-ca91-4852-a87f-df22ba9eede2.MOV

**Comment by ik2wxx** [comment]
> I connected to the dongle both the iCar Pro as well as the other BLE Dongle but the App Crashes every time i try to run a rest.

I think you selected the wrong "notify" characteristic.
To select the correct characteristic, choose one with the correct characteristic.
For write, choose one in the picker with "write" in description (FFF2 seems ok).
For notify, choose "FFF1", not FFF2.
Hope it's correct.
If you don't see any reply when tapping "SEND", something is wrong. 
Dongle BLE name is OBDII, I can add it if you can complete "auto init" and then "test" button sequence with correct results.

**Comment by jakub-a** [comment]
I did it as you instructed. Still the test button crashes the app.

**Comment by jakub-a** [comment]
https://user-images.githubusercontent.com/67999691/160490650-455974b4-3b40-4709-8635-7fc8bcfe9359.MOV

**Comment by ik2wxx** [comment]
> I did it as you instructed. Still the test button crashes the app.

I will add the OBDII ble device in the settings screen so you can test it with the full app functions.
Wait for Testflight alert to update the app.
Let us know!

**Comment by jakub-a** [comment]
Tested both dongles: the iCar Pro and the unknown brand OBDII BLE. Both connect but both give wrong readings for some parameters. But compared to the build 9 more have correct values. In this and previous versions they are slow to update values. Voltage heat map crashed the app. The build 11 also caused the dashboard to turn on and a message about automatic lock was shown briefly. Should I be logging these sessions for you?
![F0EC5919-23E7-412D-94BE-89ECAD4BE40D](https://user-images.githubusercontent.com/67999691/160677144-a1c48c47-53e2-4527-81ce-e9e84df8d559.png)
![97C259D0-A1BA-47F6-B7B9-FF0E39A5EB23](https://user-images.githubusercontent.com/67999691/160677160-63d9bb0e-ab3e-4a2b-83b2-dcb8c782f512.png)

**Comment by ik2wxx** [comment]
Thank you for reporting, we always have issues with ELM327 dongles and I don't have any experience with cars that are not model ZE50.
I need to check the app.
Will come back as I have any news.

**Comment by jakub-a** [comment]
This ELM327 dongle has been tested on Android with CanZE and is working fine. It looks like it's dongle independed because it shows similar errors for both the no-name ELM327 as well as iCar Pro BLE.
If it was working before (as other users report) on the Q model, then something must have changed how the app communicates to cause this regression.

**Comment by jakub-a** [comment]
> Thank you for reporting, we always have issues with ELM327 dongles and I don't have any experience with cars that are not model ZE50.
> I need to check the app.
> Will come back as I have any news.

@ik2wxx  - in one of the previous posts you suggested the iCar Pro dongle is defective. Do you still maintain that it's broken given more evidence?

**Comment by ik2wxx** [comment]
No, I've tried by myself and I think the problem can be solved by the app.
Communication between app and dongle is a real pain (mainly for data receiving).
I've tried slowing the dongle command queue and now it's better, but not a real problem solution.
BTW I will publish a version with adjustable dongle command queue delay so you can experiment on your car.
I'm using a value of 0.20 in my ZE50 and works ok.
Please note that a slower delay will make the data receiving faster, but you can receive wrong data.
Also I noticed that, after a wrong data is received, all other data are not fully reliable!!! Using a slower delay will not solve the problem, you will have to disconnect the dongle from the car, reconnect to the car, reconnect to the app :-(
I hope to release the new version today.

**Comment by sirdir1972** [comment]
Doesn't work, even on 0.50. the temperatures in the advanced charging screen get messed up every time. 
It still works with build 5. Build 6 and onwards breaks it. 
BTW what's about the 'energy to full' value, that's always messed up. Does work on the Android version.

**Comment by jakub-a** [comment]
Is there any way I can use the **build 5** @sirdir1972 @ik2wxx ?

No delay setting works properly. It is starting to receive meaningful data at a delay=0.03s but increasing it doesn't really improve things much. I have it at 0.05 right now. There are some data being received properly such as `pedal position` or `wheel torque` (with occasional hiccups).

Thanks for trying to fix it!

**Comment by ik2wxx** [comment]
Rolling back to older releases will delete latest updates (translations, fixes, features).
Please wait until I can add those news into the older release, without touching connection with ELM.

**Comment by LakesGeek** [comment]
Seeing similar here with vgate icar pro ble 4.0.  on the default delay of 0.2 it "kind of works on some screens" - refuses to report max charge/Regen, real state of charge, only one cell is read for temperature (and is wrong) etc.   Using 1.0.1 from TestFlight. 

If I connect the same dongle to my Android phone which seems to use standard Bluetooth and need pairing, everything works quickly and accurately.  Problem is specific to ios / BLE

**Comment by sirdir1972** [comment]
>  Problem is specific to ios / BLE

Yep, but still works in an older version. Unfortunately I'm having problems getting it compiled (managed it a while ago, but deleted my phone and would have to reinstall the older version again)

**Comment by ik2wxx** [comment]
> Seeing similar here with vgate icar pro ble 4.0. on the default delay of 0.2 it "kind of works on some screens" - refuses to report max charge/Regen, real state of charge, only one cell is read for temperature (and is wrong) etc. Using 1.0.1 from TestFlight.
> 
> If I connect the same dongle to my Android phone which seems to use standard Bluetooth and need pairing, everything works quickly and accurately. Problem is specific to ios / BLE

iOS version need some fixes for BLE adapters, I'm sorry I didn't find any time to work on it. That's why the app is still in development. Also I don't have the car always available for tests :-(

**Comment by ik2wxx** [comment]
> > Problem is specific to ios / BLE
> 
> Yep, but still works in an older version. Unfortunately I'm having problems getting it compiled (managed it a while ago, but deleted my phone and would have to reinstall the older version again)

What's the version that works better for you ?

**Comment by sirdir1972** [comment]
> What's the version that works better for you ?

Huh, it's so long now.. The version that was out on June 5th 2021 already had the problem. The version before was fine. 1.0(5) was still OK? Would that match the releases? Reread the thread and yes, version 5 was still OK.

**Comment by LakesGeek** [comment]
> > Seeing similar here with vgate icar pro ble 4.0. on the default delay of 0.2 it "kind of works on some screens" - refuses to report max charge/Regen, real state of charge, only one cell is read for temperature (and is wrong) etc. Using 1.0.1 from TestFlight.
> > If I connect the same dongle to my Android phone which seems to use standard Bluetooth and need pairing, everything works quickly and accurately. Problem is specific to ios / BLE
> 
> iOS version need some fixes for BLE adapters, I'm sorry I didn't find any time to work on it. That's why the app is still in development. Also I don't have the car always available for tests :-(

Thanks in any case for your work on it.  It does the minimum I need it to do which is show charging rate

If I can help in some way let me know

**Comment by ik2wxx** [comment]
This should have been solved with last version

**Comment by sirdir1972** [comment]
Hi!

It’s not, i.E. battery temperatures are still mostly read as NaN

**Comment by ik2wxx** [comment]
> Hi! It’s not, i.E. battery temperatures are still mostly read as NaN

Hello
All battery values, cell temperature and cell voltage included, are correctly read with the app.
I used a VGate OBD dongle.
