### ISSUE TITLE
TPMS 8 digit HEX code to 6 digit HEX code

### ISSUE THREAD

**Issue by mishu28nmv** [fesch/CanZE#708]
I am sorry to ask this here, but I can't understand the calculation an user explained!
I have the following 8 digit HEX ID's (TPMS sensors):
AD114712
AD10AA64
AD10AA6E
AD10AA92
What are the correct 6 digit HEX ID's I should insert in ddt4all?

**Comment by yoh-there** [comment]
See https://canze.fisch.lu/tpms-once-more/

Please close this issue if answered, thanks.

**Comment by mishu28nmv** [comment]
Thank you. I tried first to find that thread, but no luck. Thank you for pointing that out. I will read there and hope I will have my answear!
