### ISSUE TITLE
Max charge/regen dropping fast

### ISSUE THREAD

**Issue by ZMan88** [fesch/CanZE#710]
It's more of a question that an issue with the app.
When driving around it shows that a large number on "Max charge/regen" but when I plug it in that number drops fast... Anybody got any thoughts on that?
Here's a screenshot while charging:
![Screenshot_20210609-105359](https://user-images.githubusercontent.com/23256232/123209944-00647d00-d4ca-11eb-8fe0-be8eeaa1d48c.jpg)

**Comment by yoh-there** [comment]
I cannot answer your question. The Ph2 LBC still has a lot of operational mysteries. In Ph1 the number was determined by the battery temperature and state of charge.

The most plausible explanation is that the Ph2 now actually shows the short-time overcurrent the battery can take: my Ph1 accepts up to roughly double the allowed current for about one minute, which is great for regenerative braking. However that did not show in the field we are looking at.

I'll close the issues as there is nothing we can do but speculate (which is ok and fun). Feel free to continue though.
