### ISSUE TITLE
Zoe Q90 - Available charging power never reaching 43kW when the required conditions are met

### ISSUE THREAD

**Issue by alexdslva** [fesch/CanZE#712]
Hi,

I have gotten into the habit of monitoring the values with CanZE every time I charge my Zoe (Q90, 41kWh) at a 43kW AC fast charging station.

Whenever the application displays a "Max battery charge/regen" of 43kW, the "Available charging power" never reaches it. I get, at best, around 41kw. I have found this to be the case on all the fast charging stations I have used so far.

Did anyone ever managed to reach the 43kW ? If not, do you have any idea why this might be? I personally have 3 possible hypotheses:

- Either the values returned by CanZE (or the dongle) are incorrect,
- Either there are energy losses between the charging station and the car charger (cable, connectors, etc),
- Or the charging point simply does not honour the 43kW.

I am attaching two screenshots of two charging sessions at different stations.

I would be grateful for any insight you can provide on this observation!

![SmartSelect_20210510-175840_CanZE](https://user-images.githubusercontent.com/5452404/130044850-3700bfed-e821-49c8-83a5-1b8068477564.jpg)

![SmartSelect_20210724-213742_CanZE](https://user-images.githubusercontent.com/5452404/130044859-fe99f663-4cb5-485a-9a3b-d3a178be9675.jpg)

**Comment by yoh-there** [comment]
As far as I know this is a limitation that the battery computer sets. We've often heard the Q90 is throttling extremely early in the charge curve. What you are showing is matching pretty well the data we collected, see for rough interpolation if that data the second tab in this spreadsheet https://docs.google.com/spreadsheets/d/1zDhdxQWK0W7SLOC40KOZc_lyTW6vkk5KnUB6xARV55I/edit?usp=sharing

Closing call (not CanZE issue and AFAWK a known behavior of the Q90 model)
