### ISSUE TITLE
RFE: in cells voltage display some statistics like minimum and maximum

### ISSUE THREAD

**Issue by muayyad-alsadi** [fesch/CanZE#713]
Hello,

I would like to thank you for this useful software

it would be nice to report minimum and maximum cells voltage (of the high voltage battery) in the cells voltage graph
because if those two reading are close to gather it's a good indicator, if there is a wide gap between the two it's a bad indicator

**Comment by muayyad-alsadi** [comment]
current

![can-ze-before](https://user-images.githubusercontent.com/1312683/130349100-26246241-afc3-4f59-9c6c-8ac53f35c3f3.jpeg)

desired

![can-ze-after](https://user-images.githubusercontent.com/1312683/130349098-48204eee-f8b8-4af2-b1c7-61705386d6fe.jpeg)

**Comment by muayyad-alsadi** [comment]
while looking at the code, it seems already report min/max

https://github.com/fesch/CanZE/commit/b4024b5ede57ab4d7ad236132dd81597911fe310

was this commit released google play?

**Comment by FulminatingGhost** [comment]
Hi,
You can see minimum and maximum voltage in the cell voltage heatmap view.

**Comment by muayyad-alsadi** [comment]
Can we add it to the graph?

**Comment by fesch** [comment]
I have updated the plotter widget accordingly to this. The next release will display min / max.

**Comment by muayyad-alsadi** [comment]
Thank you very much
