### ISSUE TITLE
Some trouble with ELM327

### ISSUE THREAD

**Issue by whatswron** [fesch/CanZE#714]
Failure on start CanZE with ELM327. See screenshot

![Screenshot_20210825-143600](https://user-images.githubusercontent.com/89651087/131149047-477ef809-5158-46be-853f-b42a13edb918.png)

**Comment by fesch** [comment]
What ELM327 do you use?

**Comment by whatswron** [comment]
sorry, no idea who the manufacturer is. see photo

**Comment by fesch** [comment]
What photo?

**Comment by whatswron** [comment]
Send photo as Attachement. I try it again

**Comment by fesch** [comment]
You can't post photos using mail.
You have to post them directly onto Github in your browser!

**Comment by whatswron** [comment]
![IMG_20210827_193244_3](https://user-images.githubusercontent.com/89651087/131389588-4f272a70-33d3-419a-8aa1-a913e0f100f3.jpg)

**Comment by Albino-Zoe** [comment]
As a test, I had this very, very cheap, same dongle, it has version 2.1 and therefore cannot work (see https://github.com/fesch/CanZE/issues/709)
