### ISSUE TITLE
Some connection issues with ELM327

### ISSUE THREAD

**Issue by Flodesirat** [fesch/CanZE#716]
Hello,

I bought an ELM327 Bluetooth on amazon: https://www.amazon.fr/gp/product/B093T5V55Q  but I have some issues.

I tried to connect to my Kadjar with "Car Scanner" App and it works correctly (read motor variables perfectly) and after, I tried to connect to my Zoe ZE50 with CanZE but impossible to connect it and read values.

Pop-up messages appeared: "Unrecognized ELM version response [atws<cr>?<cr><cr>>]", "Unrecognized ELM version response [atws<cr>?]", "ELM is not responding (toughness = 0)", "Timeout on [atws] []"

Smartphone information:
Samsung Galaxy S10e - Android 11

Some pictures:
![Screenshot_20210901-214826_CanZE](https://user-images.githubusercontent.com/6069626/131743372-83b11865-cbdb-4bcd-b959-2dad828dd023.jpg)
![Screenshot_20210901-214502_CanZE](https://user-images.githubusercontent.com/6069626/131743381-fb73c1c5-e755-4f30-9c35-c70b11f93811.jpg)
![Screenshot_20210901-214421_CanZE](https://user-images.githubusercontent.com/6069626/131743400-be64ef31-eec0-406e-bc48-e4b4fbcab7dd.jpg)
![Screenshot_20210901-214644_CanZE](https://user-images.githubusercontent.com/6069626/131743405-12c86a35-27e3-49ca-a369-cf421221a50f.jpg)
![20210901_222210](https://user-images.githubusercontent.com/6069626/131743412-b2854c88-a311-452c-b510-a13e2a0da6c9.jpg)

I hope it is not a big issue and I am available if it is necessary to do some additional tests.

Thanks.

**Comment by fesch** [comment]
Your dongle seams not to be compatible with CanZE.

https://canze.fisch.lu/elm327/

**Comment by Flodesirat** [comment]
It could be possible to put a clear message in the pop-up as: "Your ODB device is not compatible" or "Your ODB device seems to be not compatible" ?

**Comment by fesch** [comment]
Right, but the software is unable to distinguish the cases "incompatibale ELM" and "timeout on a compatible ELM" ...

**Comment by Flodesirat** [comment]
Ok, thanks
