### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Limpan4all** [fesch/CanZE#718]
I live in Sweden so we have cold winters and I would like to know more about the heating system. Zoe ZE40 R110 2019.

Is it any way to see when battery heating is on and at what power? Can it be logged?
Is it any way to see if the PTC heaters are on and on what power level? Can it be logged?

And now to the hard question/suggestion.
Would it be possible to "force" battery heating to be on with the car in the "off" state to do proper preheating from say -15C to +10C prior to departure? Starting numerous 10min preheat cycles is what we are doing now, but that is a stupid workaround.
And the related issue, when driving it is a need for heating the battery to get above 10C to get full charging capacity (22kW) otherwise it will be limited due to cold battery. So IF it would be possible with a CAN message to turn on and keep the battery heating to stay on it would be fantastic for winter driving longer distances, even if it would "waste" energy prior to charging.

The next thing is a better way of heating inside when charging on trips in wintertime, the workaround by locking the doors and start preheat thru the FOB or the app works but that is not hot enough when it is -15C outside (it looks like the output from the heater is limited to 20C air, but the cooling effect is rather high).

I fully understand that you do not want to mess with the car by injecting CAN commands into it. But it would be a great advantage to the CanZE app and Zoe usage in a cold winter climate.

**Comment by yoh-there** [comment]
Apologies for the very late answer.

Battery heating can be viewed in the Climate screen (HV Bat conditioning mode).

I don't know about the PTCs. We have removed "PTCx relay" long ago as they always reported "off", but if you want to dig into it you can always use the research screen; the uploads for it as the same format as the regular _Fields.csv in the source code.

I have no idea if it's possible to instruct the car to pre-heat the battery, and while I understand your question, I dare to state that none of the developers are going to try. If you're daring you might want to use DDT4ALL and be brave with it. The ZE50 will pre-heat if it's on scheduled charging, but that is useless to you (and me).

As I believe all issues are addressed (though probably with unsatisfactory answers), I am closing this issue, feel free to reopen.
