### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by Rpp131** [fesch/CanZE#722]
Hi, I am a new user of Canze version 1.6 on a 2019  40kwh Zoe R110. I have the recommended Konnei code reader. When reading data, the message 'debug xxxx failed' appears frequently. Also 'Bluetooth connection lost' and 'ELM not responding....'
Typical screen shots attached.
![Screenshot_2021-11-13-13-29-20](https://user-images.githubusercontent.com/94389674/141822772-d17fa671-fe9e-4fe4-983d-d508f943c4f6.png)
![Screenshot_2021-11-13-13-27-14](https://user-images.githubusercontent.com/94389674/141822775-04d5f933-fa83-4822-8c15-b2b041472123.png)
![Screenshot_2021-11-13-13-27-04](https://user-images.githubusercontent.com/94389674/141822777-7f1f936d-8910-4820-94be-98508ae0e590.png)
![Screenshot_2021-11-13-13-23-13](https://user-images.githubusercontent.com/94389674/141822781-f4befba7-00b2-4d2a-8cf7-267b8a8569f1.png)
![Screenshot_2021-11-13-13-22-50](https://user-images.githubusercontent.com/94389674/141822783-b06f4304-73a8-4a40-ab9e-24022f31f84b.png)

I do collect some data but it seems slow and erratic. The Bluetooth light flashes continuously.

Do you think the code reader is faulty?

**Comment by yoh-there** [comment]
There are always comms errors, and KONNWEIs are slow (but fairly reliable) indeed. My advice would be to double-check that the car tyoe is set correctly in the settings, and set the log level to None. The latter supress these popups that, by nature stay on the screen for a fixed amount of time.

**Comment by Rpp131** [comment]
Thanks for the quick response.  I will set the log level to none and double
check the correct car is selected.  Is it normal for the blue tooth led to
flash continuously on the Konnwei?  The manual is not much help.

Regards

**Comment by yoh-there** [comment]
It is, we're polling the car as fast as the KONNWEI will go.

**Comment by Rpp131** [comment]
Once again, thanks for the quick response!
