### ISSUE TITLE
ZE50 R135 tires infos 

### ISSUE THREAD

**Issue by matizoe** [fesch/CanZE#724]
on the ZE50 R135, with the Konnwei KW902 dongle, I can connect and retrieve all the battery and charge information successfully.

However I get no information at all about the Tires, the Tires menu even disappears once the Bluetooth connection is established,
I had to add the Tires manually in the settings to see the Tires panel.

Then I got only this : 

<img width="350" alt="Screenshot_20211118-153800__01" src="https://user-images.githubusercontent.com/94652597/142509323-35a38555-7e09-47ca-b1ba-4f09108fdef3.jpg">

**Comment by FulminatingGhost** [comment]
Hello,

the tires information is not available for the new Zoe.
See issue #697 for more explenation.
