### ISSUE TITLE
Feature Request: HomeAssistant integration or any kind of API?

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [fesch/CanZE#726]
Hey there. I am HomeAssistant fan-boy and owner of a Zoe R135.

At the moment I try to find ready, solid way to bring the Zoe ODB-2 to my homeassistant.
I read this here:
https://github.com/fesch/CanZE/issues/460#issuecomment-292452566
So I gues there is no wish from @fesch to integrate a SIM way to do this but what happened on then menawhile (from 2017).

Is there a chance to get live data in any way? For example with a kind of android phone, akting as a bridge...

Hope to get some answers and thanks a lot for this nice project :)

**Comment by yoh-there** [comment]
This will not be happening as in, by the current developers, but for what you want it might be a far better idea to tap into the Renault API. For the ZE50s the API is much better than for the old Ph1 cars. There a few nice nodejs classes floating around.

If you really want to get to the car's CANbus from your home system, your best route would be to use a CanSee dongle, as it can use WiFi and thus attach to your home network. The commands are documented and easy to understand, and all the parameters are well documented in CanZE's source code.

I am closing this request as it's not a CanZE thing.
