### ISSUE TITLE
Renault ZOE ZE50 DTC menu greyed out

### ISSUE THREAD

**Issue by Dan3333333** [fesch/CanZE#728]
Hey,
Can you please tell me why my DTC menu is greyed out and how can I access it.

Adapter used is KONNWEI KW902 wifi. iOS 15.1
![0AC95807-140B-4A23-9406-E9A3CB8B55B2](https://user-images.githubusercontent.com/87605704/145526926-bd313ccc-44df-4d16-b4a5-d3c1d84de989.jpeg)
![2E60A88A-4987-4263-B025-516A3E095B8D](https://user-images.githubusercontent.com/87605704/145526931-d8cb9bbe-29af-4de7-982e-83796817ce49.jpeg)

**Comment by Dan3333333** [comment]
Same for ELMT testing
![796E5686-BE0C-4E98-86BE-3715DDE13D16](https://user-images.githubusercontent.com/87605704/145571853-cfc5246d-3a19-4997-b842-dc471b6f510c.jpeg)

**Comment by ik2wxx** [comment]
ELM testing not needed as the test is in the Settings screen

**Comment by Dan3333333** [comment]
Then how can I test my ESC system for example? Thought it was is ELM testing menu

**Comment by ik2wxx** [comment]
ELM testing is for OBD device compatibility test.

**Comment by Dan3333333** [comment]
Ok, thanks for clarifying this… waiting to find out how can I test my ESC system and how to read DTC codes

**Comment by ik2wxx** [comment]
DTC screen is not implemented yet in iOS version.
I don't have any idea on how you can test ESC system with CanZE.

**Comment by Dan3333333** [comment]
Regarding ESC see https://youtu.be/Fm5bPX5TM8c

**Comment by Dan3333333** [comment]
Just installed your app on an Android phone and DTC menu is not greyed out :( but don't have a bluetooth dongle to use it

**Comment by Dan3333333** [comment]
Any updates on greyed out dtc menu on iOS?

**Comment by ik2wxx** [comment]
iOS development is currently in standby if no other users are willing to partecipate
