### ISSUE TITLE
R90 no tire data

### ISSUE THREAD

**Issue by smulle48** [fesch/CanZE#729]
Hi

I don't get any tire data. This is how it looks (I know it's not connected now)

Can't I read and write tpms id on iOS?
![image](https://user-images.githubusercontent.com/24297824/145566815-ab08a6cb-2cf2-49a5-a856-37f46412282c.png)

[CanZE 1639138721.log](https://github.com/fesch/CanZE/files/7692642/CanZE.1639138721.log)
[Emulator 1639138737.log](https://github.com/fesch/CanZE/files/7692643/Emulator.1639138737.log)

**Comment by ik2wxx** [comment]
Tires info is not fully working as it's not tested.
We can't find anyone with iOS and a suitable Zoe to continue development of this section.

**Comment by smulle48** [comment]
> Tires info is not fully working as it's not tested.
> 
> We can't find anyone with iOS and a suitable Zoe to continue development of this section.

Thanks for the info 😄 

If you need help, I would be more then happy to help you out with whatever I can.

Though I have not developed on iOS before, I've been programming for XboxMediaPlayer (Kodi) among other.

Does the tire page work on android?

**Comment by yoh-there** [comment]
It does, at least when I made it long ago. There is a slight chance something has changed with an updated BCM / BCM firmware.

**Comment by siavashvj** [comment]
Similar issue for R110. Never ending loading of data files / assets. The Read/Write buttons are greyed out. 

I have a KW902 + R110 2019 Zoe + iOS (WiFi). 

Uploading IMG_8394.MP4…

**Comment by ik2wxx** [comment]
> If you need help, I would be more then happy to help you out with whatever I can.
> 
> Though I have not developed on iOS before, I've been programming for XboxMediaPlayer (Kodi) among other.

The sources are online, if you want to collaborate.
