### ISSUE TITLE
screen for researchers ZOE Ph 2

### ISSUE THREAD

**Issue by NB60E** [fesch/CanZE#730]
Hi,
I’m running a ZOE phase 2 build in 2021. Everything works fine: great job !
Via the screen for researchers I want to log:
•	The speed
•	The actual power consumption
•	The SOC
•	The GPS signal
In a post I found the description how to do it, using the _Researcg.csv file
e.g. SOC:	                ,7ec,24,39,.02,0,2,%,222002,622002,ff,State Of Charge (SOC) HV battery
or even GPS:		,800,24,31,0,0,0,,210e,610e,aff,GPS
but I cannot find any of these field definitions in the Assets folder of the github repository. Are the ones mentioned valid fpr ZOE Pahse 2.
Can you help me ?
Tanks

**Comment by yoh-there** [comment]
You can find the actual working entries here: https://github.com/fesch/CanZE/blob/master/app/src/main/assets/ZOE_Ph2/_Fields.csv

As I am fairly sure that answers your question, I am closing this issue. Feel free to reopen.
