### ISSUE TITLE
Manually enable battery heater via CAN injection

### ISSUE THREAD

**Issue by Sterillium** [fesch/CanZE#731]
Does anyone know what the IDs and messages are associated with the activation of the battery heater?

My ZE40 Q90 was charging at around 7kW recently on a 43kW charger due to a cold battery (around 2°C at 25% SOC). The battery heater turned on as soon as the charger was connected but I would like to be able to manually turn on/off the battery heater before I start a charge (on the way to the charger) as the 400W heater only raises the temperature of the battery a few degrees per hour.

**Comment by yoh-there** [comment]
We don't have that info. Maybe in DDT4ALL, but I think at most it can be triggered through scheduled charging. TOtally speculative though. Closing as we do not do writing to the car
