### ISSUE TITLE
Bluetooth connection

### ISSUE THREAD

**Issue by EnyxKudo** [fesch/CanZE#733]
Hello,

I have some issue with my first connection on my ELM237 bluetooth dongle (generic u guess ?)

Here the error message in the OBD2 diagnostics
![image](https://user-images.githubusercontent.com/96838373/147688383-6b36d0eb-396e-43ad-ac0a-3fe918cbfa90.png)

Thx for the help

**Comment by fesch** [comment]
Your dongle is not compatible.
