### ISSUE TITLE
a

### ISSUE THREAD

**Issue by KarelSvo** [fesch/CanZE#738]
H

**Comment by iboboc** [comment]
https://alphatech.technology/Howto-Entry-srk/Google-Services-Json-bek/
https://firebase.google.com/docs/android/setup

**Comment by KarelSvo** [comment]
Thanks, I had already read the links and tried to follow them. Unfortunately not successful.

**Comment by iboboc** [comment]
Have you downloaded your google-services.json file?
Have you placed it in \app folder?
