### ISSUE TITLE
Bluetooth permission in Android 12

### ISSUE THREAD

**Issue by iboboc** [fesch/CanZE#740]
If you use/build the app for Android 12 or higher, the Settings will crash because you need to add additional following three new permissions:

    [BLUETOOTH_CONNECT](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_CONNECT): required to connect to paired Bluetooth devices.
    [BLUETOOTH_SCAN](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_SCAN): equired to scan and pair nearby Bluetooth devices.
    [BLUETOOTH_ADVERTISE](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_ADVERTISE): required to advertise to nearby Bluetooth devices.
    
    https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by fesch** [comment]
Should be fixed in the latest version (introducing other problems :-()
