### ISSUE TITLE
Unable to get data with CANZe

### ISSUE THREAD

**Issue by duodiscus92** [fesch/CanZE#741]

**Comment by duodiscus92** [comment]
Hi
I have a dongle Konnwei kw902 and a Zoe e-tech R110 bought in july 2021
I never succeed to get data from my car using CANZE under android.
Connection seems to be not stable (continuously trying to reconnect) even when the smartphone is located at a few centimeters from the dongle. However BT is well paired (using parameters). I tryed with two different smartphone : doogee s55 and Huawei.  To be sure there is no interference I have set Zoe BT off.
By the way, I successfully connect using the app which is delivered with the dongle "OBD Check" but it is not suited for electric car so the only info I got is speed.
Could you help me ?
Regards

**Comment by fesch** [comment]
Did you try the dongle test script?
https://canze.fisch.lu/dongle-test-script/

You may also want to read this:
https://cvtz50.info/en/elm327/

**Comment by duodiscus92** [comment]
Thanks so much
I will run the test script
Attrached is a picture of my dongle : it seems that it has the good PIC model and a 4 MHz quartz
![IMG_20220218_154710](https://user-images.githubusercontent.com/11783220/154737096-e8b12efe-6e8a-4c0b-aef2-5a4b59979aa5.jpg)
.

**Comment by duodiscus92** [comment]
running the script gives the following responses. It seems than I can forget this dongle and buy another
because I received no data when typing 03222006

11:35:32.074 Connecting to KONNWEI ...
11:35:32.406 Connected
11:35:45.955 atz
11:35:45.975 ELM327 v1.5
11:42:34.635 >11:42:52.771 ate0
11:42:52.997 OK
11:42:52.997
11:42:52.997 >11:43:04.469 ats0
11:43:04.726 OK
11:43:04.726
11:43:04.726 >11:43:22.989 atsp6
11:43:23.087 OK
11:43:23.087
11:43:23.087 >11:43:36.317 atat1
11:43:36.346 OK
11:43:36.346
11:43:36.346 >11:44:01.238 atcaf0
11:44:01.336 OK
11:44:01.336
11:44:01.336 >11:44:33.317 atsh7e4
11:44:33.523 OK
11:44:33.523
11:44:33.523 >11:45:08.661 atfcsh7e4
11:45:08.914 OK
11:45:08.914
11:45:08.914 >11:45:28.488 03222006
11:45:28.656 NO DATA
11:45:28.656
11:45:28.656 >11:45:57.642 atcra699
11:45:57.874 OK
11:45:57.874
11:45:57.874 >11:46:13.326 atma
11:46:33.445 atar
11:46:33.568 STOPPED

**Comment by yoh-there** [comment]
There has been a batch with wrong termination resistors. Have you been able to check that? see https://canze.fisch.lu/dongle-trouble-4-solution-sort-of/ It seems plausible as you seem to have good connection between device and dongle, but not between dongle and car.

Furthermore, although I am sure you checked, make sure you not only pair in android, but also select the proper  device AND the proper car type in the app.

**Comment by duodiscus92** [comment]
I have measured the resistance between pin 6 and 14 of the connector : 119 ohms. So the value is fine.
>>> ... but also select the proper device AND the proper car type in the app.

Yes, right with CANZE but car type is not relevant when using a terminal app and "at" commands.

I wonder if Renault has not implemented protection on recent vehicles for security reasons. 
Because I borrowed a dongle from professionals (colleagues of mine) and it didn't work better...
So I hesitate to buy another dongle because it's not sure that it will work better ...

I can ask Renault, but it is difficult to find the good guy who will be able (and authorized) to unlock the situation, as
generally they only plug their diag case without asking themselves more questions ...

**Comment by yoh-there** [comment]
> Yes, right with CANZE but car type is not relevant when using a terminal app and "at" commands.

Well actually, it is. For instance, a Ph1 type car will answer it's free frames on an ATMA, but a ZE50 (which yours is) won't, as the "operational" data is behind a secure gateway. 

With the risk of being insulting: please make sure it is NOT on ZOE R90/110 but on ZOE ZE40/ZE50.

**Comment by duodiscus92** [comment]
Not at all, you are not insulting, don't worry :-) 
You are right, currently my CANZE is configured as R90/110 as it is a  Zoe e-tech R110 model.
But no problem I will check with ZE40/ZE50 ...

**Comment by yoh-there** [comment]
Is the dongle in the middle console? => you are right
If the dongle is in the side panel in the foot well => I am right (ZE50)
The model nomenclature is very confusing

**Comment by duodiscus92** [comment]
the obd is located in the side panel in the foot well
But does it mean that the "at" commands for ZE50 are different than as described in the dongle test script ?

**Comment by yoh-there** [comment]
I would have to check. It was a real pain in the ----- to get the ZE50 working. It's very possible that we (I) forgot to adjust the dongle check. Especially as I don't own a ZE50............ Yes, you need to set it to ZE40/ZE50. Pretty sure it will work.

**Comment by duodiscus92** [comment]
I'm going to parking to make the test and let you know the result in a few tenth minutes ...

**Comment by duodiscus92** [comment]
It works !!! (after several months looking for the solution on forums ...)
I have got info like battery cell voltage and much more other ...
Thank you so much for your help !
Regards

**Comment by yoh-there** [comment]
Great. I will close the issue. Feel free to re-open if needed.
