### ISSUE TITLE
Applied electrial torque not showing

### ISSUE THREAD

**Issue by bruvv** [fesch/CanZE#743]
Awesome app! Only thing I'm seeing is when viewing the braking category the "applied electro torque" doesn't work and keeps showing `nannm`. 
All the other stuff is working just fine. What am I missing?
![afbeelding](https://user-images.githubusercontent.com/3063928/156532353-b4b9648f-1031-4a8f-9927-452b8425bdbd.png)
It does show some blue line but that has nothing to do with braking or with accelerating
![Screenshot_20220311-180441.jpg](https://user-images.githubusercontent.com/3063928/157924907-89a5b028-329b-4c15-9666-b13b35980dd7.jpg)

How can I help debug this?

I have a R240 from 2016 and using android 11 on my oneplus 7 pro

**Comment by yoh-there** [comment]
Apologies for the late reply. You can try to switch on "use ISOTP fields" in the settings and of course make sure you select the R240. If that does not help, it's probably an issue with the dongle. Because of this and age I am closing the issue, but feel free of course to reopen
