### ISSUE TITLE
Canze doesn't do anything keeps hanging on debug

### ISSUE THREAD

**Issue by bruvv** [fesch/CanZE#744]
When using the icar pro sometimes it works just fine and I can read out everything and sometimes it just doesn't do anything and when I connect to the dongle using canze on the bottom it shows: debug debug# and doesn't get any data. I test the dongle and it sort of looks good I guess ? Running Android 11 on OnePlus 7 pro and having an Zoë r240 2016 model. I tried it on a q210 2014 model which worked fine. 
![Screenshot_20220311-092805.jpg](https://user-images.githubusercontent.com/3063928/157830800-644eb84d-967b-4272-b646-366c7fdce5bb.jpg)
![Screenshot_20220311-092402.jpg](https://user-images.githubusercontent.com/3063928/157830810-2cf19fc9-d29e-4029-a733-e3affac5c56e.jpg)

When I test it while it is working I see:
![Screenshot_20220311-093144.jpg](https://user-images.githubusercontent.com/3063928/157831095-bfcee987-cf16-45a4-bab7-f986845fe0e0.jpg)

When it hangs on debug it shows:
![Screenshot_20220310-182716.jpg](https://user-images.githubusercontent.com/3063928/157831208-cc3b25b2-939a-4154-9b0e-68e459b179ff.jpg)

Can this be related to my other issue https://github.com/fesch/CanZE/issues/743 ?

**Comment by bruvv** [comment]
Can this be related to my other issue https://github.com/fesch/CanZE/issues/743 ?

**Comment by bruvv** [comment]
Hello. Anyone?

**Comment by bruvv** [comment]
Did you had a change yet to help me out @yoh-there @fesch ?

**Comment by fesch** [comment]
I have no idea about your problem, but it it know that ELM's are not amongst the reliablest beasts :-/

**Comment by bruvv** [comment]
Thanks but can you see anything in the log ? It's also weird that in one car it works better, q210 then in mine r240

**Comment by yoh-there** [comment]
I would suggest to try the KONNWEI 902. I understand it is frustrating when having an (almost) working setup, but some dongles just don't work in all situations. Closing as the issue is stale.
