### ISSUE TITLE
CanZE esp dongle as MQTT client?

### ISSUE THREAD

**Issue by smulle48** [fesch/CanZE#748]
Hi

I was wondering if anyone have tried to setup the CanZE esp dongle as an mqtt client?

The reason is that the provider of my charger unfortunately don't give access to the api of the charger, so I thought it might be possible to modify the code for the CanZE dongle so it (when plugged in) connected to my home wifi and started pushing data to my local mqtt server?

This way I could avoid modifying my breaker box :-)

**Comment by yoh-there** [comment]
The CanSee dongle is a passive device. It doesn't do ANYTHING spontaneously. It sure could be programmed that way, but it isn't and at least from my end not planned. However, it can be contacted over a TCP/IP socket over WiFi. It is very simple do do what you want with ie NodeRed. That would separate the somewhat delicate CANbus codebase from whatever fun things you want to do.

**Comment by SMCinc** [comment]
I use my CANSee dongle in WIFi mode and have a simple bash script in a PI called every minute by crontab. 
This is sufficient for my charge control with evcc.


````sh
#! /bin/sh

rd=/ramdisk


plug=$(tail -n 1 "$rd/plug.txt") 

if [ $plug -gt 1 ]; then

soc=`echo "i7ec,222002" | nc 192.168.xx.yy 35000 -w 1 | cut -c 11-14 | tr '[:lower:]' '[:upper:]' ` &&
soc=$(echo "ibase=16; $soc" | bc) &&
mosquitto_pub -h localhost -t CANSee/RX/SOC -m $(echo "scale=2;($soc*0.02+3)" | bc -l)

odo=`echo "i7ec,222006" | nc 192.168.xx.yy 35000 -w 1 | cut -c 11-16 | tr '[:lower:]' '[:upper:]' ` &&
odo=$(echo "ibase=16; $odo" | bc) &&
mosquitto_pub -h localhost -t CANSee/RX/ODO -m $odo

rng=`echo "i7ec,223451" | nc 192.168.xx.yy 35000 -w 1 | cut -c 11-14 | tr '[:lower:]' '[:upper:]' ` &&
rng=$(echo "ibase=16; $rng" | bc) &&
mosquitto_pub -h localhost -t CANSee/RX/RNG -m $rng

fi
````

Here I have a question:
What ist the reason for BT and Wifi can not be active at the same time (wifi is swiched off in the code) ?
In my case wifi request take only place while charging.
