### ISSUE TITLE
flt4 while charging

### ISSUE THREAD

**Issue by dlehfks** [fesch/CanZE#749]

**Comment by dlehfks** [comment]
i have a problem while i charge my car. 
sometimes it ends up with unpluged which means succesfully or normally
but sometimes it ends up with flt4.  i don't know what this means and can't find it anywhere.
is it kind of fault no.4?  and what this means?? what can i do for this error.??

**Comment by yoh-there** [comment]
Unfortunately, we don't know. flt4 was the only description we found in the scarce documentation.
