### ISSUE TITLE
only dark theme in IOS version?

### ISSUE THREAD

**Issue by AndyIreland** [fesch/CanZE#751]
hello is there only a dark theme when using on Ipad IOS ? - I went into settings and could not find a setting to change to a light theme
Thanks.

**Comment by ik2wxx** [comment]
Hi
What version of CanZE are you using?
Our iOS version has only light theme.

**Comment by AndyIreland** [comment]
3.0.1.0
Thanks

![297578806_459870299321336_2059404100162868535_n](https://user-images.githubusercontent.com/49172217/182487575-80d2fcfb-e815-4525-b55d-58df2974b1db.jpg)

**Comment by ik2wxx** [comment]
I'm sorry that's not the official CanZE app so we can't help.

**Comment by AndyIreland** [comment]
> I'm sorry that's not the official CanZE app so we can't help.

Oh, I am surprised at that, I downloaded it from the official apple App icon on the ipad I am pretty sure! - I thought it was the official one.

**Comment by edddeduck** [comment]
@AndyIreland 

There is a version of the code built by Frédéric Richard on the AppStore. This is using the same source code as a base from my understanding but is a separate branch and not directly linked to the developers working on CanZe in this project. 

There is the TestFlight only version from this GitHub which will say the developer is Roberto Sonzogni.

You can subscribe to the TestFlight version here: https://canze.fisch.lu/install-the-dongle/ This will allow you to install the "official" one.

**Comment by AndyIreland** [comment]
ah right I see, thank you for that
