### ISSUE TITLE
CanZe on laptop/PC

### ISSUE THREAD

**Issue by Ely7777** [fesch/CanZE#757]
Hello,
First of all, thank you very much for creating this app. 
I’ve run into a series of issues when trying to use CanZe in my laptop (Windows, not Mac). 
I’ve tried several Android emulators like Bluestack, Memo, etc, but there is no way that I can connect CanZe with the OBD2 (ELM327) via Bluetooth. I click the icon and it just won’t work. 

I’ve also tried the app with my iPhone but the button “DTC readout” is not available. 

I’d really appreciate some feedback on this issue, as I need to be able to click the DTC readout button, which is not available when using the app on IOS. Thanks in advance!

**Comment by KarelSvo** [comment]
Pyren is better suited for Renault fault diagnosis.  https://gitlab.com/py_ren/pyren/-/blob/master/README.md

https://gitlab.com/py_ren/pyren/-/wikis/home

**Comment by Ely7777** [comment]
Hello, thank you for your answer. Are you saying that there is no other way that I can use CanZe on my laptop? As I've been looking at Pyren but it's all Greek to me. Thanks

**Comment by yoh-there** [comment]
Seems like Win11 can do some android emulation, as can a chromebook. However, I did not get BT communication to work on my Chromebook. Closing for "won't fix"
