### ISSUE TITLE
Electronic Parking Break (EPB) ZOE Z.E. 40

### ISSUE THREAD

**Issue by schmidtas** [fesch/CanZE#759]
Hi CanZE-User and Developer,

would it be possible with CanZE to put the electronic parking break into the service position.
I have to change my brake pads and discs on the rear axle and am looking for a way to open the electronic parking brake.
It would really be a great help if that would work with CanZE.

BR
Alexander

**Comment by yoh-there** [comment]
Hello Alexander,

We do not, by team policy, perform ANY writing function to the car for safety reasons. The only exception is the benign writing of valve IDs of the TPMS system.
