### ISSUE TITLE
iOS for Renault ZE

### ISSUE THREAD

**Issue by langlois50** [fesch/CanZE#762]
I wanted to test canZE application on iOS, on my Kangoo ZE 33 
but testers are no more admited on TestFlight..!
is it possible to reopen it.??
thanks

**Comment by ik2wxx** [comment]
> I wanted to test canZE application on iOS,... but testers are no more admited on TestFlight..! is ti possible to reopen it.?? thanks

We reached the previous limit of 1000 testers....so I now deleted the limit.
Please retry now.
Roberto

**Comment by langlois50** [comment]
> thanks, is there possibility to test it on my Kangoo ZE 33. without risk ??

**Comment by ik2wxx** [comment]
> > thanks, is there possibility to test it on my Kangoo ZE 33. without risk ??

CanZE is for ZOE only
