### ISSUE TITLE
CanZE charging history problem

### ISSUE THREAD

**Issue by MatteoTorba** [fesch/CanZE#768]
Hi. After a zoe lbc update, in CanZE app now i have all charging history parameters reset. Is all 0. Someone can tell me why?
Thank you

**Comment by fesch** [comment]
Some other users reported that the latest version (1.67) works, expect for the charging graphs. It sounds strange, that some values a read and other are not, but if this is related to an update of the LBC, it might not be a CanZE problem and thus related to what others say .... BUT, version 1.63 is reported to still work. Could you try that?

**Comment by yoh-there** [comment]
Graphs work again. History works on my Q210. If this is still an issue, please state car type and build year and we'll see what we can do. If not (in 1.68), please close.

**Comment by MatteoTorba** [comment]
Hi! 1.68 works great. Thank you!

Inviato da Yahoo Mail su Android 
 
  Il lun, 2 ott, 2023 alle 11:05, ***@***.***> ha scritto:   


Graphs work again. History works on my Q210. If this is still an issue, please state car type and build year and we'll see what we can do. If not (in 1.68), please close.
