### ISSUE TITLE
Support for Android 13

### ISSUE THREAD

**Issue by haplo3** [fesch/CanZE#769]
Hello all,

Does CanZE support Android 13 ?

I have a Pixel 6A and the Google Play Store says my phone is not compatible with CanZE.

Thank you,
Haplo

**Comment by Dan-Ashdown** [comment]
I'm also having this issue on a Pixel 6 (Android 13). Would be really great to use your app.

**Comment by fesch** [comment]
This should now be fixed ... at least I hope so.

Please re-open if not ...
