### ISSUE TITLE
Gone with TestFlight again!

### ISSUE THREAD

**Issue by riker82-blip** [fesch/CanZE#777]
Hi,
I have the error message that says that CANZE beta is expired and on TestFlight, not anymore invitation link are allowed.

can you please help me with this?
Thanks

**Comment by Seedler1981** [comment]
I have exact same issue ☹️

**Comment by simbacaterx** [comment]
Same Problem 
Thx for adding to TestFlight again

**Comment by Sofille65** [comment]
Same for me

**Comment by BraxNL** [comment]
Can’t acces testflight anymore as well. “No new invites are being accepted” error.  Hopefully this can be fixed?

**Comment by Groepi** [comment]
I have the same problem. How can I get an Invitation again?

**Comment by ik2wxx** [comment]
Sorry, should be ok now.
