### ISSUE TITLE
Timeout Read iOS Vgate

### ISSUE THREAD

**Issue by BraxNL** [fesch/CanZE#778]
When I try to connect to Canze using Vgate i-car pro I can sort off connect (app first says I’m connected) but after a few second the message “TIMEOUT read” appears, not data is being shown. The Vgate stays blinking blue with random one or two green flashes.

When I try to connect with with a different app, for example “Auto Doctor” the connection is perfect with a steady green light on the Vgate.

What could this be and how to fix it? Help would be very much appreciated!

**Comment by ik2wxx** [comment]
Hello, I have 2 Vgate and they work well. Maybe something has changed in new models.
Please scroll the app main screen to the last page, you will see a "TEST OBD" button.
Use that screen to discover correct OBD connection parameters, then copy/paste the log text here.
Thank you

**Comment by Sofille65** [comment]
Same error on iOS with LeLink via Bluetooth

**Comment by KarelSvo** [comment]
> When I try to connect to Canze using Vgate i-car pro I can sort off connect (app first says I’m connected) but after a few second the message “TIMEOUT read” appears, not data is being shown. The Vgate stays blinking blue with random one or two green flashes.
> 
> When I try to connect with with a different app, for example “Auto Doctor” the connection is perfect with a steady green light on the Vgate.
> 
> What could this be and how to fix it? Help would be very much appreciated!

https://github.com/fesch/CanZE/issues/775

**Comment by ik2wxx** [comment]
> > When I try to connect to Canze using Vgate i-car pro I can sort off connect (app first says I’m connected) but after a few second the message “TIMEOUT read” appears, not data is being shown. The Vgate stays blinking blue with random one or two green flashes.
> > When I try to connect with with a different app, for example “Auto Doctor” the connection is perfect with a steady green light on the Vgate.
> > What could this be and how to fix it? Help would be very much appreciated!
> 
> #775

That thread is about Android app, not iOS

**Comment by KarelSvo** [comment]
> > 
> > #775
> 
> That thread is about Android app, not iOS

https://github.com/fesch/CanZE4iOS/blob/main/CanZE/CanZE/_devices/ELM327.swift#L86
For me the problem looks the same. ATWS timeout = 0 = let MINIMUM_TIMEOUT = 100 
icar pro needs a little more than 120 ms for the response of the elm version.
If the Elm version is not recognized, the connection to the ECU will not be started. ;-)

**Comment by riker82-blip** [comment]
Same issue for me too (iOS with vGate iCar Pro) since the TestFlight invitation code has been renewed. Can you please help?

**Comment by riker82-blip** [comment]
> Hello, I have 2 Vgate and they work well. Maybe something has changed in new models.
> Please scroll the app main screen to the last page, you will see a "TEST OBD" button.
> Use that screen to discover correct OBD connection parameters, then copy/paste the log text here.
> Thank you

Test OBD fails as well with the same Timeout Read error

**Comment by PhilippDrechsler** [comment]
Same for me. 2 months sog it was working well....

**Comment by spr97ajm** [comment]
I have this same issue.

**Comment by Geekfried** [comment]
Same issue for me :-/

**Comment by PhilippDrechsler** [comment]
I do still have the Problem. Do you think this can be solved?

**Comment by thymjan** [comment]
Same here. Connection to dongle is established. But data transfer is interrupted because of timeout with (Testflight) iOS app 1.0.1(18).

With android app data transfer is working flawlessly.

Even with ABRP (iOS) data transfer iis working.

![IMG_4201](https://github.com/fesch/CanZE/assets/12277755/ecae3c90-3c34-40f5-a4ff-4faf85b53bed)
![IMG_4192](https://github.com/fesch/CanZE/assets/12277755/88b12063-6f69-401e-8359-fd959d9d539b)

**Comment by jorismw** [comment]
Same here, such a shame :(

**Comment by Agalash** [comment]
Hello all,

I just bought a VGate BLE and I have the same issue.
Do you know if this problem is specific to this dongle or it’s an IOS bug?

**Comment by druelie** [comment]
In "A Better Route Planer" it works flawlessly, so it cannot be an iOS problem.

**Comment by Sofille65** [comment]
> Hello all,
> 
> I just bought a VGate BLE and I have the same issue. Do you know if this problem is specific to this dongle or it’s an IOS bug?

It is not a dongle problem but the latest version of CANZE is not working properly under iOS. We asked for a roll back but it seems that iOS users are not a priority. So I am not using the app since months

**Comment by ik2wxx** [comment]
> It is not a dongle problem but the latest version of CANZE is not working properly under iOS. We asked for a roll back but it seems that iOS users are not a priority. So I am not using the app since months

Hello all
It's not a priority problem, it's a "car availability" problem.
Will work on that when I will have the car for testing, sorry It's taking so long.
I hope to work on a solution before the end of this month.
Roberto

**Comment by Sofille65** [comment]
> > It is not a dongle problem but the latest version of CANZE is not working properly under iOS. We asked for a roll back but it seems that iOS users are not a priority. So I am not using the app since months
> 
> Hello all It's not a priority problem, it's a "car availability" problem. Will work on that when I will have the car for testing, sorry It's taking so long. I hope to work on a solution before the end of this month. Roberto

Why not putting the previous iOS version? 
this one was working fine

**Comment by ik2wxx** [comment]
Hello all, new version is available. 
No changes from previous versions, just a restore from build 17.
No changes were made in build 18, the only thing changed was the library manager in compiler.
Please remember that for getting correct data, the car must be fully powered on.
If experimenting connection problem with ELM327 OBD, or getting "Test KO" messages, unplug dongle, replug, and retry.
Please let us know.

**Comment by druelie** [comment]
It works again!
Thank you!

**Comment by Agalash** [comment]
Thanks for this version
It works :-)

**Comment by ik2wxx** [comment]
If running into connection troubles, please scroll to the last page in app's main screen, then tap on "TEST OBD". 
It's a special OBD testing page, you can make connection and dialog experiment with your dongle, than if you want you can report results on this page.
Thank you
