### ISSUE TITLE
Problem with power outages not resuming charge

### ISSUE THREAD

**Issue by Nergal8** [fesch/CanZE#780]
Hello, i have a Spring and im part of your beta testers program. I just had a situation that dacia says is normal but maybe you guys can help me.

If you have a spring connected to a charger to charge all night, and for example you have a power outagge let's say of 30m at 10:00PM when it comes back the spring disables the charging mode and unless you unlock the doors or open a door, the car will not resume charging and you will end up with a empty battery in the morning. This is also valid for you guys like me that use a smart socket to control a schedule in witch your car will charge.

Maybe there is something we can do on software, plug or charger to solve this out.

**Comment by yoh-there** [comment]
We do not support car/charging issues, only the CanZE software. But what you describe is normal behavior for the ZOE: the car "falls asleep" and will not be woken up by the power returning. There is a way to keep the car awake without it charging, but you guessed it, it requires power. Closing this issue as it is not CanZE related.
