### ISSUE TITLE
CanZE iOS Tires info is not working

### ISSUE THREAD

**Issue by LukassCZ** [fesch/CanZE#790]
Hello there, does anyone has an advice of how to read and write TPMS codes via iOS version of CanZe? I am not able to get any updates even if I hit “tires learning” on Zoe nor when I am driving continuesly.

![IMG_2779](https://github.com/fesch/CanZE/assets/146636986/632644ec-9a45-4d2f-91e7-4847635d53f5)

**Comment by ik2wxx** [comment]
Hello, as prevoiusly reported, this page does not work as we did not have any compatible Zoe for testing. It will be removed in next version.
