### ISSUE TITLE
Bluetooth support for Konnwei in iOS

### ISSUE THREAD

**Issue by krekr** [fesch/CanZE#792]
I just got confirmation that the WiFi version isn't produced anymore and will not come back. This is after receiving and returning 3 WiFi-versions that turned out to be BLE or Bluetooth. 

This might be something to add to the "Hardware" documentation at https://canze.fisch.lu/hardware/ to prevent others falling into this rabbithole. I will be making a Cansee, but others might not be able to. Is BLE/Bluetooth support planned for the iOS version? I'd be happy to help testing and debugging.

![image](https://github.com/fesch/CanZE/assets/5542033/16d9be84-7e0b-4efe-8dfe-9178ebc2bcd4)

**Comment by yoh-there** [comment]
@ik2wxx Should we stop mentioning the KONNWEI WiFi for iOS, and maybe advise that BLE dongle you have tested?

**Comment by ik2wxx** [comment]
OBD dongle I've tested, from left to right, top to bottom:

Konnwei (WiFi)
Vgate (BLE), 2 different models.
LELink (BLE)
CanSee (WiFi) not in picture

![IMG_7633](https://github.com/fesch/CanZE/assets/948445/05639a61-1b15-44cf-b7ae-8bf61ee112d0)
![IMG_7632](https://github.com/fesch/CanZE/assets/948445/698859f7-2df5-4997-baa3-da386ad8a5e1)
