### ISSUE TITLE
Twingo EV + Vgate iCar pro + iOS showing no data

### ISSUE THREAD

**Issue by Lkukac** [fesch/CanZE#800]
New EV Twingo (2 months old), using Vgate iCar Pro dongle is connected and recognized by CanZE. 
However all the screens shows empty data
iOS 17.6.1
CanZE 1.0.1(21)
Vgate iCar Pro BLEv4.0 Dual the latest firmware
![IMG_3617](https://github.com/user-attachments/assets/bd5c8745-663c-41e8-8c51-8e3ec1cf68d8)

**Comment by Lkukac** [comment]
Is there anyone that could take a look at this issue ?

**Comment by ik2wxx** [comment]
Twingo has been added as an experiment, I can't confirm that CanZE iOS can work with Twingo as I did never tried.

**Comment by Lkukac** [comment]
Hi, I am ready to be a beta tester. Just let me know what is needed.

pon, 9. ruj 2024. u 07:24 Roberto Sonzogni ***@***.***>
napisao je:
