### ISSUE TITLE
Save KM to dest when switching screens

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#84]
By mail, MH

@fesch : I get no grip on wat is saved between screens in Android and what not. Can you enlighten me a bit?

**Comment by fesch** [comment]
When switching between screens, only the values received by the ELM, which are stored in the Fields class are persistent. All other things are getting lost because actually an activity is being destroyed an another one is set up from zero.
To remember things when an activity closes, you must implement some kind of saving onPause an some other that resumes this onResume.

**Comment by yoh-there** [comment]
Is a decent strategy to save in a public property of MainActivity? Or is that totally destroyed too when switching to another activity? I realize IF it would work, it would not survive exiting the app.

**Comment by fesch** [comment]
You may push it into a public of even static attribute of the MainActivity. That would work when shitching between the scnreens, but yes, the information will be lost if the app is closed.

Better use a sharedPreferences file. Take a look at SettingsActivity, line 45

**Comment by yoh-there** [comment]
Yep, I get that. Would you like me to use the same SharedPreferences blob for this (lu.fisch.canze.settings) and commit i.e. a kmToDest variable to it (I assume just doing that would not kill the existing variables in that blob), or should I instead always create a new SharedPreferences blob per activity? What is the "best practice" here?

**Comment by fesch** [comment]
I have no ieade what is the best practice here, but I suggest to use the SAME file, as it is the same application. Otherwise the filesystem will be populated with too many files I suppose.
If you do not overwrite some of the other preferences, they will stay as they are.

**Comment by yoh-there** [comment]
I fixed this, improved the logic, and added "double destination distance (for round trip usage)
