### ISSUE TITLE
Control Pilot time plot chart

### ISSUE THREAD

**Issue by MartijnEV** [fesch/CanZE#88]
In the Charge section it would be very nice if we could have a time plotted chart of the control pilot value, which would be plotted during a charge session, (and ideally also be saved until the next charge session starts).

This way we can have a "peek" into what is happening during a the smart charge process, or load balancing process, if present on a particular charger.

**Comment by yoh-there** [comment]
@fesch Being the widget man, would it be something you're interested in to add to i.e. the Battery activity?

**Comment by fesch** [comment]
Yes, I'll do that. I'm working anyway yet on a method to make the graph data persistent.

I am myself annoyed by the fact that if I change between the screens, the plotted data is lost :-/ Certainly the time when the requested fields are not being polled will miss, but at least the previous data should remain.

For the charging, I will have to add some "stop" event. Indeed if you start charging in the evening and come back in the morning, the graph may be moved to far so you won't see nothing anymore. Or maybe change the timeplot. I'll see ...

**Comment by yoh-there** [comment]
I do know you mean adding logic to stop the sampling, but at least here is your trigger:

public static final String SID_ChargingStatusDisplay            = "65b.41";

3 is charging, anything else is not charging (waiting, unplugged, etc)

**Comment by fesch** [comment]
I'm working on something ...

**Comment by yoh-there** [comment]
I think now that using the control pilot is not the proper field to use, as we don't know the the phase count. Better would be to use AvChargingPower (427.40)

**Comment by yoh-there** [comment]
This issue is not forgotton. I am working on some graphs here. Should make it to the experimental section any day now. BTW, the widgets are not very easy to use, an d I really love the gradients.

**Comment by yoh-there** [comment]
Done, needs some debugging, but closing
