### ISSUE TITLE
CanZE crashes while driving in Braking screen

### ISSUE THREAD

**Issue by fesch** [fesch/CanZE#89]
This happened today twice within some minutes of the start :-/

**Comment by yoh-there** [comment]
Noticed it too as being the least stable screen. I will look into it, but wouldn't mind an extra pair of eyes looking for obvious stupidities.

**Comment by yoh-there** [comment]
I don't see anything wrong in the code. The only thing different from at lest the screens I wrote, is that it is the only one doing ATMA queries (meaning a SID with only one dot) exclusively).

**Comment by yoh-there** [comment]
I added a useless ISO-TP command to it, to check if it improves stability.

**Comment by yoh-there** [comment]
I am going to close this issue. It is either the addition of an ISO-TP command or the improvement of the ELM driver (which is what I hope). I will test privately with removing the ISO-TP again. 

Let me know if the problem still occurs please.
