### ISSUE TITLE
Copied from spreadsheet: Battery balancing

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#91]
By AM

**Comment by yoh-there** [comment]
@avataranedotas Any progress here Alexandre? I can only say that for the Zoe it is, as far as I can see, not equal to what you suspected for the Fluence.

**Comment by avataranedotas** [comment]
In the Fluence it seems to be exactly as in the Nissan Leaf.

Requesting 02 21 07 on the LBC. The 4 least significant bits on each byte will represent the active cell shunts. On the first byte, bit 3=cell 1, bit 2 = cell 2, bit 1 = cell 3 and bit 0 = cell 4. Second byte cells 5 to 8, so on until you get the 96 cells.

**Comment by yoh-there** [comment]
OK, what I will do then is try that command one more time on the Zoe, report back here and in the spreadsheet and then close this item. Thanks!

**Comment by yoh-there** [comment]
I will close this issue soon, as we have managed to get definition of diagnostics fields. I will change the implementation of this issue to "balancing on/off indication on the advanced charging screen".

**Comment by yoh-there** [comment]
Closed, implemented in commit #362
